;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-337F-7354-97                      |
; |                       Paul Gilbert, ScummVM Team                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : D230968536F66521C8509B62FB36D0332F89FD02F6A76A033D733991793ACFBE
; Input MD5    : B3AEE79419926BB722F6AE0C12832EBF
; Input CRC32  : 932841EA

; File Name   : C:\dev\lota\configur.exe
; Format      : MS-DOS executable (EXE)
; Base Address: 1000h Range: 10000h-13540h Loaded length: 26F0h
; Entry Point : 1000:5CE
; OS type         :  MS DOS
; Application type:  Executable 16bit

                .686p
                .mmx
                .model large

; ===========================================================================

; Segment type: Pure code
seg000          segment byte public 'CODE' use16
                assume cs:seg000
                assume es:nothing, ss:nothing, ds:dseg, fs:nothing, gs:nothing
                db 10h dup(0)

; =============== S U B R O U T I N E =======================================

; CONFIGUR.EXE main: read/validate DRCONFIG.DAT, print the current disk configuration, and (on Y) prompt for the new drive letter(s) and rewrite the file. Standalone MSC -- not a LEGLIB client.
; Attributes: noreturn bp-based frame

; int __cdecl main(int argc, const char **argv, const char **envp)
_main           proc near               ; CODE XREF: start+8D↓p

var_7A          = byte ptr -7Ah
var_78          = byte ptr -78h
var_76          = byte ptr -76h
var_74          = byte ptr -74h
var_72          = byte ptr -72h
var_71          = byte ptr -71h
var_70          = byte ptr -70h
var_6F          = byte ptr -6Fh
var_22          = word ptr -22h
var_20          = byte ptr -20h
argc            = word ptr  4
argv            = dword ptr  6
envp            = dword ptr  0Ah

                push    bp
                mov     bp, sp
                sub     sp, 7Ah
                push    di
                push    si              ; int *
                cmp     [bp+argc], 5
                jz      short loc_10021
                jmp     loc_1011A
; ---------------------------------------------------------------------------

loc_10021:                              ; CODE XREF: _main+C↑j
                mov     bx, word ptr [bp+argv]
                mov     bx, [bx+2]
                mov     di, bx
                lea     si, [bp+var_20]
                mov     ax, ds
                mov     es, ax
                assume es:dseg
                mov     cx, 0FFFFh
                xor     ax, ax
                repne scasb
                not     cx
                sub     di, cx
                xchg    di, si
                shr     cx, 1
                repne movsw
                adc     cx, cx
                repne movsb
                lea     ax, [bp+var_22]
                push    ax              ; unsigned int
                mov     ax, 8002h
                push    ax
                lea     ax, [bp+var_20]
                push    ax              ; char *
                call    __dos_open
                add     sp, 6
                or      ax, ax
                jz      short loc_10065
                mov     ax, 0FFFFh
                push    ax              ; int
                call    _exit
; ---------------------------------------------------------------------------
                add     sp, 2

loc_10065:                              ; CODE XREF: _main+49↑j
                mov     bx, word ptr [bp+argv]
                mov     bx, [bx+4]
                mov     di, bx
                lea     si, [bp+var_72]
                mov     ax, ds
                mov     es, ax
                mov     cx, 0FFFFh
                xor     ax, ax
                repne scasb
                not     cx
                sub     di, cx
                xchg    di, si
                shr     cx, 1
                repne movsw
                adc     cx, cx
                repne movsb
                mov     bx, word ptr [bp+argv]
                mov     bx, [bx+6]
                mov     di, bx
                lea     si, [bp+var_72]
                mov     ax, ds
                mov     cx, 0FFFFh
                xor     ax, ax
                repne scasb
                not     cx
                sub     di, cx
                mov     bx, cx
                xchg    di, si
                mov     cx, 0FFFFh
                repne scasb
                dec     di
                mov     cx, bx
                shr     cx, 1
                repne movsw
                adc     cx, cx
                repne movsb
                mov     bx, word ptr [bp+argv]
                mov     bx, [bx+8]
                mov     di, bx
                lea     si, [bp+var_72]
                mov     ax, ds
                mov     cx, 0FFFFh
                xor     ax, ax
                repne scasb
                not     cx
                sub     di, cx
                mov     bx, cx
                xchg    di, si
                mov     cx, 0FFFFh
                repne scasb
                dec     di
                mov     cx, bx
                shr     cx, 1
                repne movsw
                adc     cx, cx
                repne movsb
                mov     ax, 9B0h
                push    ax              ; unsigned int *
                mov     ax, 3
                push    ax              ; unsigned int
                lea     ax, [bp+var_72]
                push    ss
                push    ax              ; void far *
                push    [bp+var_22]     ; int
                call    __dos_write
                add     sp, 0Ah
                or      ax, ax
                jz      short loc_10105
                mov     ax, 0FFFFh
                push    ax              ; int
                call    _exit
; ---------------------------------------------------------------------------
                add     sp, 2

loc_10105:                              ; CODE XREF: _main+E9↑j
                push    [bp+var_22]     ; int
                call    __dos_close
                add     sp, 2
                sub     ax, ax
                push    ax              ; int
                call    _exit
; ---------------------------------------------------------------------------
                add     sp, 2
                jmp     short loc_1012F
; ---------------------------------------------------------------------------
                align 2

loc_1011A:                              ; CODE XREF: _main+E↑j
                mov     cx, 0Dh
                lea     di, [bp+var_20]
                mov     si, 42h ; 'B'
                mov     ax, ss
                mov     es, ax
                assume es:nothing
                shr     cx, 1
                repne movsw
                adc     cx, cx
                repne movsb

loc_1012F:                              ; CODE XREF: _main+107↑j
                lea     ax, [bp+var_22]
                push    ax              ; unsigned int
                mov     ax, 8002h
                push    ax
                lea     ax, [bp+var_20]
                push    ax              ; char *
                call    __dos_open
                add     sp, 6
                or      ax, ax
                jz      short loc_1017D
                call    getVideoPage    ; int 10h AH=0Fh -- cache the active display page (BH) in cs:byte_1056C.
                call    clearScreen     ; blank the whole 80x25 screen (int 10h AH=06h scroll-up, full window, attribute 7).
                sub     ax, ax
                push    ax
                push    ax
                call    gotoXY          ; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
                add     sp, 4
                mov     ax, 4Fh ; 'O'
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 7Ch ; '|'
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 0BBh
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 0FFFFh
                push    ax              ; int
                call    _exit
; ---------------------------------------------------------------------------
                add     sp, 2

loc_1017D:                              ; CODE XREF: _main+133↑j
                mov     ax, 0FC8h
                push    ax              ; unsigned int *
                mov     ax, 3
                push    ax              ; unsigned int
                lea     ax, [bp+var_72]
                push    ss
                push    ax              ; void far *
                push    [bp+var_22]     ; int
                call    __dos_read
                add     sp, 0Ah
                mov     al, [bp+var_72]
                mov     [bp+var_7A], al
                mov     al, [bp+var_71]
                mov     [bp+var_74], al
                mov     al, [bp+var_70]
                mov     [bp+var_78], al
                push    [bp+var_22]     ; int
                call    __dos_close
                add     sp, 2
                call    getVideoPage    ; int 10h AH=0Fh -- cache the active display page (BH) in cs:byte_1056C.
                call    clearScreen     ; blank the whole 80x25 screen (int 10h AH=06h scroll-up, full window, attribute 7).
                sub     ax, ax
                push    ax
                push    ax
                call    gotoXY          ; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
                add     sp, 4
                mov     ax, 0CFh
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 116h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 15Dh
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 1A4h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                cmp     [bp+var_78], 32h ; '2'
                jnz     short loc_1021A
                mov     ax, 1EDh
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 221h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 247h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 27Ch
                push    ax              ; char *
                call    _printf
                add     sp, 2
                sub     ax, ax
                jmp     loc_102B9
; ---------------------------------------------------------------------------
                align 2

loc_1021A:                              ; CODE XREF: _main+1DA↑j
                cmp     [bp+var_78], 30h ; '0'
                jnz     short loc_10264
                mov     ax, 2A6h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 2D8h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     al, [bp+var_74]
                cmp     [bp+var_7A], al
                jnz     short loc_1024E
                mov     al, [bp+var_7A]
                sub     ah, ah
                push    ax
                mov     ax, 2FCh

loc_10245:                              ; CODE XREF: _main+27F↓j
                push    ax              ; char *
                call    _printf
                add     sp, 4
                jmp     short loc_102C0
; ---------------------------------------------------------------------------

loc_1024E:                              ; CODE XREF: _main+22A↑j
                mov     al, [bp+var_74]
                sub     ah, ah
                push    ax
                mov     al, [bp+var_7A]
                push    ax
                mov     ax, 307h

loc_1025B:                              ; CODE XREF: _main+28F↓j
                push    ax              ; char *
                call    _printf
                add     sp, 6
                jmp     short loc_102C0
; ---------------------------------------------------------------------------

loc_10264:                              ; CODE XREF: _main+20E↑j
                cmp     [bp+var_78], 31h ; '1'
                jnz     short loc_102A2
                mov     ax, 31Bh
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 34Dh
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     al, [bp+var_74]
                cmp     [bp+var_7A], al
                jnz     short loc_10292
                mov     al, [bp+var_7A]
                sub     ah, ah
                push    ax
                mov     ax, 36Fh
                jmp     short loc_10245
; ---------------------------------------------------------------------------
                align 2

loc_10292:                              ; CODE XREF: _main+274↑j
                mov     al, [bp+var_74]
                sub     ah, ah
                push    ax
                mov     al, [bp+var_7A]
                push    ax
                mov     ax, 37Ah
                jmp     short loc_1025B
; ---------------------------------------------------------------------------
                align 2

loc_102A2:                              ; CODE XREF: _main+258↑j
                mov     ax, 38Eh
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 3B5h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 0FFFFh

loc_102B9:                              ; CODE XREF: _main+206↑j
                push    ax              ; int
                call    _exit
; ---------------------------------------------------------------------------
                add     sp, 2

loc_102C0:                              ; CODE XREF: _main+23C↑j
                                        ; _main+252↑j
                sub     ax, ax
                push    ax
                call    setTextColor    ; set the text attribute for subsequent printf output (int 10h AH=10h) -- arg!=0 selects the highlight colour (6/7), else normal (0x20).
                add     sp, 2
                mov     ax, 3DFh
                push    ax              ; char *
                call    _printf
                add     sp, 2

loc_102D3:                              ; CODE XREF: _main+2D3↓j
                call    readKeyUpper    ; wait for a keypress (_bios_keybrd(0)) and return it folded to upper case.
                mov     [bp+var_76], al
                cmp     al, 59h ; 'Y'
                jz      short loc_102E5
                cmp     al, 4Eh ; 'N'
                jz      short loc_102E5
                cmp     al, 1Bh
                jnz     short loc_102D3

loc_102E5:                              ; CODE XREF: _main+2CB↑j
                                        ; _main+2CF↑j
                cmp     [bp+var_76], 59h ; 'Y'
                jz      short loc_102EE
                jmp     loc_104E6
; ---------------------------------------------------------------------------

loc_102EE:                              ; CODE XREF: _main+2D9↑j
                mov     ax, 0Ah
                push    ax
                mov     ax, 4Fh ; 'O'
                push    ax
                mov     ax, 6
                push    ax
                sub     ax, ax
                push    ax
                call    clearRegion     ; blank a rectangular region (int 10h AH=06h) -- args col1,row1,col2,row2.
                add     sp, 8
                mov     ax, 6
                push    ax
                sub     ax, ax
                push    ax
                call    gotoXY          ; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
                add     sp, 4
                mov     ax, 414h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                cmp     [bp+var_78], 30h ; '0'
                jnz     short loc_10326
                mov     ax, 447h
                jmp     short loc_10329
; ---------------------------------------------------------------------------
                align 2

loc_10326:                              ; CODE XREF: _main+30E↑j
                mov     ax, 459h

loc_10329:                              ; CODE XREF: _main+313↑j
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 46Ah
                push    ax              ; char *
                call    _printf
                add     sp, 2

loc_1033A:                              ; CODE XREF: _main+33A↓j
                call    readKeyUpper    ; wait for a keypress (_bios_keybrd(0)) and return it folded to upper case.
                mov     [bp+var_76], al
                cmp     al, 59h ; 'Y'
                jz      short loc_1034C
                cmp     al, 4Eh ; 'N'
                jz      short loc_1034C
                cmp     al, 1Bh
                jnz     short loc_1033A

loc_1034C:                              ; CODE XREF: _main+332↑j
                                        ; _main+336↑j
                mov     ax, 0Ah
                push    ax
                mov     ax, 4Fh ; 'O'
                push    ax
                mov     ax, 9
                push    ax
                sub     ax, ax
                push    ax
                call    clearRegion     ; blank a rectangular region (int 10h AH=06h) -- args col1,row1,col2,row2.
                add     sp, 8
                mov     ax, 9
                push    ax
                sub     ax, ax
                push    ax
                call    gotoXY          ; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
                add     sp, 4
                cmp     [bp+var_76], 59h ; 'Y'
                jnz     short loc_103AC
                mov     ax, 487h
                push    ax              ; char *
                call    _printf
                add     sp, 2

loc_1037E:                              ; CODE XREF: _main+376↓j
                                        ; _main+37A↓j
                call    readKeyUpper    ; wait for a keypress (_bios_keybrd(0)) and return it folded to upper case.
                mov     [bp+var_76], al
                cmp     al, 40h ; '@'
                jb      short loc_1037E
                cmp     al, 5Ah ; 'Z'
                ja      short loc_1037E
                mov     [bp+var_7A], al
                mov     ax, 4C6h
                push    ax              ; char *
                call    _printf
                add     sp, 2

loc_10399:                              ; CODE XREF: _main+391↓j
                                        ; _main+395↓j
                call    readKeyUpper    ; wait for a keypress (_bios_keybrd(0)) and return it folded to upper case.
                mov     [bp+var_76], al
                cmp     al, 40h ; '@'
                jb      short loc_10399
                cmp     al, 5Ah ; 'Z'
                ja      short loc_10399
                mov     [bp+var_74], al
                jmp     short loc_103CA
; ---------------------------------------------------------------------------

loc_103AC:                              ; CODE XREF: _main+362↑j
                mov     ax, 505h
                push    ax              ; char *
                call    _printf
                add     sp, 2

loc_103B6:                              ; CODE XREF: _main+3AE↓j
                                        ; _main+3B2↓j
                call    readKeyUpper    ; wait for a keypress (_bios_keybrd(0)) and return it folded to upper case.
                mov     [bp+var_76], al
                cmp     al, 40h ; '@'
                jb      short loc_103B6
                cmp     al, 5Ah ; 'Z'
                ja      short loc_103B6
                mov     [bp+var_74], al
                mov     [bp+var_7A], al

loc_103CA:                              ; CODE XREF: _main+39A↑j
                mov     ax, 0Ch
                push    ax
                mov     ax, 4Fh ; 'O'
                push    ax
                mov     ax, 6
                push    ax
                sub     ax, ax
                push    ax
                call    clearRegion     ; blank a rectangular region (int 10h AH=06h) -- args col1,row1,col2,row2.
                add     sp, 8
                mov     ax, 6
                push    ax
                sub     ax, ax
                push    ax
                call    gotoXY          ; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
                add     sp, 4
                mov     ax, 539h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     al, [bp+var_74]
                cmp     [bp+var_7A], al
                jnz     short loc_10410
                mov     al, [bp+var_7A]
                sub     ah, ah
                push    ax
                mov     ax, 56Ah
                push    ax              ; char *
                call    _printf
                add     sp, 4
                jmp     short loc_10424
; ---------------------------------------------------------------------------

loc_10410:                              ; CODE XREF: _main+3EC↑j
                mov     al, [bp+var_74]
                sub     ah, ah
                push    ax
                mov     al, [bp+var_7A]
                push    ax
                mov     ax, 575h
                push    ax              ; char *
                call    _printf
                add     sp, 6

loc_10424:                              ; CODE XREF: _main+3FE↑j
                mov     ax, 5A5h
                push    ax              ; char *
                call    _printf
                add     sp, 2

loc_1042E:                              ; CODE XREF: _main+42E↓j
                call    readKeyUpper    ; wait for a keypress (_bios_keybrd(0)) and return it folded to upper case.
                mov     [bp+var_76], al
                cmp     al, 59h ; 'Y'
                jz      short loc_10440
                cmp     al, 4Eh ; 'N'
                jz      short loc_10440
                cmp     al, 1Bh
                jnz     short loc_1042E

loc_10440:                              ; CODE XREF: _main+426↑j
                                        ; _main+42A↑j
                cmp     [bp+var_76], 59h ; 'Y'
                jz      short loc_10449
                jmp     loc_104E6
; ---------------------------------------------------------------------------

loc_10449:                              ; CODE XREF: _main+434↑j
                mov     al, [bp+var_7A]
                mov     [bp+var_72], al
                mov     al, [bp+var_74]
                mov     [bp+var_71], al
                mov     al, [bp+var_78]
                mov     [bp+var_70], al
                mov     [bp+var_6F], 0
                lea     ax, [bp+var_22]
                push    ax              ; unsigned int
                mov     ax, 8002h
                push    ax
                lea     ax, [bp+var_20]
                push    ax              ; char *
                call    __dos_open
                add     sp, 6
                mov     ax, 9B0h
                push    ax              ; unsigned int *
                mov     ax, 3
                push    ax              ; unsigned int
                lea     ax, [bp+var_72]
                push    ss
                push    ax              ; void far *
                push    [bp+var_22]     ; int
                call    __dos_write
                add     sp, 0Ah
                or      ax, ax
                jz      short loc_104BC
                call    clearScreen     ; blank the whole 80x25 screen (int 10h AH=06h scroll-up, full window, attribute 7).
                sub     ax, ax
                push    ax
                push    ax
                call    gotoXY          ; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
                add     sp, 4
                mov     ax, 1
                push    ax
                call    setTextColor    ; set the text attribute for subsequent printf output (int 10h AH=10h) -- arg!=0 selects the highlight colour (6/7), else normal (0x20).
                add     sp, 2
                mov     ax, 5D8h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 611h
                push    ax              ; char *
                call    _printf
                add     sp, 2
                mov     ax, 0FFFFh
                jmp     short loc_104F2
; ---------------------------------------------------------------------------
                align 2

loc_104BC:                              ; CODE XREF: _main+479↑j
                push    [bp+var_22]     ; int
                call    __dos_close
                add     sp, 2
                call    clearScreen     ; blank the whole 80x25 screen (int 10h AH=06h scroll-up, full window, attribute 7).
                sub     ax, ax
                push    ax
                push    ax
                call    gotoXY          ; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
                add     sp, 4
                mov     ax, 1
                push    ax
                call    setTextColor    ; set the text attribute for subsequent printf output (int 10h AH=10h) -- arg!=0 selects the highlight colour (6/7), else normal (0x20).
                add     sp, 2
                mov     ax, 642h
                push    ax              ; char *
                call    _printf
                jmp     short loc_104ED
; ---------------------------------------------------------------------------
                align 2

loc_104E6:                              ; CODE XREF: _main+2DB↑j
                                        ; _main+436↑j
                mov     ax, 1
                push    ax
                call    setTextColor    ; set the text attribute for subsequent printf output (int 10h AH=10h) -- arg!=0 selects the highlight colour (6/7), else normal (0x20).

loc_104ED:                              ; CODE XREF: _main+4D3↑j
                add     sp, 2
                sub     ax, ax

loc_104F2:                              ; CODE XREF: _main+4A9↑j
                push    ax              ; int
                call    _exit
_main           endp

; ---------------------------------------------------------------------------
                add     sp, 2
                pop     si
                pop     di
                mov     sp, bp
                pop     bp
                retn
; ---------------------------------------------------------------------------
                align 2

; =============== S U B R O U T I N E =======================================

; set the text attribute for subsequent printf output (int 10h AH=10h) -- arg!=0 selects the highlight colour (6/7), else normal (0x20).
; Attributes: bp-based frame

setTextColor    proc near               ; CODE XREF: _main+2B3↑p
                                        ; _main+48C↑p ...

var_4           = byte ptr -4
var_2           = byte ptr -2
arg_0           = byte ptr  4

                push    bp
                mov     bp, sp
                sub     sp, 4
                cmp     [bp+arg_0], 0
                jz      short loc_10516
                mov     [bp+var_4], 6
                mov     [bp+var_2], 7
                jmp     short loc_1051A
; ---------------------------------------------------------------------------

loc_10516:                              ; CODE XREF: setTextColor+A↑j
                mov     [bp+var_4], 20h ; ' '

loc_1051A:                              ; CODE XREF: setTextColor+14↑j
                mov     byte ptr colorRegs, 1 ; static `union REGS` that setTextColor fills (AL / BL / BH bytes at 12B2B / 12B2E / 12B2F) and passes twice to _int86(0x10) to set the text colour.
                mov     al, [bp+var_4]
                mov     byte_12B2F, al
                mov     al, [bp+var_2]
                mov     byte_12B2E, al
                mov     ax, 0DBAh
                push    ax
                push    ax              ; union REGS *
                mov     ax, 10h
                push    ax              ; int
                call    _int86
                mov     sp, bp
                pop     bp
                retn
setTextColor    endp

; ---------------------------------------------------------------------------
                align 2

; =============== S U B R O U T I N E =======================================

; wait for a keypress (_bios_keybrd(0)) and return it folded to upper case.
; Attributes: bp-based frame

readKeyUpper    proc near               ; CODE XREF: _main:loc_102D3↑p
                                        ; _main:loc_1033A↑p ...

var_6           = word ptr -6
var_4           = byte ptr -4
var_2           = byte ptr -2

                push    bp
                mov     bp, sp
                sub     sp, 6
                sub     ax, ax
                push    ax              ; unsigned int
                call    __bios_keybrd
                add     sp, 2
                mov     [bp+var_6], ax
                mov     al, byte ptr [bp+var_6+1]
                mov     [bp+var_2], al
                mov     al, byte ptr [bp+var_6]
                mov     [bp+var_4], al
                cmp     al, 60h ; '`'
                jbe     short loc_10562
                sub     [bp+var_4], 20h ; ' '

loc_10562:                              ; CODE XREF: readKeyUpper+20↑j
                mov     al, [bp+var_4]
                sub     ah, ah
                mov     sp, bp
                pop     bp
                retn
readKeyUpper    endp

; ---------------------------------------------------------------------------
                align 2
byte_1056C      db 0                    ; DATA XREF: getVideoPage+6↓w
                                        ; gotoXY+5↓r

; =============== S U B R O U T I N E =======================================

; int 10h AH=0Fh -- cache the active display page (BH) in cs:byte_1056C.

getVideoPage    proc near               ; CODE XREF: _main+135↑p
                                        ; _main+19E↑p
                push    ax
                push    bx
                mov     ah, 0Fh
                int     10h             ; - VIDEO - GET CURRENT VIDEO MODE
                                        ; Return: AH = number of columns on screen
                                        ; AL = current video mode
                                        ; BH = current active display page
                mov     cs:byte_1056C, bh
                pop     bx
                pop     ax
                retn
getVideoPage    endp


; =============== S U B R O U T I N E =======================================

; blank the whole 80x25 screen (int 10h AH=06h scroll-up, full window, attribute 7).

clearScreen     proc near               ; CODE XREF: _main+138↑p
                                        ; _main+1A1↑p ...
                push    ax
                push    bx
                push    cx
                push    dx
                push    bp
                xor     al, al
                xor     cx, cx
                mov     dh, 18h
                mov     dl, 4Fh ; 'O'
                mov     bh, 7
                mov     ah, 6
                int     10h             ; - VIDEO - SCROLL PAGE UP
                                        ; AL = number of lines to scroll window (0 = blank whole window)
                                        ; BH = attributes to be used on blanked lines
                                        ; CH,CL = row,column of upper left corner of window to scroll
                                        ; DH,DL = row,column of lower right corner of window
                pop     bp
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                retn
clearScreen     endp


; =============== S U B R O U T I N E =======================================

; position the cursor (int 10h AH=02h) at (col=arg0, row=arg1) on the cached page.
; Attributes: bp-based frame

gotoXY          proc near               ; CODE XREF: _main+13F↑p
                                        ; _main+1A8↑p ...

arg_0           = byte ptr  4
arg_2           = byte ptr  6

                push    bp
                mov     bp, sp
                push    ax
                push    bx
                mov     bh, cs:byte_1056C
                mov     dl, [bp+arg_0]
                mov     dh, [bp+arg_2]
                mov     ah, 2
                int     10h             ; - VIDEO - SET CURSOR POSITION
                                        ; DH,DL = row, column (0,0 = upper left)
                                        ; BH = page number
                pop     bx
                pop     ax
                pop     bp
                retn
gotoXY          endp


; =============== S U B R O U T I N E =======================================

; blank a rectangular region (int 10h AH=06h) -- args col1,row1,col2,row2.
; Attributes: bp-based frame

clearRegion     proc near               ; CODE XREF: _main+2ED↑p
                                        ; _main+34B↑p ...

arg_0           = byte ptr  4
arg_2           = byte ptr  6
arg_4           = byte ptr  8
arg_6           = byte ptr  0Ah

                push    bp
                mov     bp, sp
                push    ax
                push    bx
                push    cx
                push    dx
                xor     al, al
                mov     ch, [bp+arg_2]
                mov     cl, [bp+arg_0]
                mov     dh, [bp+arg_6]
                mov     dl, [bp+arg_4]
                mov     bh, 7
                mov     ah, 6
                int     10h             ; - VIDEO - SCROLL PAGE UP
                                        ; AL = number of lines to scroll window (0 = blank whole window)
                                        ; BH = attributes to be used on blanked lines
                                        ; CH,CL = row,column of upper left corner of window to scroll
                                        ; DH,DL = row,column of lower right corner of window
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                pop     bp
                retn
clearRegion     endp

; ---------------------------------------------------------------------------
                align 2
                assume ss:seg002, ds:nothing
; [000000B2 BYTES: COLLAPSED FUNCTION start. PRESS NUMPAD+ TO EXPAND]
; [000000C4 BYTES: COLLAPSED FUNCTION __cinit. PRESS NUMPAD+ TO EXPAND]
; [00000017 BYTES: COLLAPSED FUNCTION _exit. PRESS NUMPAD+ TO EXPAND]
; [00000045 BYTES: COLLAPSED FUNCTION __exit. PRESS NUMPAD+ TO EXPAND]
; [0000002D BYTES: COLLAPSED FUNCTION __ctermsub. PRESS NUMPAD+ TO EXPAND]
; [0000000F BYTES: COLLAPSED FUNCTION sub_107CD. PRESS NUMPAD+ TO EXPAND]
; [00000013 BYTES: COLLAPSED FUNCTION sub_107DC. PRESS NUMPAD+ TO EXPAND]
                align 2
; [00000020 BYTES: COLLAPSED FUNCTION __FF_MSGBANNER. PRESS NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION __fptrap. PRESS NUMPAD+ TO EXPAND]
; [00000016 BYTES: COLLAPSED FUNCTION __chkstk. PRESS NUMPAD+ TO EXPAND]
; [00000022 BYTES: COLLAPSED FUNCTION __nullcheck. PRESS NUMPAD+ TO EXPAND]
; [0000018E BYTES: COLLAPSED FUNCTION __setargv. PRESS NUMPAD+ TO EXPAND]
; [0000006E BYTES: COLLAPSED FUNCTION __setenvp. PRESS NUMPAD+ TO EXPAND]
; [0000002B BYTES: COLLAPSED FUNCTION __NMSG_TEXT. PRESS NUMPAD+ TO EXPAND]
; [00000029 BYTES: COLLAPSED FUNCTION __NMSG_WRITE. PRESS NUMPAD+ TO EXPAND]
; [00000042 BYTES: COLLAPSED FUNCTION __myalloc. PRESS NUMPAD+ TO EXPAND]
; ---------------------------------------------------------------------------

__dosret0:
                jb      short loc_10AF5
; [00000011 BYTES: COLLAPSED CHUNK OF FUNCTION __dos_close. PRESS NUMPAD+ TO EXPAND]
; ---------------------------------------------------------------------------
; [0000000D BYTES: COLLAPSED CHUNK OF FUNCTION _lseek. PRESS NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION __maperror. PRESS NUMPAD+ TO EXPAND]

; =============== S U B R O U T I N E =======================================


sub_10B06       proc near               ; CODE XREF: __dos_close-1237↑p
                                        ; _lseek:loc_10AF5↑p ...
                mov     byte ptr _doserrno, al ; raw DOS error code (low byte) saved on entry to _maperror before translation.
                or      ah, ah
                jnz     short loc_10B30
                cmp     byte ptr _osversion, 3 ; DOS version word (low byte = _osmajor). Set by __cinit; _maperror checks `>= 3` before using the extended errno mapping.
                jb      short loc_10B21
                cmp     al, 22h ; '"'
                jnb     short loc_10B25
                cmp     al, 20h ; ' '
                jb      short loc_10B21
                mov     al, 5
                jmp     short loc_10B27
; ---------------------------------------------------------------------------
                db 90h
; ---------------------------------------------------------------------------

loc_10B21:                              ; CODE XREF: sub_10B06+C↑j
                                        ; sub_10B06+14↑j
                cmp     al, 13h
                jbe     short loc_10B27

loc_10B25:                              ; CODE XREF: sub_10B06+10↑j
                mov     al, 13h

loc_10B27:                              ; CODE XREF: sub_10B06+18↑j
                                        ; sub_10B06+1D↑j
                mov     bx, 728h
                xlat

loc_10B2B:                              ; CODE XREF: sub_10B06+2C↓j
                cbw
                mov     _errno, ax      ; C `errno` -- sub_10B06 (_maperror) xlat's the raw DOS error code through the 0x728 table and stores it here.
                retn
; ---------------------------------------------------------------------------

loc_10B30:                              ; CODE XREF: sub_10B06+5↑j
                mov     al, ah
                jmp     short loc_10B2B
sub_10B06       endp

; [00000032 BYTES: COLLAPSED FUNCTION _flushall. PRESS NUMPAD+ TO EXPAND]
; [0000003C BYTES: COLLAPSED FUNCTION _printf. PRESS NUMPAD+ TO EXPAND]
; [00000155 BYTES: COLLAPSED FUNCTION __flsbuf. PRESS NUMPAD+ TO EXPAND]
                align 2
; [0000006C BYTES: COLLAPSED FUNCTION __getbuf. PRESS NUMPAD+ TO EXPAND]
; [00000084 BYTES: COLLAPSED FUNCTION __stbuf. PRESS NUMPAD+ TO EXPAND]
; [00000096 BYTES: COLLAPSED FUNCTION __ftbuf. PRESS NUMPAD+ TO EXPAND]
; [0000006E BYTES: COLLAPSED FUNCTION _fflush. PRESS NUMPAD+ TO EXPAND]
; [0000031D BYTES: COLLAPSED FUNCTION __output. PRESS NUMPAD+ TO EXPAND]
                align 2
; [00000135 BYTES: COLLAPSED FUNCTION iprint. PRESS NUMPAD+ TO EXPAND]
                align 2
; [000000E8 BYTES: COLLAPSED FUNCTION sprint. PRESS NUMPAD+ TO EXPAND]
; [00000057 BYTES: COLLAPSED FUNCTION fprint. PRESS NUMPAD+ TO EXPAND]
; ---------------------------------------------------------------------------
                add     sp, 0Ah
                cmp     byte ptr [bp-4], 0
                jz      short loc_1149A
                cmp     word_126EC, 0
                jnz     short loc_1149A
                push    word_1270A
                call    off_125F4
; ---------------------------------------------------------------------------
                add     sp, 2

loc_1149A:                              ; CODE XREF: seg000:1486↑j
                                        ; seg000:148D↑j
                cmp     word_126EC, 0
                jz      short loc_114B3
                cmp     word_12706, 0
                jnz     short loc_114B3
                push    word_1270A
                call    off_125F8
; ---------------------------------------------------------------------------
                add     sp, 2

loc_114B3:                              ; CODE XREF: seg000:149F↑j
                                        ; seg000:14A6↑j
                add     word_126FA, 8
                mov     word_1270E, 0
                mov     ax, word_126F6
                or      ax, word_126FC
                jz      short loc_114DA
                push    word ptr [bp-2]
                call    off_125FA
; ---------------------------------------------------------------------------
                add     sp, 2
                or      ax, ax
                jz      short loc_114DA
                mov     ax, 1
                jmp     short loc_114DC
; ---------------------------------------------------------------------------

loc_114DA:                              ; CODE XREF: seg000:14C5↑j
                                        ; seg000:14D3↑j
                sub     ax, ax

loc_114DC:                              ; CODE XREF: seg000:14D8↑j
                push    ax
                call    _out
                mov     sp, bp
                pop     bp
                retn
; [0000003D BYTES: COLLAPSED FUNCTION _outc. PRESS NUMPAD+ TO EXPAND]
                align 2
; [0000005E BYTES: COLLAPSED FUNCTION putpad. PRESS NUMPAD+ TO EXPAND]
; [00000068 BYTES: COLLAPSED FUNCTION putbuf. PRESS NUMPAD+ TO EXPAND]
; [000000E2 BYTES: COLLAPSED FUNCTION _out. PRESS NUMPAD+ TO EXPAND]
; [00000017 BYTES: COLLAPSED FUNCTION putsign. PRESS NUMPAD+ TO EXPAND]
                align 2
; [00000029 BYTES: COLLAPSED FUNCTION putprefix. PRESS NUMPAD+ TO EXPAND]
                align 2
; [0000007F BYTES: COLLAPSED FUNCTION getnum. PRESS NUMPAD+ TO EXPAND]
                align 2
; [00000027 BYTES: COLLAPSED FUNCTION flagchar. PRESS NUMPAD+ TO EXPAND]
                align 2
; [0000007A BYTES: COLLAPSED FUNCTION _lseek. PRESS NUMPAD+ TO EXPAND]
; [000000A6 BYTES: COLLAPSED FUNCTION _write. PRESS NUMPAD+ TO EXPAND]
; [0000004E BYTES: COLLAPSED FUNCTION sub_118D4. PRESS NUMPAD+ TO EXPAND]
; ---------------------------------------------------------------------------
; [00000034 BYTES: COLLAPSED CHUNK OF FUNCTION _write. PRESS NUMPAD+ TO EXPAND]
; [00000012 BYTES: COLLAPSED FUNCTION _stackavail. PRESS NUMPAD+ TO EXPAND]
; [00000012 BYTES: COLLAPSED FUNCTION unknown_libname_1. PRESS NUMPAD+ TO EXPAND]
; [00000046 BYTES: COLLAPSED FUNCTION unknown_libname_2. PRESS NUMPAD+ TO EXPAND]
; ---------------------------------------------------------------------------
; [00000003 BYTES: COLLAPSED CHUNK OF FUNCTION __amalloc. PRESS NUMPAD+ TO EXPAND]
; [000000E3 BYTES: COLLAPSED FUNCTION __amalloc. PRESS NUMPAD+ TO EXPAND]
; [0000003A BYTES: COLLAPSED FUNCTION __amexpand. PRESS NUMPAD+ TO EXPAND]
; [00000022 BYTES: COLLAPSED FUNCTION __amlink. PRESS NUMPAD+ TO EXPAND]
; [0000001F BYTES: COLLAPSED FUNCTION __amallocbrk. PRESS NUMPAD+ TO EXPAND]
                align 2
; [0000006E BYTES: COLLAPSED FUNCTION _brkctl. PRESS NUMPAD+ TO EXPAND]
; [00000056 BYTES: COLLAPSED FUNCTION sub_11B90. PRESS NUMPAD+ TO EXPAND]
; [0000001B BYTES: COLLAPSED FUNCTION _strlen. PRESS NUMPAD+ TO EXPAND]
                align 2
; [0000000A BYTES: COLLAPSED FUNCTION _ultoa. PRESS NUMPAD+ TO EXPAND]
; [00000023 BYTES: COLLAPSED FUNCTION _isatty. PRESS NUMPAD+ TO EXPAND]
                align 2
; [0000007E BYTES: COLLAPSED FUNCTION _int86. PRESS NUMPAD+ TO EXPAND]
; ---------------------------------------------------------------------------
; [0000005F BYTES: COLLAPSED CHUNK OF FUNCTION _ultoa. PRESS NUMPAD+ TO EXPAND]
                align 2
; [00000014 BYTES: COLLAPSED FUNCTION __bios_keybrd. PRESS NUMPAD+ TO EXPAND]
; [0000000D BYTES: COLLAPSED FUNCTION __dos_close. PRESS NUMPAD+ TO EXPAND]
                align 2
; [00000017 BYTES: COLLAPSED FUNCTION __dos_open. PRESS NUMPAD+ TO EXPAND]
                align 2
; [00000007 BYTES: COLLAPSED FUNCTION __dos_read. PRESS NUMPAD+ TO EXPAND]
; [0000001C BYTES: COLLAPSED FUNCTION __dos_write. PRESS NUMPAD+ TO EXPAND]
                align 8
seg000          ends

; ===========================================================================

; Segment type: Pure data
dseg            segment para public 'DATA' use16
                assume cs:dseg
                db 2 dup(0)
word_11D72      dw 0                    ; DATA XREF: start+50↑w
                align 8
                db 4Dh, 53h, 20h, 52h, 75h, 6Eh, 2Dh, 54h, 69h, 6Dh, 65h
                db 20h, 4Ch, 69h, 62h, 72h, 61h, 72h, 79h, 20h, 2Dh, 20h
                db 43h, 6Fh, 70h, 79h, 72h, 69h, 67h, 68h, 74h, 20h, 28h
                db 63h, 29h, 20h
word_11D9C      dw 3931h                ; DATA XREF: __setenvp+11↑r
                db 2 dup(38h), 2Ch, 20h, 4Dh, 69h, 63h, 72h, 6Fh, 73h
                db 6Fh, 66h, 74h, 20h, 43h, 6Fh, 72h, 70h, 11h, 0, 44h
                db 52h, 43h, 4Fh, 4Eh, 46h, 49h, 47h, 2Eh, 44h, 41h, 54h
                db 0
aTheConfigurati db 'The configuration file could not be found!',0Ah
                db 0Ah,0
aRestartConfigu db 'Restart CONFIGUR.EXE from Disk 1 or from the LEGACY directory',0Ah
                db 0
aOnYourHardDisk db 'on your hard disk.',0Ah,0
                db 0Bh dup(20h), 0DAh, 38h dup(0C4h), 0BFh, 0Ah, 0, 0Bh dup(20h)
                db 0B3h, 0Ah dup(20h), 4Ch, 65h, 67h, 61h, 63h, 79h, 20h
                db 6Fh, 66h, 20h, 74h, 68h, 65h, 20h, 41h, 6Eh, 63h, 69h
                db 65h, 6Eh, 74h, 73h, 20h, 43h, 6Fh, 6Eh, 66h, 69h, 67h
                db 75h, 72h, 61h, 74h, 69h, 6Fh, 6Eh, 0Ah dup(20h), 0B3h
                db 0Ah, 0, 0Bh dup(20h), 0B3h, 6 dup(20h), 28h, 63h, 29h
                db 20h, 31h, 39h, 38h, 39h, 20h, 45h, 6Ch, 65h, 63h, 74h
                db 72h, 6Fh, 6Eh, 69h, 63h, 20h, 41h, 72h, 74h, 73h, 20h
                db 41h, 2 dup(6Ch), 20h, 52h, 69h, 67h, 68h, 74h, 73h
                db 20h, 52h, 65h, 73h, 65h, 72h, 76h, 65h, 64h, 6 dup(20h)
                db 0B3h, 0Ah, 0, 0Bh dup(20h), 0C0h, 38h dup(0C4h), 0D9h
                db 3 dup(0Ah), 0
aLegacyOfTheAnc db 'Legacy of the Ancients is currently configured for',0Ah,0
aAHighDensityFl db 'a High Density floppy or Hard Disk.',0Ah
                db 0Ah,0
aIfYouWishToRun db 'If you wish to run Legacy of the Ancients from 360K',0Ah,0
aOr720kFloppyDi db 'or 720K floppy disks, please re-install.',0Ah,0
aLegacyOfTheAnc_0 db 'Legacy of the Ancients',27h,' current configuration is',0Ah,0
aFour360k525Flo db 'four 360K 5.25" floppy disks using ',0
aDriveC         db 'drive %c:',0Ah,0
aDrivesCAndC    db 'drives %c: and %c:',0Ah,0
aLegacyOfTheAnc_1 db 'Legacy of the Ancients',27h,' current configuration is',0Ah,0
aTwo720k35Flopp db 'two 720K 3.5" floppy disks using ',0
aDriveC_0       db 'drive %c:',0Ah,0
aDrivesCAndC_0  db 'drives %c: and %c:',0Ah,0
aTheConfigurati_0 db 'The configuration file is corrupted!',0Ah
                db 0Ah,0
aPleaseReInstal db 'Please re-install Legacy of the Ancients',0Ah,0
aWouldYouLikeTo db 0Ah
                db 'Would you like to change this configuration (Y/N)?',0Ah,0
aWouldYouLikeLe db 'Would you like Legacy of the Ancients to utilize ',0Ah,0
aTwo525Drives   db 'two 5.25" drives ',0
aTwo35Drives    db 'two 3.5" drives ',0
aToReduceDiskSw db 'to reduce disk swaps (Y/N)?',0Ah,0
aPleaseEnterThe db 'Please enter the letter of the drive to use for Disk 1 (A-Z)?',0Ah
                db 0
aPleaseEnterThe_0 db 'Please enter the letter of the drive to use for Disk 2 (A-Z)?',0Ah
                db 0
aPleaseEnterThe_1 db 'Please enter the letter of the drive to use (A-Z)?',0Ah,0
aLegacyOfTheAnc_2 db 'Legacy of the Ancients is now configured to use ',0
aDriveC_1       db 'drive %c:',0Ah,0
aDriveCForDisk1 db 0Ah
                db 'Drive %c: for Disk 1 and Drive %c: for Disk 2',0Ah,0
aWouldYouLikeTo_0 db 0Ah
                db 'Would you like to save this configuration (Y/N)?',0Ah,0
aAnErrorHasOccu db 'An error has occured writing the Legacy of the Ancients',0Ah,0
aConfigurationF db 'Configuration file. Please restart CONFIGUR.EXE',0Ah,0
aLegacyOfTheAnc_3 db 'Legacy of the Ancients Configuration has been updated.',0Ah,0
word_123EA      dw 0                    ; DATA XREF: start+4A↑w
                                        ; __myalloc+8↑r ...
word_123EC      dw 0                    ; DATA XREF: start+3E↑w
off_123EE       dw offset __exit        ; DATA XREF: start+9C↑w
                                        ; start+AE↑r
word_123F0      dw 0                    ; DATA XREF: start+39↑w
                                        ; __myalloc+2↑r ...
                dw seg dseg
                db 4Ch dup(0)
word_12440      dw 680h                 ; DATA XREF: _brkctl:loc_11B41↑r
                                        ; _brkctl+61↑w
aCFileInfo      db ';C_FILE_INFO',0
dword_1244F     dd 0                    ; DATA XREF: __cinit+C↑w
                                        ; __ctermsub+E↑r ...
                db 8 dup(0)
; volatile int errno
_errno          dw 0                    ; DATA XREF: sub_10B06+26↑w
                                        ; C `errno` -- sub_10B06 (_maperror) xlat's the raw DOS error code through the 0x728 table and stores it here.
                db 4 dup(0)
_savedDS        dw 0                    ; DATA XREF: start+5E↑w
                                        ; __cinit+26↑r ...
                                        ; the DGROUP segment, stashed by `start` (`mov ss:[12461h], ds`) and reloaded into DS/ES by __setargv / __setenvp / __myalloc / __cinit.
_osversion      dw 0                    ; DATA XREF: __cinit+4↑w
                                        ; __setargv+7↑r ...
                                        ; DOS version word (low byte = _osmajor). Set by __cinit; _maperror checks `>= 3` before using the extended errno mapping.
                align 2
_doserrno       dw 0                    ; DATA XREF: sub_10B06↑w
                                        ; raw DOS error code (low byte) saved on entry to _maperror before translation.
_nfile          dw 14h                  ; DATA XREF: _lseek+9↑r
                                        ; _write+9↑r ...
                                        ; size of the file-handle table -- _lseek / _write / _isatty bounds-check the fd against it.
                db 3 dup(81h), 2 dup(1), 0Fh dup(0)
; int argc
argc            dw 0                    ; DATA XREF: start+89↑r
                                        ; __setargv+BE↑w
; char **argv
argv            dw 0                    ; DATA XREF: start+85↑r
                                        ; __setargv+D0↑w
word_12482      dw 0                    ; DATA XREF: start+81↑r
                                        ; __setenvp+44↑w
word_12484      dw 718h                 ; DATA XREF: __setargv+29↑w
                                        ; __setargv+DE↑r
seg_12486       dw seg dseg             ; DATA XREF: __setargv+16↑w
                db 43h, 3 dup(0)
byte_1248C      db 0                    ; DATA XREF: __ctermsub+18↑r
byte_1248D      db 0                    ; DATA XREF: __ctermsub+20↑r
dword_1248E     dd 0                    ; DATA XREF: __ctermsub+23↑r
word_12492      dw 0                    ; DATA XREF: __FF_MSGBANNER+A↑r
                                        ; __FF_MSGBANNER+11↑r
_STKHQQ         dw 10D0h                ; DATA XREF: __chkstk+7↑r
                                        ; _stackavail+1↑r
                                        ; Microsoft C stack-overflow limit -- __chkstk and _stackavail compare the prospective SP against it.
word_12496      dw 0                    ; DATA XREF: __setargv↑w
                                        ; __setargv+18A↑r
                db 0, 16h, 2 dup(2), 18h, 0Dh, 9, 3 dup(0Ch), 7, 8, 2 dup(16h)
                db 0FFh, 12h, 0Dh, 12h, 2, 0FFh
word_124AC      dw 0                    ; DATA XREF: __flsbuf+90↑w
                                        ; __stbuf+A↑w
                db 0BAh, 0Bh, 2 dup(0), 0BAh, 0Bh, 1, 7 dup(0), 2, 1, 6 dup(0)
                db 2 dup(2), 6 dup(0), 84h, 3, 6 dup(0), 2, 4, 78h dup(0)
                db 1, 2 dup(0), 2, 74h dup(0)
word_125C6      dw 7D6h                 ; DATA XREF: _flushall:loc_10B58↑r
aNull           db '(null)',0
aNull_0         db '(null)',0
                db '+- #',0
                align 2
word_125DC      dw 0                    ; DATA XREF: unknown_libname_2+1F↑w
word_125DE      dw 0                    ; DATA XREF: unknown_libname_2+22↑w
                db 2 dup(0)
word_125E2      dw 0                    ; DATA XREF: unknown_libname_2+32↑w
                db 2 dup(0)
word_125E6      dw 0                    ; DATA XREF: __amalloc+A2↑r
                db 2 dup(0)
word_125EA      dw 0                    ; DATA XREF: __amalloc+4F↑w
                                        ; __amalloc+D6↑w
word_125EC      dw 2000h                ; DATA XREF: __amexpand:loc_11AB6↑r
                align 4
byte_125F0      db 0                    ; DATA XREF: __amalloc:loc_11A1B↑w
                                        ; __amalloc:loc_11A56↑w
                align 2
off_125F2       dw offset __fptrap      ; DATA XREF: fprint+53↑r
off_125F4       dw offset __fptrap      ; DATA XREF: seg000:1493↑r
                db 10h, 8
off_125F8       dw offset __fptrap      ; DATA XREF: seg000:14AC↑r
off_125FA       dw offset __fptrap      ; DATA XREF: seg000:14CA↑r
                db 8 dup(0)
byte_12604      db 2 dup(0)             ; DATA XREF: __cinit+37↑r
                                        ; __cinit+4D↑r ...
word_12606      dw 0                    ; DATA XREF: __cinit+20↑r
                                        ; __ctermsub↑r
dword_12608     dd 0                    ; DATA XREF: __cinit+2F↑r
dword_1260C     dd 0                    ; DATA XREF: __cinit:loc_106C3↑r
a4Nmsg          db '4',0Bh,'<<NMSG>>',0
                align 2
aR6000StackOver db 'R6000',0Dh,0Ah
                db '- stack overflow',0Dh,0Ah,0
                db 3, 0
aR6003IntegerDi db 'R6003',0Dh,0Ah
                db '- integer divide by 0',0Dh,0Ah,0
                db 9,0
aR6009NotEnough db 'R6009',0Dh,0Ah
                db '- not enough space for environment',0Dh,0Ah,0
                db 0FCh, 0, 0Dh, 0Ah, 0, 0FFh, 0, 72h, 75h, 6Eh, 2Dh, 74h
                db 69h, 6Dh, 65h, 20h, 65h, 2 dup(72h), 6Fh, 72h, 20h
                db 0, 2, 0
aR6002FloatingP db 'R6002',0Dh,0Ah
                db '- floating point not loaded',0Dh,0Ah,0
                db 1, 0
aR6001NullPoint db 'R6001',0Dh,0Ah
                db '- null pointer assignment',0Dh,0Ah,0
                db 4 dup(0FFh)
word_126EC      dw 0FFFFh               ; DATA XREF: __output+55↑w
                                        ; __output:loc_10F80↑w ...
; FILE *word_126EE
word_126EE      dw 0FFFFh               ; DATA XREF: __output+1E↑w
                                        ; __output+2BB↑r ...
word_126F0      dw ?                    ; DATA XREF: __output+52↑w
                                        ; __output:loc_11098↑w ...
word_126F2      dw ?                    ; DATA XREF: __output+43↑w
                                        ; __output:loc_11046↑w ...
word_126F4      dw ?                    ; DATA XREF: __output+49↑w
                                        ; __output+111↑w ...
word_126F6      dw ?                    ; DATA XREF: __output+40↑w
                                        ; __output+75↑w ...
word_126F8      dw ?                    ; DATA XREF: __output+58↑w
                                        ; __output+9F↑w ...
word_126FA      dw ?                    ; DATA XREF: __output+18↑w
                                        ; __output:loc_11066↑r ...
word_126FC      dw ?                    ; DATA XREF: __output+4F↑w
                                        ; __output+79↑w ...
word_126FE      dw ?                    ; DATA XREF: __output+4C↑w
                                        ; __output+D7↑w ...
word_12700      dw ?                    ; DATA XREF: __output+46↑w
                                        ; __output:loc_1107A↑w ...
word_12702      dw ?                    ; DATA XREF: __output+27↑w
                                        ; __output+180↑r ...
word_12704      dw ?                    ; DATA XREF: __output+21↑w
                                        ; __output:loc_111E2↑r ...
word_12706      dw ?                    ; DATA XREF: __output:loc_10F24↑w
                                        ; __output+E9↑r ...
word_12708      dw ?                    ; DATA XREF: __output+1BB↑w
                                        ; __output:loc_110B0↑w ...
; char *word_1270A
word_1270A      dw ?                    ; DATA XREF: __output+12↑w
                                        ; iprint+79↑r ...
word_1270C      dw ?                    ; DATA XREF: __output+BF↑r
                                        ; __output+CA↑r ...
word_1270E      dw ?                    ; DATA XREF: iprint:loc_11280↑w
                                        ; seg000:14B8↑w ...
; int word_12710
word_12710      dw ?                    ; DATA XREF: __output+5B↑w
                                        ; __output+68↑w ...
                db 419h dup(?)
colorRegs       dw ?                    ; DATA XREF: setTextColor:loc_1051A↑w
                                        ; static `union REGS` that setTextColor fills (AL / BL / BH bytes at 12B2B / 12B2E / 12B2F) and passes twice to _int86(0x10) to set the text colour.
                db    ? ;
byte_12B2E      db ?                    ; DATA XREF: setTextColor+28↑w
byte_12B2F      db ?                    ; DATA XREF: setTextColor+22↑w
                db 210h dup(?)
dseg            ends

; ===========================================================================

; Segment type: Uninitialized
seg002          segment byte stack 'STACK' use16
                assume cs:seg002
                assume es:nothing, ss:nothing, ds:dseg, fs:nothing, gs:nothing
                db 800h dup(?)
seg002          ends


                end start
