//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
// |                      License info: 48-337F-7354-97                      |
// |                       Paul Gilbert, ScummVM Team                        |
// +-------------------------------------------------------------------------+
//
//
//      This file should be used in the following way:
//         - reload executable into IDA with using switch -c
//         - use File, Load IDC file and load this file.
//
//      NOTE: This file doesn't contain all information from the database.
//

#define UNLOADED_FILE   1
#include <idc.idc>

static main(void)
{
        // set 'loading idc file' mode
        set_inf_attr(INF_GENFLAGS, INFFL_LOADIDC|get_inf_attr(INF_GENFLAGS));
        GenInfo();            // various settings
        Segments();           // segmentation
        Enums();              // enumerations
        Structures();         // structure types
        ApplyStrucTInfos();   // structure type infos
        Patches();            // manual patches
        SegRegs();            // segment register values
        Bytes();              // individual bytes (code,data)
        Functions();          // function definitions
        // clear 'loading idc file' mode
        set_inf_attr(INF_GENFLAGS, ~INFFL_LOADIDC&get_inf_attr(INF_GENFLAGS));
}

//------------------------------------------------------------------------
// General information

static GenInfo(void) {

        delete_all_segments();    // purge database
	set_processor_type("metapc", SETPROC_USER);
	set_inf_attr(INF_COMPILER, 0);
	set_inf_attr(INF_STRLIT_BREAK, 0xA);
	set_flag(INF_CMTFLG, SCF_ALLCMT, 0);
	set_flag(INF_OUTFLAGS, OFLG_SHOW_VOID, 0);
	set_inf_attr(INF_XREFNUM, 0);
	set_flag(INF_OUTFLAGS, OFLG_SHOW_AUTO, 1);
	set_inf_attr(INF_INDENT, 0);
	set_inf_attr(INF_CMT_INDENT, 24);
	set_inf_attr(INF_MAXREF, 0x10);
}

//------------------------------------------------------------------------
// Information about segmentation

static Segments(void) {

	add_segm_ex(0X10100,0X108C5,0X1000,0,1,2,ADDSEG_NOSREG);
	SegRename(0X10100,"seg000");
	SegClass (0X10100,"CODE");
	SegDefReg(0x10100,"ds",0x1000);
	set_segm_type(0X10100,2);
	set_inf_attr(INF_LOW_OFF, 0x100);
	set_inf_attr(INF_HIGH_OFF, 0x1000);
}

//------------------------------------------------------------------------
// Information about enum types

static Enums(void) {
        auto id;
        begin_type_updating(UTP_ENUM);
        end_type_updating(UTP_ENUM);
}

//------------------------------------------------------------------------
// Information about type information for structure members

static ApplyStrucTInfos() {
}

//------------------------------------------------------------------------
// Information about structure types

static Structures(void) {
        auto id;
        begin_type_updating(UTP_STRUCT);
}

//------------------------------------------------------------------------
// Information about bytes

static Bytes_0(void) {
        auto x;
#define id x

	update_extra_cmt		(0X10100,	E_PREV + 0,	"; File Name   : C:\\games\\ULTIMA2\\ultima2.com");
	update_extra_cmt		(0X10100,	E_PREV + 1,	"; Format      : MS-DOS COM-file");
	update_extra_cmt		(0X10100,	E_PREV + 2,	"; Base Address: 1000h Range: 10100h-108C5h Loaded length: 7C5h");
	create_insn	(0X10100);
	set_name	(0X10100,	"start");
	create_strlit	(0X10103,	0X7);
	set_name	(0X10103,	"aU2Cfg");
	create_strlit	(0X1010A,	0XD);
	set_name	(0X1010A,	"aUltimaiiExe");
	create_byte	(0X10117);
	make_array	(0X10117,	0X23);
	create_byte	(0X1013A);
	make_array	(0X1013A,	0X4);
	create_byte	(0X1013E);
	make_array	(0X1013E,	0X4);
	create_byte	(0X10142);
	create_byte	(0X10143);
	make_array	(0X10143,	0X59);
	create_byte	(0X1019C);
	make_array	(0X1019C,	0X14);
	create_strlit	(0X101B0,	0X8B);
	set_name	(0X101B0,	"aErrorInitializ");
	create_byte	(0X1023B);
	make_array	(0X1023B,	0X7);
	create_byte	(0X10242);
	create_byte	(0X10243);
	make_array	(0X10243,	0XB);
	create_byte	(0X1024E);
	make_array	(0X1024E,	0X16);
	create_byte	(0X10264);
	make_array	(0X10264,	0X20);
	create_byte	(0X10284);
	make_array	(0X10284,	0X10);
	create_insn	(0X10294);
	set_name	(0X10294,	"start_0");
	set_cmt	(0X10299,	"DOS - 2+ - ADJUST MEMORY BLOCK SIZE (SETBLOCK)\nES = segment address of block to change\nBX = new size in paragraphs",	0);
	create_insn	(x=0X10299);
	op_hex		(x,	0);
	create_insn	(0X102D3);
	create_insn	(x=0X102D5);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X102D9);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X102E7);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(0X102F4);
	create_insn	(0X102F5);
	create_insn	(x=0X102F6);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(0X1031E);
	create_insn	(x=0X10322);
	op_hex		(x,	1);
	create_insn	(x=0X10326);
	op_hex		(x,	1);
	create_insn	(x=0X10347);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(0X1035C);
	create_insn	(x=0X1035D);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X10364);
	op_hex		(x,	1);
	create_insn	(x=0X10368);
	op_hex		(x,	1);
	create_insn	(x=0X10370);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X1037D);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X10383);
	op_hex		(x,	1);
	create_insn	(x=0X10387);
	op_hex		(x,	1);
	create_insn	(x=0X1038F);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(0X103A7);
	create_insn	(x=0X103A8);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X103AF);
	op_hex		(x,	1);
	create_insn	(x=0X103B3);
	op_hex		(x,	1);
	create_insn	(x=0X103BB);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X103C8);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X103CC);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X103D4);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X103DC);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X103E4);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	set_cmt	(0X103F1,	"DOS - 2+ - LOAD OR EXECUTE (EXEC)\nDS:DX -> ASCIZ filename\nES:BX -> parameter block\nAL = subfunc: load & execute program",	0);
	create_insn	(x=0X103F1);
	op_hex		(x,	0);
	create_insn	(x=0X103F5);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X103FD);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X10415);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X1041D);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X10435);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X1043D);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X10455);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(x=0X1045D);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X10475);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(0X1047D);
	create_insn	(x=0X1047F);
	op_hex		(x,	1);
	set_cmt	(0X10481,	"DOS - PRINT STRING\nDS:DX -> string terminated by \"$\"",	0);
	create_insn	(x=0X10481);
	op_hex		(x,	0);
	create_insn	(0X10486);
	create_insn	(0X1048D);
	create_insn	(x=0X10499);
	op_hex		(x,	1);
	set_cmt	(0X1049B,	"DOS - 2+ - QUIT WITH EXIT CODE (EXIT)\nAL = exit code",	0);
	create_insn	(x=0X1049B);
	op_hex		(x,	0);
	create_insn	(0X1049D);
	create_insn	(x=0X104B0);
	op_plain_offset	(x,	1,	0X10100);
	op_plain_offset	(x,	129,	0X10100);
	create_insn	(0X104BD);
	create_insn	(0X104C3);
	create_insn	(0X104DA);
	create_insn	(0X104F6);
	create_insn	(0X10508);
	create_insn	(x=0X10515);
	op_hex		(x,	1);
	create_insn	(0X1051F);
	create_insn	(x=0X10522);
	op_hex		(x,	1);
	create_insn	(0X1052D);
	set_cmt	(0X1053F,	"DOS - 2+ - OPEN DISK FILE WITH HANDLE\nDS:DX -> ASCIZ filename\nAL = access mode\n0 - read",	0);
	create_insn	(x=0X1053F);
	op_hex		(x,	0);
	create_insn	(x=0X1056B);
	op_hex		(x,	1);
	set_cmt	(0X1056D,	"DOS - 2+ - READ FROM FILE WITH HANDLE\nBX = file handle, CX = number of bytes to read\nDS:DX -> buffer",	0);
	create_insn	(x=0X1056D);
	op_hex		(x,	0);
	create_insn	(x=0X10574);
	op_hex		(x,	1);
	set_cmt	(0X10576,	"DOS - 2+ - CLOSE A FILE WITH HANDLE\nBX = file handle",	0);
	create_insn	(x=0X10576);
	op_hex		(x,	0);
	create_insn	(0X1057E);
	create_insn	(0X10588);
	set_cmt	(0X10594,	"DOS - 2+ - MOVE FILE READ/WRITE POINTER (LSEEK)\nAL = method: offset from present location",	0);
	create_insn	(x=0X10594);
	op_hex		(x,	0);
	set_cmt	(0X1059E,	"DOS - 2+ - MOVE FILE READ/WRITE POINTER (LSEEK)\nAL = method: offset from end of file",	0);
	create_insn	(x=0X1059E);
	op_hex		(x,	0);
	set_cmt	(0X105AE,	"DOS - 2+ - MOVE FILE READ/WRITE POINTER (LSEEK)\nAL = method: offset from beginning of file",	0);
	create_insn	(x=0X105AE);
	op_hex		(x,	0);
	create_insn	(0X105B5);
	create_insn	(0X105BD);
	create_insn	(x=0X105BF);
	op_hex		(x,	1);
	create_insn	(x=0X105C4);
	op_hex		(x,	1);
	create_insn	(x=0X105C9);
	op_hex		(x,	1);
	create_insn	(x=0X105CE);
	op_hex		(x,	1);
	create_insn	(x=0X105D5);
	op_hex		(x,	1);
	set_cmt	(0X105D7,	"DOS - 2+ - ALLOCATE MEMORY\nBX = number of 16-byte paragraphs desired",	0);
	create_insn	(x=0X105D7);
	op_hex		(x,	0);
	create_insn	(0X105E1);
	create_insn	(x=0X105E5);
	op_hex		(x,	1);
	set_cmt	(0X105E7,	"DOS - 2+ - FREE MEMORY\nES = segment address of area to be freed",	0);
	create_insn	(x=0X105E7);
	op_hex		(x,	0);
	create_insn	(0X105F0);
	create_byte	(0X105F5);
	make_array	(0X105F5,	0X10);
	create_byte	(0X10605);
	make_array	(0X10605,	0X4);
	create_byte	(0X10609);
	make_array	(0X10609,	0X4);
	create_byte	(0X1060D);
	make_array	(0X1060D,	0XA);
	create_byte	(0X10617);
	make_array	(0X10617,	0X25);
	create_byte	(0X1063C);
	make_array	(0X1063C,	0X12);
	create_byte	(0X1064E);
	make_array	(0X1064E,	0X3A);
	create_insn	(0X10688);
	set_cmt	(0X10695,	"reserved for user interrupt",	0);
	create_insn	(x=0X10695);
	op_hex		(x,	0);
	create_insn	(0X1069F);
	create_insn	(x=0X106AA);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X106B1);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X106BA);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X106C1);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(0X106CF);
	set_cmt	(0X106DE,	"reserved for user interrupt",	0);
	create_insn	(x=0X106DE);
	op_hex		(x,	0);
	create_insn	(0X106EA);
	create_insn	(x=0X106F0);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X106F9);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_byte	(0X10705);
	make_array	(0X10705,	0XAE);
	create_insn	(0X107B3);
	create_insn	(x=0X107BE);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X107C5);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X107CE);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X107D5);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X107DE);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X107E5);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(0X107F3);
	create_insn	(x=0X107F9);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X10802);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(x=0X1080B);
	op_plain_offset	(x,	1,	0X10000);
	op_plain_offset	(x,	129,	0X10000);
	create_insn	(0X10817);
	set_cmt	(0X10827,	"Timer 8253-5 (AT: 8254.2).",	0);
	create_insn	(x=0X10827);
	op_hex		(x,	0);
	create_insn	(0X10833);
	set_cmt	(0X1083D,	"Timer 8253-5 (AT: 8254.2).",	0);
	create_insn	(x=0X1083D);
	op_hex		(x,	0);
	set_cmt	(0X10841,	"Timer 8253-5 (AT: 8254.2).",	0);
	create_insn	(x=0X10841);
	op_hex		(x,	0);
	create_insn	(0X10848);
	create_insn	(0X10856);
	set_cmt	(0X1085F,	"CLOCK - GET TIME OF DAY\nReturn: CX:DX = clock count\nAL = 00h if clock was read or written (via AH=0,1) since the previous\nmidnight\nOtherwise, AL > 0",	0);
	create_insn	(x=0X1085F);
	op_hex		(x,	0);
	set_cmt	(0X10868,	"CLOCK - SET TIME OF DAY\nCX:DX = clock count\nReturn: time of day set",	0);
	create_insn	(x=0X10868);
	op_hex		(x,	0);
	create_insn	(0X10870);
	create_insn	(0X1088D);
	create_insn	(x=0X10891);
	op_hex		(x,	1);
	set_cmt	(0X10893,	"DOS - 2+ - GET INTERRUPT VECTOR\nAL = interrupt number\nReturn: ES:BX = value of interrupt vector",	0);
	create_insn	(x=0X10893);
	op_hex		(x,	0);
	create_insn	(0X108A3);
	create_insn	(x=0X108A9);
	op_hex		(x,	1);
	set_cmt	(0X108AB,	"DOS - SET INTERRUPT VECTOR\nAL = interrupt number\nDS:DX = new vector to be used for specified interrupt",	0);
	create_insn	(x=0X108AB);
	op_hex		(x,	0);
	create_insn	(0X108B0);
}

static Functions_0(void) {

	add_func    (0X10100,0X10103);
	set_func_flags(0X10100,0x14c1);
	add_func    (0X10294,0X102D3);
	set_func_flags(0X10294,0x1401);
	add_func    (0X102D3,0X102F5);
	set_func_flags(0X102D3,0x5400);
	set_frame_size(0X102D3, 0, 0, 0);
	add_func    (0X103A8,0X103C8);
	set_func_flags(0X103A8,0x5400);
	set_frame_size(0X103A8, 0, 0, 0);
	add_func    (0X103C8,0X103FD);
	set_func_flags(0X103C8,0x5400);
	set_frame_size(0X103C8, 0, 0, 0);
	add_func    (0X1043D,0X1045D);
	set_func_flags(0X1043D,0x5400);
	set_frame_size(0X1043D, 0, 0, 0);
	add_func    (0X1047D,0X10486);
	set_func_flags(0X1047D,0x5400);
	set_frame_size(0X1047D, 0, 0, 0);
	add_func    (0X10486,0X1048D);
	set_func_flags(0X10486,0x1401);
	add_func    (0X1048D,0X1049D);
	set_func_flags(0X1048D,0x1401);
	add_func    (0X1049D,0X104C3);
	set_func_flags(0X1049D,0x5400);
	set_frame_size(0X1049D, 0, 0, 0);
	add_func    (0X104C3,0X104DA);
	set_func_flags(0X104C3,0x5400);
	set_frame_size(0X104C3, 0, 0, 0);
	add_func    (0X104DA,0X104F6);
	set_func_flags(0X104DA,0x5400);
	set_frame_size(0X104DA, 0, 0, 0);
	add_func    (0X104F6,0X10508);
	set_func_flags(0X104F6,0x5400);
	set_frame_size(0X104F6, 0, 0, 0);
	add_func    (0X1052D,0X10588);
	set_func_flags(0X1052D,0x5400);
	set_frame_size(0X1052D, 0, 0, 0);
	add_func    (0X10588,0X105BD);
	set_func_flags(0X10588,0x5400);
	set_frame_size(0X10588, 0, 0, 0);
	add_func    (0X105BD,0X105E1);
	set_func_flags(0X105BD,0x5400);
	set_frame_size(0X105BD, 0, 0, 0);
	add_func    (0X105E1,0X105F5);
	set_func_flags(0X105E1,0x5400);
	set_frame_size(0X105E1, 0, 0, 0);
	add_func    (0X10688,0X1069F);
	set_func_flags(0X10688,0x5400);
	set_frame_size(0X10688, 0, 0, 0);
	add_func    (0X1069F,0X106CF);
	set_func_flags(0X1069F,0x5400);
	set_frame_size(0X1069F, 0, 0, 0);
	add_func    (0X106CF,0X106EA);
	set_func_flags(0X106CF,0x5400);
	set_frame_size(0X106CF, 0, 0, 0);
	add_func    (0X106EA,0X10705);
	set_func_flags(0X106EA,0x5400);
	set_frame_size(0X106EA, 0, 0, 0);
	add_func    (0X107B3,0X107F3);
	set_func_flags(0X107B3,0x5400);
	set_frame_size(0X107B3, 0, 0, 0);
	add_func    (0X107F3,0X10817);
	set_func_flags(0X107F3,0x5400);
	set_frame_size(0X107F3, 0, 0, 0);
	add_func    (0X1088D,0X108A3);
	set_func_flags(0X1088D,0x5400);
	set_frame_size(0X1088D, 0X6, 0, 0);
	add_func    (0X108A3,0X108B0);
	set_func_flags(0X108A3,0x5400);
	set_frame_size(0X108A3, 0X2, 0, 0);
	add_func    (0X108B0,0X108C5);
	set_func_flags(0X108B0,0x5400);
	set_frame_size(0X108B0, 0X4, 0, 0);
}

//------------------------------------------------------------------------
// Information about functions

static Functions(void) {

	Functions_0();
}

//------------------------------------------------------------------------
// Information about segment registers

static SegRegs(void) {
	split_sreg_range(0X10100,"es",BADSEL,3);
	split_sreg_range(0X102AB,"es",0X1010,3);
	split_sreg_range(0X102CA,"es",0X1010,3);
	split_sreg_range(0X104D4,"es",BADSEL,3);
	split_sreg_range(0X104F0,"es",BADSEL,3);
	split_sreg_range(0X10535,"es",0X1000,3);
	split_sreg_range(0X10563,"es",BADSEL,3);
	split_sreg_range(0X10582,"es",BADSEL,3);
	split_sreg_range(0X105E5,"es",BADSEL,3);
	split_sreg_range(0X105F3,"es",BADSEL,3);
	split_sreg_range(0X106A8,"es",0X1000,3);
	split_sreg_range(0X106CA,"es",BADSEL,3);
	split_sreg_range(0X107BC,"es",0X1000,3);
	split_sreg_range(0X107EE,"es",BADSEL,3);
	split_sreg_range(0X1084F,"es",0X1000,3);
	split_sreg_range(0X10854,"es",BADSEL,3);
	split_sreg_range(0X1089F,"es",BADSEL,3);
	split_sreg_range(0X108BD,"es",BADSEL,3);
	split_sreg_range(0X108C2,"es",BADSEL,3);
	split_sreg_range(0X10100,"ss",BADSEL,3);
	split_sreg_range(0X1029F,"ss",0X1000,3);
	split_sreg_range(0X102C3,"ss",0X1000,3);
	split_sreg_range(0X10100,"ds",0X1000,3);
	split_sreg_range(0X102A9,"ds",0X1010,3);
	split_sreg_range(0X102C8,"ds",0X1010,3);
	split_sreg_range(0X102FE,"ds",0X1000,3);
	split_sreg_range(0X1031C,"ds",0X1000,3);
	split_sreg_range(0X1031F,"ds",0X1000,3);
	split_sreg_range(0X10569,"ds",0X1000,3);
	split_sreg_range(0X10570,"ds",0X1000,3);
	split_sreg_range(0X108A7,"ds",0X1000,3);
	split_sreg_range(0X108AE,"ds",0X1000,3);
	split_sreg_range(0X10100,"fs",BADSEL,3);
	split_sreg_range(0X10100,"gs",BADSEL,3);
}

//------------------------------------------------------------------------
// Information about all patched bytes:

static Patches(void) {
}

//------------------------------------------------------------------------
// Call all byte feature functions:

static Bytes(void) {
	Bytes_0();
        end_type_updating(UTP_STRUCT);
}

// End of file.
