/* Generated from docs/spells.md; spell names come from the manual. */
#include "mm2_spells.h"

const char *const MM2_SPELL_NAMES[96] = {
	"Awaken",
	"Detect Magic",
	"Energy Blast",
	"Flame Arrow",
	"Light",
	"Location",
	"Sleep",
	"Eagle Eye",
	"Electric Arrow",
	"Identify Monster",
	"Jump",
	"Levitate",
	"Lloyd's Beacon",
	"Protection from Magic",
	"Acid Stream",
	"Fly",
	"Invisibility",
	"Lightning Bolt",
	"Web",
	"Wizard Eye",
	"Cold Beam",
	"Feeble Mind",
	"Fire Ball",
	"Guard Dog",
	"Shield",
	"Time Distortion",
	"Disrupt",
	"Fingers of Death",
	"Sand Storm",
	"Shelter",
	"Teleport",
	"Disintegration",
	"Entrapment",
	"Fantastic Freeze",
	"Recharge Item",
	"Super Shock",
	"Dancing Sword",
	"Duplication",
	"Etherealize",
	"Prismatic Light",
	"Incinerate",
	"Mega Volts",
	"Meteor Shower",
	"Power Shield",
	"Implosion",
	"Inferno",
	"Star Burst",
	"Enchant Item",
	"Apparition",
	"Awaken",
	"Bless",
	"First Aid",
	"Light",
	"Power Cure",
	"Turn Undead",
	"Cure Wounds",
	"Heroism",
	"Nature's Gate",
	"Pain",
	"Protection From Elements",
	"Silence",
	"Weaken",
	"Cold Ray",
	"Create Food",
	"Cure Poison",
	"Immobilize",
	"Lasting Light",
	"Walk on Water",
	"Acid Spray",
	"Air Transmutation",
	"Cure Disease",
	"Restore Alignment",
	"Surface",
	"Holy Bonus",
	"Air Encasement",
	"Deadly Swarm",
	"Frenzy",
	"Paralyze",
	"Remove Condition",
	"Earth Transmutation",
	"Rejuvenate",
	"Stone to Flesh",
	"Water Encasement",
	"Water Transmutation",
	"Earth Encasement",
	"Fiery Flail",
	"Moon Ray",
	"Raise Dead",
	"Fire Encasement",
	"Fire Transmutation",
	"Mass Distortion",
	"Town Portal",
	"Divine intervention",
	"Holy Word",
	"Resurrection",
	"Uncurse Item",
};

const uint8_t MM2_SPELL_LEVEL[96] = {
	1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9,
};
