/* Generated by tools/gen_c_tables.py from MM2.EXE DGROUP; do not edit. */
#include "mm2_tables.h"

const uint32_t MM2_EXP_TABLE[18] = {
	1500, 3000, 6000, 12000, 24000, 48000, 96000, 192000, 384000,
	2000, 4000, 8000, 16000, 32000, 64000, 128000, 256000, 512000,
};  /* [group][level 2..10] */

const uint16_t MM2_TOWN_MULT[5] = {
	1, 5, 2, 3, 2,
};
const uint16_t MM2_TOWN_HP_DIV[5] = {
	2, 5, 3, 4, 3,
};
const uint16_t MM2_HP_PER_LEVEL[8] = {
	12, 10, 10, 8, 6, 8, 8, 15,
};
const uint8_t MM2_SWING_DIV[8] = {
	4, 4, 5, 7, 10, 5, 5, 4,
};
const uint8_t MM2_HIT_DIV[8] = {
	1, 1, 1, 3, 4, 2, 2, 1,
};
const uint8_t MM2_MONSTER_TOHIT[16] = {
	40, 45, 50, 55, 60, 65, 70, 75,
	80, 90, 100, 120, 150, 250, 100, 200,
};
const uint8_t MM2_STAT_BRACKET[23] = {
	4, 6, 9, 13, 15, 17, 19, 22,
	26, 30, 45, 60, 75, 90, 105, 120,
	135, 150, 175, 200, 225, 250, 255,
};
const uint8_t MM2_RACE_STAT_ADJ[35] = {
	0, 0, 0, 0, 0, 0, 0,
	255, 1, 0, 255, 0, 1, 0,
	0, 255, 0, 1, 255, 0, 1,
	0, 0, 0, 0, 255, 255, 2,
	1, 255, 255, 1, 0, 0, 255,
};  /* [race][Might,Int,Per,End,Spd,Acc,Luck]; 255 = -1 */
const uint8_t MM2_RACE_RESIST[48] = {
	0, 0, 0, 35, 0, 0,
	5, 0, 10, 0, 5, 0,
	5, 0, 10, 0, 5, 0,
	5, 0, 10, 0, 5, 0,
	0, 0, 0, 0, 0, 0,
	60, 30, 0, 0, 30, 0,
	60, 5, 60, 0, 30, 0,
	0, 0, 0, 0, 0, 0,
};  /* [k][race] k = 0..7 -> char +16+k */
const uint8_t MM2_START_THIEVERY[8] = {
	0, 0, 0, 0, 0, 30, 10, 0,
};
const uint16_t MM2_START_HP[8] = {
	9, 7, 7, 5, 3, 5, 5, 12,
};
const uint16_t MM2_ENDURANCE_HP[22] = {
	5, 12, 0, 0, 1, 1, 2, 2,
	2, 3, 3, 3, 3, 4, 4, 5,
	5, 6, 6, 7, 7, 7,
};
const uint16_t MM2_START_SP[23] = {
	8, 8, 1, 1, 1, 1, 2, 2,
	2, 3, 3, 3, 3, 4, 4, 5,
	5, 6, 6, 7, 7, 7, 8,
};
const uint8_t MM2_START_AC[15] = {
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 1, 1, 2,
};
const uint8_t MM2_START_ITEM[64] = {
	2, 3, 3, 4, 4, 4, 5, 5,
	161, 161, 161, 67, 67, 66, 67, 161,
	1, 1, 1, 1, 1, 1, 1, 1,
	2, 3, 2, 1, 1, 1, 4, 1,
	3, 4, 4, 3, 2, 2, 4, 3,
	6, 7, 6, 7, 4, 4, 6, 8,
	12, 10, 12, 9, 5, 5, 8, 9,
	15, 15, 15, 11, 10, 10, 13, 15,
};  /* [tier][class] */
const uint8_t MM2_TREASURE_THRESHOLD[7] = {
	25, 40, 50, 55, 70, 75, 100,
};
const uint8_t MM2_TREASURE_ROWS[28] = {
	0, 24, 53, 65,
	65, 13, 19, 26,
	91, 6, 13, 19,
	114, 3, 10, 12,
	126, 8, 23, 28,
	154, 2, 4, 5,
	159, 22, 34, 48,
};  /* {base item id, range for quality 0..2} */
const uint8_t MM2_TREASURE_CHARGES[4] = {
	5, 60, 200, 0,
};
