"""
IDA Pro script: walks every CALL xref to write_string, reads the
decoded-text comment fix_inline_strings.py left on each call site, and
dumps a full game-text inventory to a text file.

Background: fix_inline_strings.py's cleanup of the "inline string
after CALL" trick (see this file's own docstring, and the "inline
data after CALL" section in docs/overview.md) leaves a comment on each
write_string call site showing the decoded string it prints. Since
every one of those call sites has now been fixed and commented (the
whole binary's write_string call graph was swept this session and
earlier ones), this script gets a complete game-text catalog "for
free" by just reading those comments back out -- no re-decoding
needed.

Output format, one line per call site, sorted by address:
    <address> <enclosing_function>: "<decoded text>"

Useful both as documentation (a searchable game-text reference) and
later as a resource-file source for the ScummVM port.

USAGE: read-only against the IDB (no IDB modifications at all) --
writes only to the output text file. Safe to re-run any time to
refresh the catalog after further edits.
"""

import ida_funcs
import ida_name
import ida_xref
import idaapi
import idautils
import idc

OUTPUT_PATH = r"C:\dev\ultima2\docs\game-text-catalog.txt"


def find_call_sites(func_ea):
    sites = []
    for xref in idautils.XrefsTo(func_ea, 0):
        if xref.type in (ida_xref.fl_CN, ida_xref.fl_CF):
            sites.append(xref.frm)
    return sites


def enclosing_function_name(ea):
    pfn = ida_funcs.get_func(ea)
    if pfn is None:
        return "?"
    name = ida_name.get_name(pfn.start_ea)
    return name if name else f"sub_{pfn.start_ea:X}"


def main():
    func_ea = idc.get_name_ea_simple("write_string")
    if func_ea == idaapi.BADADDR:
        print("[!] write_string not found -- aborting")
        return

    sites = find_call_sites(func_ea)
    print(f"{len(sites)} call site(s) to write_string")

    entries = []
    no_comment = []
    for call_ea in sorted(sites):
        cmt = idc.get_cmt(call_ea, 0)
        if not cmt:
            no_comment.append(call_ea)
            continue
        fname = enclosing_function_name(call_ea)
        entries.append((call_ea, fname, cmt))

    print(f"{len(entries)} site(s) with a decoded-text comment, "
          f"{len(no_comment)} without")
    if no_comment:
        print("Sites missing a comment (not yet fixed, or a "
              "genuinely comment-less case):")
        for ea in no_comment:
            print(f"  {ea:X}")

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("Ultima II (DOS) -- write_string call-site text catalog\n")
        f.write(f"{len(entries)} entries, generated by "
                "ida_scripts/build_string_catalog.py\n")
        f.write("=" * 70 + "\n\n")
        for ea, fname, cmt in entries:
            text = cmt.replace("\r", "\\r").replace("\n", "\\n")
            f.write(f"{ea:05X}  {fname}: {text!r}\n")

    print(f"\nWrote {len(entries)} entries to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
