// Generated by tools/gen_records.py from manifest/schema_*.tsv - do not edit.

#include "vstables/records.h"

#include "TSText.h"
#include "TTAction.h"
#include "TTButton.h"
#include "TTScene.h"
#include "TTText.h"
#include "vstables/fieldIds.h"

// Recovered group of TSAction ("ActiveAction", table 25).
TTypeGroup &TSAction::GetTypeGroup() {
	static TTypeGroup typeGroup(533, static_cast<eVisionaireTable>(25), static_cast<eSaveGame>(1), -1, -1, -1, -1);
	return typeGroup;
}

void TSAction::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kActionSavedObject, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kActionActionPartStarted, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kActionActionPartIndex, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kActionContinueWaitForEndIfElse, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kActionTimerStarted, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kActionPauseTime, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));

	group.SetCreate(TSAction::OnCreate);
	group.SetInit(TSAction::OnInit);
}

// Recovered group of TSAnimation ("ActiveAnimation", table 26).
TTypeGroup &TSAnimation::GetTypeGroup() {
	static TTypeGroup typeGroup(535, static_cast<eVisionaireTable>(26), static_cast<eSaveGame>(1), -1, -1, -1, -1);
	return typeGroup;
}

void TSAnimation::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kAnimationSavedObject, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kAnimationLoops, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kPlayOppositeDirection, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 42, -1));
	group.AddType(TTypeData(kAnimationCurrentSpriteIndex, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kAnimationCurrentSpritePos, eTypeData::kPoint, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kAnimationCurrentPosition, eTypeData::kPoint, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kAnimationCalledTime, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kAnimationSize, eTypeData::kFloat, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kAnimationWaiting, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kAnimationWaitingTime, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kFrameCount, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 42, -1));
	group.AddType(TTypeData(kAnimationPreloaded, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 54, -1));
	group.AddType(TTypeData(kAnimationActive, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 56, -1));
	group.AddType(TTypeData(kAnimationFirstFrame, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 99, -1));
	group.AddType(TTypeData(kAnimationLastFrame, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 99, -1));
	group.AddType(TTypeData(kAnimationStartedByUser, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 133, -1));

	group.SetCreate(TSAnimation::OnCreate);
	group.SetInit(TSAnimation::OnInit);
}

// Recovered group of TSText ("ActiveText", table 24).
TTypeGroup &TSText::GetTypeGroup() {
	static TTypeGroup typeGroup(531, static_cast<eVisionaireTable>(24), static_cast<eSaveGame>(1), -1, -1, -1, -1);
	return typeGroup;
}

void TSText::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kTextSavedObject, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextRemainingText, eTypeData::kString, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextCurrentText, eTypeData::kString, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextPosition, eTypeData::kPoint, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextTimeToWait, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextTimeElapsed, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextFont, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextBackground, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextSpeaker, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, -1, 124));
	group.AddType(TTypeData(kTextActive, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextWaitForAudio, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kTextOwner, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 125, -1));
	group.AddType(TTypeData(kTextAlignment, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 155, -1));

	group.SetCreate(TSText::OnCreate);
	group.SetInit(TSText::OnInit);
}

// Recovered group of TTAction ("Action", table 7).
TTypeGroup &TTAction::GetTypeGroup() {
	static TTypeGroup typeGroup(158, static_cast<eVisionaireTable>(7), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTAction::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kActionExecutionType, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kActionFixture, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kActionCommand, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kActionActionParts, eTypeData::kLinkList, static_cast<eVisionaireTable>(8), 1, -1));

	group.SetCreate(TTAction::OnCreate);
	group.SetInit(TTAction::OnInit);
}

// Recovered group of TTActionArea ("ActionArea", table 32).
TTypeGroup &TTActionArea::GetTypeGroup() {
	static TTypeGroup typeGroup(673, static_cast<eVisionaireTable>(32), static_cast<eSaveGame>(0), 120, -1, -1, -1);
	return typeGroup;
}

void TTActionArea::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kActionAreaPolygon, eTypeData::kPointList, static_cast<eSaveGame>(0), 120, -1, -1, -1));
	group.AddType(TTypeData(kActionAreaActions, eTypeData::kLinkList, static_cast<eVisionaireTable>(33), 120, -1));

	group.SetCreate(TTActionArea::OnCreate);
	group.SetInit(TTActionArea::OnInit);
}

// Recovered group of TTActionPart ("ActionPart", table 8).
TTypeGroup &TTActionPart::GetTypeGroup() {
	static TTypeGroup typeGroup(178, static_cast<eVisionaireTable>(8), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTActionPart::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kActionPartCommand, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kActionPartLink, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kActionPartPath, eTypeData::kPath, 1, -1));
	group.AddType(TTypeData(kActionPartInt, eTypeData::kInt, 19, -1));
	group.AddType(TTypeData(kActionPartAltLink, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kActionPartAltInt, eTypeData::kInt, 23, -1));
	group.AddType(TTypeData(kActionPartAltInt2, eTypeData::kInt, 99, -1));
	group.AddType(TTypeData(kActionPartString, eTypeData::kString, 100, -1));

	group.SetCreate(TTActionPart::OnCreate);
	group.SetInit(TTActionPart::OnInit);
	group.SetNameInList(TTActionPart::GetNameInList);
}

// Recovered group of TTAnimation ("Animation", table 9).
TTypeGroup &TTAnimation::GetTypeGroup() {
	static TTypeGroup typeGroup(182, static_cast<eVisionaireTable>(9), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTAnimation::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kAnimationLoopRandom, eTypeData::kBool, 1, -1));
	group.AddType(TTypeData(kAnimationOppositeDirection, eTypeData::kBool, -1, 112));
	group.AddType(TTypeData(kAnimationRandomOrder, eTypeData::kBool, -1, 112));
	group.AddType(TTypeData(kAnimationNumberOfLoops, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kAnimationPause, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kAnimationPosition, eTypeData::kPoint, 1, -1));
	group.AddType(TTypeData(kAnimationAction, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kAnimationSprites, eTypeData::kSpriteList, 18, -1));
	group.AddType(TTypeData(kAnimationMirror, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kAnimationDirection, eTypeData::kInt, 23, -1));
	group.AddType(TTypeData(kAnimationMove, eTypeData::kBool, 24, -1));
	group.AddType(TTypeData(kAnimationUseIndividualPause, eTypeData::kBool, 25, -1));
	group.AddType(TTypeData(kAnimationStandingSprite, eTypeData::kSprite, 27, 111));
	group.AddType(TTypeData(kAnimationResetPosition, eTypeData::kBool, 30, 111));
	group.AddType(TTypeData(kAnimationCenter, eTypeData::kPoint, 30, -1));
	group.AddType(TTypeData(kAnimationPropertyFrames, eTypeData::kLinkList, 54, -1));
	group.AddType(TTypeData(kAnimationReplay, eTypeData::kInt, 112, -1));
	group.AddType(TTypeData(kAnimationModelAnimIndex, eTypeData::kInt, 142, -1));
	group.AddType(TTypeData(kAnimationModelAnimSpeed, eTypeData::kInt, 142, -1));
	group.AddType(TTypeData(kAnimationWalkSteps, eTypeData::kFloatList, 166, -1));
	group.AddType(TTypeData(kAnimationModelFile, eTypeData::kPath, 180, -1));
	group.AddType(TTypeData(kAnimationModelName, eTypeData::kString, 180, -1));
	group.AddType(TTypeData(kAnimationEndDirection, eTypeData::kInt, 180, -1));

	group.SetCreate(TTAnimation::OnCreate);
	group.SetInit(TTAnimation::OnInit);
}

// Recovered group of TTAnimationFrame ("AnimationFrame", table 28).
TTypeGroup &TTAnimationFrame::GetTypeGroup() {
	static TTypeGroup typeGroup(570, static_cast<eVisionaireTable>(28), static_cast<eSaveGame>(0), 54, -1, -1, -1);
	return typeGroup;
}

void TTAnimationFrame::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kAnimationFrameIndex, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kAnimationFrameSound, eTypeData::kPath, 1, -1));
	group.AddType(TTypeData(kAnimationFrameSoundVolume, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kAnimationFrameSoundBalance, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kAnimationFrameAction, eTypeData::kLink, 1, -1));

	group.SetCreate(TTAnimationFrame::OnCreate);
	group.SetInit(TTAnimationFrame::OnInit);
}

// Recovered group of TTAreaAction ("AreaAction", table 33).
TTypeGroup &TTAreaAction::GetTypeGroup() {
	static TTypeGroup typeGroup(677, static_cast<eVisionaireTable>(33), static_cast<eSaveGame>(0), 120, -1, -1, -1);
	return typeGroup;
}

void TTAreaAction::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kAreaActionCharacter, eTypeData::kLink, static_cast<eVisionaireTable>(0), 120, -1));
	group.AddType(TTypeData(kAreaActionExecuteAlways, eTypeData::kBool, static_cast<eSaveGame>(0), 120, -1, -1, -1));
	group.AddType(TTypeData(kAreaActionAction, eTypeData::kLink, static_cast<eVisionaireTable>(7), 120, -1));

	group.SetCreate(TTAreaAction::OnCreate);
	group.SetInit(TTAreaAction::OnInit);
}

// Recovered group of TTAudioBus ("AudioBus", table 37).
TTypeGroup &TTAudioBus::GetTypeGroup() {
	static TTypeGroup typeGroup(827, static_cast<eVisionaireTable>(37), 184, -1);
	return typeGroup;
}

void TTAudioBus::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kAudioBusLinks, eTypeData::kLinkList, 184, -1));
	group.AddType(TTypeData(kAudioBusType, eTypeData::kInt, 184, -1));
	group.AddType(TTypeData(kAudioBusSettings, eTypeData::kString, 184, -1));
	group.AddType(TTypeData(kAudioBusValues, eTypeData::kLinkList, 184, -1));
	group.AddType(TTypeData(kAudioBusEvents, eTypeData::kLinkList, 184, -1));

	group.SetCreate(TTAudioBus::OnCreate);
	group.SetInit(TTAudioBus::OnInit);
}

// Recovered group of TTButton ("Button", table 2).
TTypeGroup &TTButton::GetTypeGroup() {
	static TTypeGroup typeGroup(152, static_cast<eVisionaireTable>(2), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTButton::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kButtonAction, eTypeData::kInt, -1, 100));
	group.AddType(TTypeData(kButtonActiveSprite, eTypeData::kLink, 25, -1));
	group.AddType(TTypeData(kButtonInactiveSprite, eTypeData::kLink, 25, -1));
	group.AddType(TTypeData(kButtonCursor, eTypeData::kLink, 15, -1));
	group.AddType(TTypeData(kButtonName, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kButtonConjunction, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kButtonType, eTypeData::kInt, 23, -1));
	group.AddType(TTypeData(kButtonCommandType, eTypeData::kInt, 100, -1));
	group.AddType(TTypeData(kButtonUse, eTypeData::kInt, 24, -1));
	group.AddType(TTypeData(kButtonUseOnOwnCharacter, eTypeData::kBool, 40, 100));
	group.AddType(TTypeData(kButtonUseOnCurrentCharacter, eTypeData::kBool, 100, -1));
	group.AddType(TTypeData(kButtonPolygon, eTypeData::kPointList, 41, -1));
	group.AddType(TTypeData(kButtonActions, eTypeData::kLinkList, static_cast<eVisionaireTable>(7), 41, -1));
	group.AddType(TTypeData(kButtonCondition, eTypeData::kLink, 43, -1));
	group.AddType(TTypeData(kButtonConditionNegate, eTypeData::kBool, 43, -1));
	group.AddType(TTypeData(kButtonAnimation, eTypeData::kLink, 43, -1));
	group.AddType(TTypeData(kButtonAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 43, -1));
	group.AddType(TTypeData(kButtonDraggable, eTypeData::kBool, 53, -1));
	group.AddType(TTypeData(kButtonGroup, eTypeData::kLinkList, static_cast<eVisionaireTable>(2), 60, -1));
	group.AddType(TTypeData(kButtonRotation, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kButtonRotationCenter, eTypeData::kPoint, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kButtonShaderSet, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kButtonScale, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kButtonMatrixId, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kButtonScaleX, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kButtonScaleY, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 180, -1));

	group.SetCreate(TTButton::OnCreate);
	group.SetInit(TTButton::OnInit);
}

// Recovered group of TTCharacter ("Character", table 0).
TTypeGroup &TTCharacter::GetTypeGroup() {
	static TTypeGroup typeGroup(148, static_cast<eVisionaireTable>(0), -1, -1);
	return typeGroup;
}

void TTCharacter::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kCharacterName, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kCharacterWalkingSound, eTypeData::kPath, static_cast<eSaveGame>(2), 23, -1, -1, -1));
	group.AddType(TTypeData(kCharacterInterfaces, eTypeData::kLinkList, static_cast<eVisionaireTable>(1), 2, -1));
	group.AddType(TTypeData(kCharacterFont, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kCharacterCurrentOutfit, eTypeData::kLink, static_cast<eSaveGame>(2), 23, -1, -1, -1));
	group.AddType(TTypeData(kCharacterCurrentCommentSet, eTypeData::kLink, static_cast<eSaveGame>(2), 23, -1, -1, -1));
	group.AddType(TTypeData(kCharacterDialogCursor, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kCharacterDialogs, eTypeData::kLinkList, static_cast<eVisionaireTable>(11), 23, -1));
	group.AddType(TTypeData(kCharacterTexts, eTypeData::kLinkList, static_cast<eVisionaireTable>(14), 23, 32));
	group.AddType(TTypeData(kCharacterActions, eTypeData::kLinkList, static_cast<eVisionaireTable>(7), 23, -1));
	group.AddType(TTypeData(kCharacterOutfits, eTypeData::kLinkList, static_cast<eVisionaireTable>(17), 23, -1));
	group.AddType(TTypeData(kCharacterCommentSets, eTypeData::kLinkList, static_cast<eVisionaireTable>(16), 23, -1));
	group.AddType(TTypeData(kCharacterStartObject, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kCharacterValues, eTypeData::kLinkList, static_cast<eVisionaireTable>(20), 24, -1));
	group.AddType(TTypeData(kCharacterConditions, eTypeData::kLinkList, static_cast<eVisionaireTable>(10), 24, -1));
	group.AddType(TTypeData(kCharacterScale, eTypeData::kBool, 41, -1));
	group.AddType(TTypeData(kCharacterActiveDialogFont, eTypeData::kLink, 41, -1));
	group.AddType(TTypeData(kCharacterInactiveDialogFont, eTypeData::kLink, 57, -1));
	group.AddType(TTypeData(kCharacterDialogArea, eTypeData::kRect, 41, -1));
	group.AddType(TTypeData(kCharacterDialogActiveScrollUp, eTypeData::kSprite, 41, -1));
	group.AddType(TTypeData(kCharacterDialogInactiveScrollUp, eTypeData::kSprite, 41, -1));
	group.AddType(TTypeData(kCharacterDialogActiveScrollDown, eTypeData::kSprite, 41, -1));
	group.AddType(TTypeData(kCharacterDialogInactiveScrollDown, eTypeData::kSprite, 41, -1));
	group.AddType(TTypeData(kCharacterDialogSprite, eTypeData::kSprite, 41, -1));
	group.AddType(TTypeData(kCharacterDialogVerticalSpace, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kCharacterActive, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterScene, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterFollowCharacter, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterActionCharacter, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterFollowAction, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterFollowReachDistance, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterAnimState, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterDirection, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterState, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterPosition, eTypeData::kPoint, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterDestination, eTypeData::kPoint, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterDestinationObject, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterActiveCommand, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kCharacterInterfaceWithItems, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 100, 114));
	group.AddType(TTypeData(kCharacterAlpha, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 47, 100));
	group.AddType(TTypeData(kCharacterDestAlpha, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 47, 100));
	group.AddType(TTypeData(kCharacterTimeToDestAlpha, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 47, 100));
	group.AddType(TTypeData(kCharacterAnimIndex, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 51, -1));
	group.AddType(TTypeData(kCharacterScaleFactor, eTypeData::kInt, static_cast<eSaveGame>(2), 52, -1, 52, -1));
	group.AddType(TTypeData(kCharacterVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kCharacterDestVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kCharacterTimeToDestVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kCharacterItems, eTypeData::kLinkList, static_cast<eSaveGame>(1), -1, -1, 114, -1));
	group.AddType(TTypeData(kCharacterTint, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 115, -1));
	group.AddType(TTypeData(kCharacterActionDestPosition, eTypeData::kPoint, static_cast<eSaveGame>(2), 149, -1, 148, -1));
	group.AddType(TTypeData(kCharacterSize, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 158, -1));
	group.AddType(TTypeData(kCharacterMatrixId, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 178, -1));
	group.AddType(TTypeData(kCharacterShaderSet, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 179, -1));
	group.AddType(TTypeData(kCharacterLightmapActive, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kCharacterHarmonizeWalkAnimations, eTypeData::kBool, 186, -1));

	group.SetCreate(TTCharacter::OnCreate);
	group.SetInit(TTCharacter::OnInit);
}

// Recovered group of TTClipboardObject ("Clipboard", table -1).
TTypeGroup &TTClipboardObject::GetTypeGroup() {
	static TTypeGroup typeGroup(37, static_cast<eVisionaireTable>(-1), -1, -1);
	return typeGroup;
}

void TTClipboardObject::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kClipboardObjects, eTypeData::kLinkList, 1, -1));
	group.AddType(TTypeData(kClipboardParentTable, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kClipboardParentField, eTypeData::kInt, 1, -1));
}

// Recovered group of TTCommentSet ("CommentSet", table 16).
TTypeGroup &TTCommentSet::GetTypeGroup() {
	static TTypeGroup typeGroup(263, static_cast<eVisionaireTable>(16), static_cast<eSaveGame>(0), 23, -1, -1, -1);
	return typeGroup;
}

void TTCommentSet::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kCommentSetElements, eTypeData::kLinkList, static_cast<eVisionaireTable>(14), -1, 48));
	group.AddType(TTypeData(kCommentSetEntries, eTypeData::kLinkList, static_cast<eVisionaireTable>(27), 48, -1));

	group.SetCreate(TTCommentSet::OnCreate);
	group.SetInit(TTCommentSet::OnInit);
}

// Recovered group of TTCommentSetEntry ("CommentSetEntry", table 27).
TTypeGroup &TTCommentSetEntry::GetTypeGroup() {
	static TTypeGroup typeGroup(558, static_cast<eVisionaireTable>(27), static_cast<eSaveGame>(0), 48, -1, -1, -1);
	return typeGroup;
}

void TTCommentSetEntry::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kCommentSetEntryText, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kCommentSetEntryCommand, eTypeData::kLink, 1, -1));

	group.SetCreate(TTCommentSetEntry::OnCreate);
	group.SetInit(TTCommentSetEntry::OnInit);
}

// Recovered group of TTCondition ("Condition", table 10).
TTypeGroup &TTCondition::GetTypeGroup() {
	static TTypeGroup typeGroup(192, static_cast<eVisionaireTable>(10), -1, -1);
	return typeGroup;
}

void TTCondition::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kConditionIsVariable, eTypeData::kBool, 1, -1));
	group.AddType(TTypeData(kConditionValue, eTypeData::kBool, static_cast<eSaveGame>(2), 1, -1, -1, -1));
	group.AddType(TTypeData(kConditionReturnNegate, eTypeData::kBool, 1, -1));
	group.AddType(TTypeData(kConditionCondition1Negate, eTypeData::kBool, 1, -1));
	group.AddType(TTypeData(kConditionCondition2Negate, eTypeData::kBool, 1, -1));
	group.AddType(TTypeData(kConditionOperator, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kConditionCondition1, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kConditionCondition2, eTypeData::kLink, 1, -1));

	group.SetCreate(TTCondition::OnCreate);
	group.SetInit(TTCondition::OnInit);
}

// Recovered group of TTCursor ("Cursor", table 15).
TTypeGroup &TTCursor::GetTypeGroup() {
	static TTypeGroup typeGroup(226, static_cast<eVisionaireTable>(15), static_cast<eSaveGame>(0), 15, -1, -1, -1);
	return typeGroup;
}

void TTCursor::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kCursorSpritesActive, eTypeData::kSpriteList, 18, 99));
	group.AddType(TTypeData(kCursorSpritesInActive, eTypeData::kSpriteList, 18, 99));
	group.AddType(TTypeData(kCursorActiveAnimation, eTypeData::kLink, 99, -1));
	group.AddType(TTypeData(kCursorInactiveAnimation, eTypeData::kLink, 99, -1));
	group.AddType(TTypeData(kCursorHotspot, eTypeData::kPoint, 18, 100));

	group.SetCreate(TTCursor::OnCreate);
	group.SetInit(TTCursor::OnInit);
}

// Recovered group of TTDialog ("Dialog", table 11).
TTypeGroup &TTDialog::GetTypeGroup() {
	static TTypeGroup typeGroup(201, static_cast<eVisionaireTable>(11), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTDialog::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kDialogDialogParts, eTypeData::kLinkList, static_cast<eVisionaireTable>(12), 1, -1));
	group.AddType(TTypeData(kDialogCharacter, eTypeData::kLink, 182, -1));

	group.SetCreate(TTDialog::OnCreate);
	group.SetInit(TTDialog::OnInit);
}

// Recovered group of TTDialogPart ("DialogPart", table 12).
TTypeGroup &TTDialogPart::GetTypeGroup() {
	static TTypeGroup typeGroup(203, static_cast<eVisionaireTable>(12), -1, -1);
	return typeGroup;
}

void TTDialogPart::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kDialogPartCondition, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kDialogPartConditionValue, eTypeData::kBool, 10, 100));
	group.AddType(TTypeData(kDialogPartConditionNegate, eTypeData::kBool, 100, -1));
	group.AddType(TTypeData(kDialogPartText, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kDialogPartAction, eTypeData::kLink, static_cast<eVisionaireTable>(7), 1, -1));
	group.AddType(TTypeData(kDialogPartLinkedAction, eTypeData::kLink, static_cast<eVisionaireTable>(7), 104, -1));
	group.AddType(TTypeData(kDialogPartAnswerText, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kDialogPartReturn, eTypeData::kInt, 23, -1));
	group.AddType(TTypeData(kDialogPartRemove, eTypeData::kBool, 23, -1));
	group.AddType(TTypeData(kDialogPartNextDialog, eTypeData::kLink, static_cast<eVisionaireTable>(11), 23, -1));
	group.AddType(TTypeData(kDialogPartAltText, eTypeData::kLink, 41, -1));
	group.AddType(TTypeData(kDialogPartUseAltText, eTypeData::kBool, 41, -1));
	group.AddType(TTypeData(kDialogPartAvailable, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 23, -1));

	group.SetCreate(TTDialogPart::OnCreate);
	group.SetInit(TTDialogPart::OnInit);
}

// Recovered group of TTEvent ("Event", table 38).
TTypeGroup &TTEvent::GetTypeGroup() {
	static TTypeGroup typeGroup(832, static_cast<eVisionaireTable>(38), 184, -1);
	return typeGroup;
}

void TTEvent::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);

	group.SetCreate(TTEvent::OnCreate);
	group.SetInit(TTEvent::OnInit);
}

// Recovered group of TTFont ("Font", table 3).
TTypeGroup &TTFont::GetTypeGroup() {
	static TTypeGroup typeGroup(141, static_cast<eVisionaireTable>(3), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTFont::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kFontSprite, eTypeData::kSprite, 23, -1));
	group.AddType(TTypeData(kFontLetters, eTypeData::kRectList, 1, -1));
	group.AddType(TTypeData(kFontAlphabet, eTypeData::kString, 23, -1));
	group.AddType(TTypeData(kFontLetterSpacing, eTypeData::kInt, 23, -1));
	group.AddType(TTypeData(kVerticalLetterSpacing, eTypeData::kInt, 42, -1));
	group.AddType(TTypeData(kFontSpaceWidth, eTypeData::kInt, 100, -1));
	group.AddType(TTypeData(kFontAutoLineBreak, eTypeData::kBool, 100, -1));
	group.AddType(TTypeData(kFontLineWidth, eTypeData::kInt, 100, -1));
	group.AddType(TTypeData(kFontKerning, eTypeData::kString, 138, -1));
	group.AddType(TTypeData(kFontTrueTypeFont, eTypeData::kBool, 171, -1));
	group.AddType(TTypeData(kFontFont, eTypeData::kLink, 171, -1));
	group.AddType(TTypeData(kFontTrueTypeFontPath, eTypeData::kPath, 171, -1));
	group.AddType(TTypeData(kFontSize, eTypeData::kFloat, 171, -1));
	group.AddType(TTypeData(kFontColor, eTypeData::kInt, 171, -1));
	group.AddType(TTypeData(kFontBorder, eTypeData::kBool, 171, -1));
	group.AddType(TTypeData(kFontBorderColor, eTypeData::kInt, 171, -1));
	group.AddType(TTypeData(kFontBorderSize, eTypeData::kFloat, 171, -1));
	group.AddType(TTypeData(kFontShadow, eTypeData::kBool, 171, -1));
	group.AddType(TTypeData(kFontShadowOffset, eTypeData::kPoint, 171, -1));

	group.SetCreate(TTFont::OnCreate);
	group.SetInit(TTFont::OnInit);
}

// Recovered group of TTGame ("Game", table -1).
TTypeGroup &TTGame::GetTypeGroup() {
	static TTypeGroup typeGroup(116, static_cast<eVisionaireTable>(-1), -1, -1);
	return typeGroup;
}

void TTGame::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kGameId, eTypeData::kString, 35, -1));
	group.AddType(TTypeData(kGameSaveGameName, eTypeData::kString, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameSceneLinks, eTypeData::kLinkList, static_cast<eVisionaireTable>(4), 1, -1));
	group.AddType(TTypeData(kGameCharacterLinks, eTypeData::kLinkList, static_cast<eVisionaireTable>(0), 1, -1));
	group.AddType(TTypeData(kGameInterfaces, eTypeData::kLinkList, static_cast<eVisionaireTable>(1), 99, -1));
	group.AddType(TTypeData(kGameFontLinks, eTypeData::kLinkList, static_cast<eVisionaireTable>(3), 1, -1));
	group.AddType(TTypeData(kGameLanguages, eTypeData::kLinkList, static_cast<eVisionaireTable>(18), 23, -1));
	group.AddType(TTypeData(kGameFirstScene, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kGameItems, eTypeData::kLinkList, static_cast<eVisionaireTable>(6), 26, -1));
	group.AddType(TTypeData(kGameLoading, eTypeData::kLink, 26, -1));
	group.AddType(TTypeData(kGameDescription, eTypeData::kString, 1, -1));
	group.AddType(TTypeData(kGameAbout, eTypeData::kString, 1, -1));
	group.AddType(TTypeData(kGameWindowResolution, eTypeData::kPoint, 1, -1));
	group.AddType(TTypeData(kGameCursors, eTypeData::kLinkList, static_cast<eVisionaireTable>(15), 8, -1));
	group.AddType(TTypeData(kGameIntro, eTypeData::kPath, 15, -1));
	group.AddType(TTypeData(kGameCommandBehaviour, eTypeData::kInt, static_cast<eSaveGame>(2), 21, -1, 100, -1));
	group.AddType(TTypeData(kGameFadeDelay, eTypeData::kInt, static_cast<eSaveGame>(2), 17, -1, 47, -1));
	group.AddType(TTypeData(kGameScrollSpeed, eTypeData::kInt, static_cast<eSaveGame>(2), 22, -1, 100, -1));
	group.AddType(TTypeData(kGameFullScreenIntro, eTypeData::kBool, 22, -1));
	group.AddType(TTypeData(kGameFirstCharacter, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kGameRightMouseClick, eTypeData::kInt, static_cast<eSaveGame>(2), 23, 171, 100, 171));
	group.AddType(TTypeData(kGameDraggableItems, eTypeData::kBool, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kGameStandardLanguage, eTypeData::kLink, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kGameActions, eTypeData::kLinkList, static_cast<eVisionaireTable>(7), 23, -1));
	group.AddType(TTypeData(kGameStartAction, eTypeData::kLink, 34, -1));
	group.AddType(TTypeData(kGameRightClickAction, eTypeData::kLink, 24, -1));
	group.AddType(TTypeData(kGameReserved, eTypeData::kString, 35, -1));
	group.AddType(TTypeData(kGameHoldTime, eTypeData::kInt, static_cast<eSaveGame>(2), 37, -1, 100, -1));
	group.AddType(TTypeData(kGameLeftMouseDblClick, eTypeData::kInt, static_cast<eSaveGame>(2), 37, 171, 100, 171));
	group.AddType(TTypeData(kGameLeftDblClickAction, eTypeData::kLink, 37, -1));
	group.AddType(TTypeData(kGameLeftMouseHold, eTypeData::kInt, static_cast<eSaveGame>(2), 37, 171, 100, 171));
	group.AddType(TTypeData(kGameLeftHoldAction, eTypeData::kLink, 37, -1));
	group.AddType(TTypeData(kGameLeftMouseHolding, eTypeData::kInt, static_cast<eSaveGame>(2), 39, 171, 100, 171));
	group.AddType(TTypeData(kGameLeftHoldingAction, eTypeData::kLink, 39, -1));
	group.AddType(TTypeData(kGameParticleContainerLinks, eTypeData::kLinkList, static_cast<eVisionaireTable>(23), 41, -1));
	group.AddType(TTypeData(kGameFadeEffect, eTypeData::kInt, static_cast<eSaveGame>(2), 44, -1, 47, -1));
	group.AddType(TTypeData(kGameMinificationFilter, eTypeData::kInt, 45, -1));
	group.AddType(TTypeData(kGameMagnificationFilter, eTypeData::kInt, 45, -1));
	group.AddType(TTypeData(kGameCurrentCharacter, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameCurrentScene, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameScrollPosition, eTypeData::kPoint, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameScrollToPoint, eTypeData::kPoint, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameScrollTo, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameScrollDirectionHorizontal, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameScrollDirectionVertical, eTypeData::kInt, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameWaitForDialogSelection, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, -1, 99));
	group.AddType(TTypeData(kGameDialog, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameCurrentText, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameBackgroundTexts, eTypeData::kLinkList, static_cast<eSaveGame>(1), -1, -1, 1, 99));
	group.AddType(TTypeData(kGameAutoHideInterfacesInMenu, eTypeData::kBool, static_cast<eSaveGame>(2), 100, -1, 100, -1));
	group.AddType(TTypeData(kGameHideInterfaces, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameHideCursor, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameDialogAction, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameCurrentDialogAction, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 99, -1));
	group.AddType(TTypeData(kGameDestinationCommand, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameDestinationItem, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameDestinationItemPicked, eTypeData::kBool, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameDestinationEvent, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kGameSavedObject, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kGameSceneBrightness, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 47, 99));
	group.AddType(TTypeData(kGameObjectSaved, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, -1, 47));
	group.AddType(TTypeData(kGameScrollCenterCharacter, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 50, -1));
	group.AddType(TTypeData(kGameScrollCharacter, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kGameLeftMouseClick, eTypeData::kInt, 51, 171));
	group.AddType(TTypeData(kGameLeftClickAction, eTypeData::kLink, 51, -1));
	group.AddType(TTypeData(kGameAlwaysAllowSkipText, eTypeData::kBool, static_cast<eSaveGame>(2), 52, -1, 100, -1));
	group.AddType(TTypeData(kGameExecuteActionsDuringDialog, eTypeData::kBool, static_cast<eSaveGame>(2), 55, -1, 100, -1));
	group.AddType(TTypeData(kGameHiddenDialog, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 56, -1));
	group.AddType(TTypeData(kGameAlignCharacterOnImExecution, eTypeData::kBool, 58, -1));
	group.AddType(TTypeData(kGameTextOutput, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 59, -1));
	group.AddType(TTypeData(kGameComposedFile, eTypeData::kPath, static_cast<eSaveGame>(2), 99, -1, 169, -1));
	group.AddType(TTypeData(kGameSceneComposedFiles, eTypeData::kInt, 99, -1));
	group.AddType(TTypeData(kGameSceneComposedFile, eTypeData::kPath, 99, -1));
	group.AddType(TTypeData(kGameCharacterComposedFiles, eTypeData::kInt, 100, -1));
	group.AddType(TTypeData(kGameCharacterComposedFile, eTypeData::kPath, 100, -1));
	group.AddType(TTypeData(kGameMovieComposedFiles, eTypeData::kInt, 100, -1));
	group.AddType(TTypeData(kGameMovieComposedFile, eTypeData::kPath, 100, -1));
	group.AddType(TTypeData(kGameVersion, eTypeData::kString, 100, -1));
	group.AddType(TTypeData(kGameActiveCommand, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kGameDrawActionText, eTypeData::kInt, static_cast<eSaveGame>(2), 99, -1, 116, -1));
	group.AddType(TTypeData(kGameActionTextFont, eTypeData::kLink, static_cast<eSaveGame>(2), 99, -1, 139, -1));
	group.AddType(TTypeData(kGameActionTextRect, eTypeData::kRect, 99, -1));
	group.AddType(TTypeData(kGameQuake, eTypeData::kBool, 99, -1));
	group.AddType(TTypeData(kGameQuakeForce, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 99, -1));
	group.AddType(TTypeData(kGameQuakeSpeed, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 99, -1));
	group.AddType(TTypeData(kGameSpeakerTextAlignment, eTypeData::kInt, static_cast<eSaveGame>(2), 99, -1, 99, -1));
	group.AddType(TTypeData(kGameTextAlignment, eTypeData::kInt, static_cast<eSaveGame>(2), 99, -1, 99, -1));
	group.AddType(TTypeData(kGameCutsceneAction, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 99, -1));
	group.AddType(TTypeData(kGameKeepCharacterSpritesDuringMenus, eTypeData::kBool, 99, -1));
	group.AddType(TTypeData(kGameDisableInteractionDuringAnim, eTypeData::kInt, 99, -1));
	group.AddType(TTypeData(kGameTextSpeed, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 99, -1));
	group.AddType(TTypeData(kGameScriptLinks, eTypeData::kLinkList, static_cast<eVisionaireTable>(30), 100, -1));
	group.AddType(TTypeData(kGameInterfaceClasses, eTypeData::kLinkList, static_cast<eVisionaireTable>(31), 114, -1));
	group.AddType(TTypeData(kGameHorizontalScrollDistance, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 119, -1));
	group.AddType(TTypeData(kGameVerticalScrollDistance, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 119, -1));
	group.AddType(TTypeData(kGamePictureCacheSize, eTypeData::kInt, 118, -1));
	group.AddType(TTypeData(kGameInterfaceComposedFiles, eTypeData::kInt, 119, -1));
	group.AddType(TTypeData(kGameInterfaceComposedFile, eTypeData::kPath, 119, -1));
	group.AddType(TTypeData(kGameGameComposedFiles, eTypeData::kInt, 121, -1));
	group.AddType(TTypeData(kGameGameComposedFile, eTypeData::kPath, 121, -1));
	group.AddType(TTypeData(kGameObjectFont, eTypeData::kLink, 125, -1));
	group.AddType(TTypeData(kGameUsedItem, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 126, -1));
	group.AddType(TTypeData(kGameCurrentObject, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 126, -1));
	group.AddType(TTypeData(kGameCursorHorizontalScrollDistance, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 132, -1));
	group.AddType(TTypeData(kGameCursorVerticalScrollDistance, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 132, -1));
	group.AddType(TTypeData(kGameVideosEncrypted, eTypeData::kBool, 134, -1));
	group.AddType(TTypeData(kGameCompanyName, eTypeData::kString, 136, -1));
	group.AddType(TTypeData(kGameGameName, eTypeData::kString, 136, -1));
	group.AddType(TTypeData(kGameObjectTextOutput, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 59, -1));
	group.AddType(TTypeData(kGameModelLinks, eTypeData::kLinkList, static_cast<eVisionaireTable>(35), 141, 144));
	group.AddType(TTypeData(kGameUsedItemPicked, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 146, -1));
	group.AddType(TTypeData(kGamePreloadPicThreads, eTypeData::kInt, 147, -1));
	group.AddType(TTypeData(kGamePreloadedPicBufferSize, eTypeData::kInt, 147, -1));
	group.AddType(TTypeData(kGamePicBufferSize, eTypeData::kInt, 147, -1));
	group.AddType(TTypeData(kGameVideoSubtitleFont, eTypeData::kLink, static_cast<eSaveGame>(2), 151, -1, 150, 151));
	group.AddType(TTypeData(kGameVideoSubtitlePosition, eTypeData::kPoint, static_cast<eSaveGame>(2), 151, -1, 150, 151));
	group.AddType(TTypeData(kGameVideoSubtitleLanguage, eTypeData::kString, static_cast<eSaveGame>(2), 151, -1, 150, 151));
	group.AddType(TTypeData(kGameVideoAudioLanguage, eTypeData::kString, static_cast<eSaveGame>(2), 151, -1, 150, 151));
	group.AddType(TTypeData(kGamePreallocatedTextures3Bpt, eTypeData::kInt, 151, 154));
	group.AddType(TTypeData(kGamePreallocatedTextures4Bpt, eTypeData::kInt, 151, 154));
	group.AddType(TTypeData(kGamePreallocatedTextures, eTypeData::kInt, 154, -1));
	group.AddType(TTypeData(kGameNearestNeighborInterpolation, eTypeData::kBool, 156, -1));
	group.AddType(TTypeData(kGameSpeechLanguage, eTypeData::kLink, static_cast<eSaveGame>(1), -1, -1, 162, -1));
	group.AddType(TTypeData(kSpeakerSoundPanFactor, eTypeData::kInt, static_cast<eSaveGame>(2), 173, -1, 164, -1));
	group.AddType(TTypeData(kGameRegisteredEventHandlers, eTypeData::kString, static_cast<eSaveGame>(1), -1, -1, 166, -1));
	group.AddType(TTypeData(kGameShowBlackScreenAfterVideo, eTypeData::kBool, static_cast<eSaveGame>(2), 169, -1, 169, -1));
	group.AddType(TTypeData(kGameSavegameScreenshot, eTypeData::kPath, 170, -1));
	group.AddType(TTypeData(kGameMiddleClickAction, eTypeData::kLink, 171, -1));
	group.AddType(TTypeData(kGameMouseWheelUpAction, eTypeData::kLink, 171, -1));
	group.AddType(TTypeData(kGameMouseWheelDownAction, eTypeData::kLink, 171, -1));
	group.AddType(TTypeData(kGameLeftHoldBehaviour, eTypeData::kInt, 173, -1));
	group.AddType(TTypeData(kGameMiddleClickBehaviour, eTypeData::kInt, 173, -1));
	group.AddType(TTypeData(kGameRightClickBehaviour, eTypeData::kInt, 173, -1));
	group.AddType(TTypeData(kGameShaderExclude, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 173, -1));
	group.AddType(TTypeData(kGameVideoPauseScreen, eTypeData::kPath, 175, -1));
	group.AddType(TTypeData(kGameExecuteCalledActionImmediately, eTypeData::kBool, 177, -1));
	group.AddType(TTypeData(kGameContainers, eTypeData::kStringList, 180, -1));
	group.AddType(TTypeData(kGameBuildRules, eTypeData::kStringList, 180, -1));
	group.AddType(TTypeData(kGameIconFile, eTypeData::kPath, 181, -1));
	group.AddType(TTypeData(kGameBuildOptions, eTypeData::kString, 181, -1));
	group.AddType(TTypeData(kGameShaderLinks, eTypeData::kLinkList, static_cast<eVisionaireTable>(36), 181, -1));
	group.AddType(TTypeData(kGameSmoothScrolling, eTypeData::kBool, 183, -1));
	group.AddType(TTypeData(kGameAudioMixLinks, eTypeData::kLinkList, 184, -1));
	group.AddType(TTypeData(kGameAudioContainerLinks, eTypeData::kLinkList, 184, -1));

	group.SetCreate(TTGame::OnCreate);
	group.SetInit(TTGame::OnInit);
}

// Recovered group of TTInterface ("Interface", table 1).
TTypeGroup &TTInterface::GetTypeGroup() {
	static TTypeGroup typeGroup(137, static_cast<eVisionaireTable>(1), static_cast<eSaveGame>(2), 1, -1, 100, -1);
	return typeGroup;
}

void TTInterface::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kInterfaceScrollStepSize, eTypeData::kInt, static_cast<eSaveGame>(2), -1, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceSprite, eTypeData::kSprite, 18, -1));
	group.AddType(TTypeData(kInterfaceButtons, eTypeData::kLinkList, static_cast<eVisionaireTable>(2), 1, -1));
	group.AddType(TTypeData(kInterfaceStandardCommand, eTypeData::kLink, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceOffset, eTypeData::kPoint, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceDisplacement, eTypeData::kInt, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceActionTextFont, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kInterfaceActionTextRect, eTypeData::kRect, 23, -1));
	group.AddType(TTypeData(kInterfaceTextOnScreen, eTypeData::kBool, 40, 99));
	group.AddType(TTypeData(kInterfaceSize, eTypeData::kInt, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceBorder, eTypeData::kPointList, 23, -1));
	group.AddType(TTypeData(kInterfaceLeaveAction, eTypeData::kLink, static_cast<eSaveGame>(0), 40, -1, -1, -1));
	group.AddType(TTypeData(kInterfaceConditions, eTypeData::kLinkList, static_cast<eVisionaireTable>(10), 41, -1));
	group.AddType(TTypeData(kInterfaceValues, eTypeData::kLinkList, static_cast<eVisionaireTable>(20), 41, -1));
	group.AddType(TTypeData(kInterfaceItems, eTypeData::kLinkList, static_cast<eSaveGame>(1), -1, -1, 100, 114));
	group.AddType(TTypeData(kInterfaceItemsScrollPosition, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceActive, eTypeData::kBool, static_cast<eSaveGame>(2), 99, 114, 100, 114));
	group.AddType(TTypeData(kInterfaceVisible, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceDestVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceTimeToDestVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kInterfaceActiveCommand, eTypeData::kLink, static_cast<eSaveGame>(1), 1, -1, -1, -1));
	group.AddType(TTypeData(kInterfaceDrawActionText, eTypeData::kBool, 99, -1));
	group.AddType(TTypeData(kInterfaceInterfaceClass, eTypeData::kLink, static_cast<eSaveGame>(0), 114, -1, -1, -1));
	group.AddType(TTypeData(kInterfacePosition, eTypeData::kPoint, static_cast<eSaveGame>(1), -1, -1, 128, -1));
	group.AddType(TTypeData(kInterfaceShowAlways, eTypeData::kBool, 176, -1));
	group.AddType(TTypeData(kInterfaceMatrixId, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 180, -1));

	group.SetCreate(TTInterface::OnCreate);
	group.SetInit(TTInterface::OnInit);
}

// Recovered group of TTInterfaceClass ("InterfaceClass", table 31).
TTypeGroup &TTInterfaceClass::GetTypeGroup() {
	static TTypeGroup typeGroup(658, static_cast<eVisionaireTable>(31), static_cast<eSaveGame>(0), 114, -1, -1, -1);
	return typeGroup;
}

void TTInterfaceClass::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kInterfaceClassName, eTypeData::kString, static_cast<eSaveGame>(0), 114, -1, -1, -1));

	group.SetCreate(TTInterfaceClass::OnCreate);
	group.SetInit(TTInterfaceClass::OnInit);
}

// Recovered group of TTLanguage ("Language", table 18).
TTypeGroup &TTLanguage::GetTypeGroup() {
	static TTypeGroup typeGroup(261, static_cast<eVisionaireTable>(18), static_cast<eSaveGame>(0), 23, -1, -1, -1);
	return typeGroup;
}

void TTLanguage::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);

	group.SetCreate(TTLanguage::OnCreate);
	group.SetInit(TTLanguage::OnInit);
}

// Recovered group of TTLoading ("Loading", table 21).
TTypeGroup &TTLoading::GetTypeGroup() {
	static TTypeGroup typeGroup(352, static_cast<eVisionaireTable>(21), static_cast<eSaveGame>(0), 26, -1, -1, -1);
	return typeGroup;
}

void TTLoading::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kLoadingMusic, eTypeData::kPath, 1, -1));
	group.AddType(TTypeData(kLoadingSprite, eTypeData::kSprite, 1, -1));
	group.AddType(TTypeData(kLoadingStatusSprite, eTypeData::kSprite, 99, -1));
	group.AddType(TTypeData(kLoadingStatusCover, eTypeData::kBool, 1, -1));

	group.SetCreate(TTLoading::OnCreate);
	group.SetInit(TTLoading::OnInit);
}

// Recovered group of TTModel ("Model", table 35).
TTypeGroup &TTModel::GetTypeGroup() {
	static TTypeGroup typeGroup(705, static_cast<eVisionaireTable>(35), static_cast<eSaveGame>(2), 140, 143, 140, 145);
	return typeGroup;
}

void TTModel::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kModelModel, eTypeData::kPath, 140, -1));
	group.AddType(TTypeData(kModelTextures, eTypeData::kPathList, 140, -1));

	group.SetCreate(TTModel::OnCreate);
	group.SetInit(TTModel::OnInit);
}

// Recovered group of TTObject ("Object", table 6).
TTypeGroup &TTObject::GetTypeGroup() {
	static TTypeGroup typeGroup(163, static_cast<eVisionaireTable>(6), static_cast<eSaveGame>(2), 1, -1, 100, -1);
	return typeGroup;
}

void TTObject::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kObjectName, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kObjectPolygon, eTypeData::kPointList, 25, -1));
	group.AddType(TTypeData(kObjectDirection, eTypeData::kInt, 13, -1));
	group.AddType(TTypeData(kObjectCondition, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kObjectSprite, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kObjectAnimation, eTypeData::kLink, 1, -1));
	group.AddType(TTypeData(kObjectActions, eTypeData::kLinkList, static_cast<eVisionaireTable>(7), 1, -1));
	group.AddType(TTypeData(kObjectSprites, eTypeData::kLinkList, -1, 23));
	group.AddType(TTypeData(kObjectConditions, eTypeData::kLinkList, static_cast<eVisionaireTable>(10), 1, -1));
	group.AddType(TTypeData(kObjectAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 1, -1));
	group.AddType(TTypeData(kObjectCenter, eTypeData::kInt, 24, -1));
	group.AddType(TTypeData(kObjectValues, eTypeData::kLinkList, static_cast<eVisionaireTable>(20), 24, -1));
	group.AddType(TTypeData(kObjectPosition, eTypeData::kPoint, 24, -1));
	group.AddType(TTypeData(kObjectIsItem, eTypeData::kBool, 25, -1));
	group.AddType(TTypeData(kObjectConditionNegate, eTypeData::kBool, 26, -1));
	group.AddType(TTypeData(kObjectIsWalkable, eTypeData::kBool, 38, -1));
	group.AddType(TTypeData(kObjectParticleSystem, eTypeData::kLink, static_cast<eVisionaireTable>(23), 41, -1));
	group.AddType(TTypeData(kObjectScrollFactorX, eTypeData::kInt, 42, -1));
	group.AddType(TTypeData(kObjectScrollFactorY, eTypeData::kInt, 42, -1));
	group.AddType(TTypeData(kObjectVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kObjectDestVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kObjectTimeToDestVisibility, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kObjectSnoopAnimation, eTypeData::kLink, static_cast<eVisionaireTable>(9), 117, -1));
	group.AddType(TTypeData(kObjectSnoopAnimationPos, eTypeData::kPoint, 117, -1));
	group.AddType(TTypeData(kObjectOffset, eTypeData::kPoint, static_cast<eSaveGame>(1), -1, -1, 172, -1));
	group.AddType(TTypeData(kObjectRotation, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 174, -1));
	group.AddType(TTypeData(kObjectRotationCenter, eTypeData::kPoint, static_cast<eSaveGame>(1), -1, -1, 174, -1));
	group.AddType(TTypeData(kObjectShaderSet, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 174, -1));
	group.AddType(TTypeData(kObjectScale, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 174, -1));
	group.AddType(TTypeData(kObjectModel, eTypeData::kPath, 178, -1));
	group.AddType(TTypeData(kObjectMatrixId, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 178, -1));
	group.AddType(TTypeData(kObjectScaleX, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 180, -1));
	group.AddType(TTypeData(kObjectScaleY, eTypeData::kFloat, static_cast<eSaveGame>(1), -1, -1, 180, -1));

	group.SetCreate(TTObject::OnCreate);
	group.SetInit(TTObject::OnInit);
}

// Recovered group of TTOutfit ("Outfit", table 17).
TTypeGroup &TTOutfit::GetTypeGroup() {
	static TTypeGroup typeGroup(266, static_cast<eVisionaireTable>(17), static_cast<eSaveGame>(2), 23, -1, 100, -1);
	return typeGroup;
}

void TTOutfit::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kOutfitWalkAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 1, -1));
	group.AddType(TTypeData(kOutfitTalkAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 1, -1));
	group.AddType(TTypeData(kOutfitRandomAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 1, -1));
	group.AddType(TTypeData(kOutfitCharacterAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 1, -1));
	group.AddType(TTypeData(kOutfitStandingAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 38, -1));
	group.AddType(TTypeData(kOutfitCharacterSpeed, eTypeData::kInt, static_cast<eSaveGame>(2), 1, -1, -1, -1));
	group.AddType(TTypeData(kOutfitModel, eTypeData::kPath, 140, -1));
	group.AddType(TTypeData(kOutfitCameraDistance, eTypeData::kFloat, 140, 142));
	group.AddType(TTypeData(kOutfitCameraHeight, eTypeData::kInt, static_cast<eSaveGame>(2), 140, -1, 144, -1));
	group.AddType(TTypeData(kOutfitCameraAngle, eTypeData::kInt, static_cast<eSaveGame>(2), 140, -1, 144, -1));
	group.AddType(TTypeData(kOutfitUseLight, eTypeData::kBool, static_cast<eSaveGame>(2), 140, -1, 144, -1));
	group.AddType(TTypeData(kOutfitLightPosX, eTypeData::kFloat, static_cast<eSaveGame>(2), 140, -1, 144, -1));
	group.AddType(TTypeData(kOutfitLightPosY, eTypeData::kFloat, static_cast<eSaveGame>(2), 140, -1, 144, -1));
	group.AddType(TTypeData(kOutfitLightPosZ, eTypeData::kFloat, static_cast<eSaveGame>(2), 140, -1, 144, -1));
	group.AddType(TTypeData(kOutfitLightColor, eTypeData::kInt, static_cast<eSaveGame>(2), 140, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelScaleFactor, eTypeData::kInt, static_cast<eSaveGame>(2), 142, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelShowShadow, eTypeData::kBool, static_cast<eSaveGame>(2), 142, 160, 144, 160));
	group.AddType(TTypeData(kOutfitModelShadowTranslucency, eTypeData::kInt, static_cast<eSaveGame>(2), 142, 160, 144, 160));
	group.AddType(TTypeData(kOutfitModelUseToonShading, eTypeData::kBool, static_cast<eSaveGame>(2), 142, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelToonNuances, eTypeData::kInt, static_cast<eSaveGame>(2), 142, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelShowOutline, eTypeData::kBool, static_cast<eSaveGame>(2), 142, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelOutlineColor, eTypeData::kInt, static_cast<eSaveGame>(2), 142, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelOutlineWidth, eTypeData::kInt, static_cast<eSaveGame>(2), 142, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelTextures, eTypeData::kPathList, 143, -1));
	group.AddType(TTypeData(kOutfitAmbientLightColor, eTypeData::kInt, static_cast<eSaveGame>(2), 144, -1, 144, -1));
	group.AddType(TTypeData(kOutfitModelShadowVisibility, eTypeData::kInt, static_cast<eSaveGame>(2), 160, -1, 160, -1));
	group.AddType(TTypeData(kOutfitWalkCycleCurve, eTypeData::kFloatList, 161, 162));
	group.AddType(TTypeData(kOutfitWalkCyclePoints, eTypeData::kIntList, 161, 162));
	group.AddType(TTypeData(kOutfitRandomMinTime, eTypeData::kInt, 163, -1));
	group.AddType(TTypeData(kOutfitRandomMaxTime, eTypeData::kInt, 163, -1));
	group.AddType(TTypeData(kOutfitModelShadow, eTypeData::kInt, 160, -1));
	group.AddType(TTypeData(kOutfitModelAmbientOcclusion, eTypeData::kInt, 160, -1));
	group.AddType(TTypeData(kOutfitSlideWalkAnimation, eTypeData::kBool, 168, -1));
	group.AddType(TTypeData(kOutfitModelFiles, eTypeData::kPathList, 180, -1));
	group.AddType(TTypeData(kOutfitTurnAnimations, eTypeData::kLinkList, static_cast<eVisionaireTable>(9), 180, -1));

	group.SetCreate(TTOutfit::OnCreate);
	group.SetInit(TTOutfit::OnInit);
}

// Recovered group of TTParticleContainer ("ParticleContainer", table 23).
TTypeGroup &TTParticleContainer::GetTypeGroup() {
	static TTypeGroup typeGroup(450, static_cast<eVisionaireTable>(23), static_cast<eSaveGame>(0), 41, -1, -1, -1);
	return typeGroup;
}

void TTParticleContainer::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kParticleContainerParticles, eTypeData::kLinkList, static_cast<eVisionaireTable>(22), 1, -1));
	group.AddType(TTypeData(kParticleContainerCameraZPosition, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleContainerCameraZoom, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleContainerLeadTime, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleContainerSettings, eTypeData::kString, 180, -1));
	group.AddType(TTypeData(kParticleContainerPreviewScene, eTypeData::kLink, 181, -1));

	group.SetCreate(TTParticleContainer::OnCreate);
	group.SetInit(TTParticleContainer::OnInit);
}

// Recovered group of TTParticles ("Particle", table 22).
TTypeGroup &TTParticles::GetTypeGroup() {
	static TTypeGroup typeGroup(391, static_cast<eVisionaireTable>(22), static_cast<eSaveGame>(0), 41, -1, -1, -1);
	return typeGroup;
}

void TTParticles::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kParticleTexture, eTypeData::kPath, 41, -1));
	group.AddType(TTypeData(kParticleMaterialMode, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleTilesX, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleTilesY, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleType, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleXPos, eTypeData::kFloat, 41, 152));
	group.AddType(TTypeData(kParticleYPos, eTypeData::kFloat, 41, 152));
	group.AddType(TTypeData(kParticleEmitterType, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleEmitterWidth, eTypeData::kFloat, 41, 157));
	group.AddType(TTypeData(kParticleEmitterHeight, eTypeData::kFloat, 41, 157));
	group.AddType(TTypeData(kParticleEmitterDepth, eTypeData::kFloat, 41, 157));
	group.AddType(TTypeData(kParticleMaxParticles, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticlePerTime, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticlePhiX, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticlePhiY, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleMinSize, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleMaxSize, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleMinVelocity, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleMaxVelocity, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleMinLife, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleMaxLife, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleMinColor, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleMaxColor, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleRotationX, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleRotationZ, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleActiveStages, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleBlendColor0, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleBlendColor1, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleBlendColor2, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleBlendColor3, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleBlendColorCurve0, eTypeData::kFloatList, 41, -1));
	group.AddType(TTypeData(kParticleBlendColorCurve1, eTypeData::kFloatList, 41, -1));
	group.AddType(TTypeData(kParticleBlendColorCurve2, eTypeData::kFloatList, 41, -1));
	group.AddType(TTypeData(kParticleBlendColorCurve3, eTypeData::kFloatList, 41, -1));
	group.AddType(TTypeData(kParticleColorControlPoints0, eTypeData::kIntList, 41, -1));
	group.AddType(TTypeData(kParticleColorControlPoints1, eTypeData::kIntList, 41, -1));
	group.AddType(TTypeData(kParticleColorControlPoints2, eTypeData::kIntList, 41, -1));
	group.AddType(TTypeData(kParticleColorControlPoints3, eTypeData::kIntList, 41, -1));
	group.AddType(TTypeData(kParticleForceType, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleForceStrength, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleForceRotationX, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleForceRotationZ, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleForceXPos, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleForceYPos, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleForceZPos, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleForceBlend, eTypeData::kFloat, 41, -1));
	group.AddType(TTypeData(kParticleBlendSizeCurve, eTypeData::kFloatList, 41, -1));
	group.AddType(TTypeData(kParticleSizeControlPoints, eTypeData::kIntList, 41, -1));
	group.AddType(TTypeData(kParticleBlendMaxTile, eTypeData::kInt, 41, -1));
	group.AddType(TTypeData(kParticleBlendTilesCurve, eTypeData::kFloatList, 41, -1));
	group.AddType(TTypeData(kParticleBlendTilesControlPoints, eTypeData::kIntList, 41, -1));
	group.AddType(TTypeData(kParticlePosX, eTypeData::kInt, 152, -1));
	group.AddType(TTypeData(kParticlePosY, eTypeData::kInt, 152, -1));
	group.AddType(TTypeData(kParticleEmitterSizeX, eTypeData::kInt, 157, -1));
	group.AddType(TTypeData(kParticleEmitterSizeY, eTypeData::kInt, 157, -1));
	group.AddType(TTypeData(kParticleEmitterSizeZ, eTypeData::kInt, 157, -1));

	group.SetCreate(TTParticles::OnCreate);
	group.SetInit(TTParticles::OnInit);
}

// Recovered group of TTPoint ("Point", table 5).
TTypeGroup &TTPoint::GetTypeGroup() {
	static TTypeGroup typeGroup(144, static_cast<eVisionaireTable>(5), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTPoint::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kPointSize, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kPointPosition, eTypeData::kPoint, 1, -1));
	group.AddType(TTypeData(kPointRelations, eTypeData::kLinkList, static_cast<eVisionaireTable>(5), 1, -1));

	group.SetCreate(TTPoint::OnCreate);
	group.SetInit(TTPoint::OnInit);
}

// Recovered group of TTScene ("Scene", table 4).
TTypeGroup &TTScene::GetTypeGroup() {
	static TTypeGroup typeGroup(129, static_cast<eVisionaireTable>(4), static_cast<eSaveGame>(2), 1, -1, 43, -1);
	return typeGroup;
}

void TTScene::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kSceneSprite, eTypeData::kSprite, 18, -1));
	group.AddType(TTypeData(kSceneName, eTypeData::kLink, 28, -1));
	group.AddType(TTypeData(kSceneBackgroundMusic, eTypeData::kPath, static_cast<eSaveGame>(2), 1, -1, 43, -1));
	group.AddType(TTypeData(kSceneContinueMusic, eTypeData::kBool, 29, -1));
	group.AddType(TTypeData(kCDTrack, eTypeData::kInt, 1, -1));
	group.AddType(TTypeData(kSceneMusicVolume, eTypeData::kInt, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kSceneMusicBalance, eTypeData::kInt, static_cast<eSaveGame>(2), 23, -1, 100, -1));
	group.AddType(TTypeData(kSceneObjects, eTypeData::kLinkList, static_cast<eVisionaireTable>(6), 1, -1));
	group.AddType(TTypeData(kSceneScrollOnEdges, eTypeData::kBool, static_cast<eSaveGame>(2), 17, -1, 100, -1));
	group.AddType(TTypeData(kSceneIsMenu, eTypeData::kBool, 23, -1));
	group.AddType(TTypeData(kSceneCursor, eTypeData::kLink, 23, -1));
	group.AddType(TTypeData(kSceneSavegameAreas, eTypeData::kRectList, 23, -1));
	group.AddType(TTypeData(kSceneSavegameScrollStep, eTypeData::kInt, 23, -1));
	group.AddType(TTypeData(kSceneValues, eTypeData::kLinkList, static_cast<eVisionaireTable>(20), 24, -1));
	group.AddType(TTypeData(kSceneConditions, eTypeData::kLinkList, static_cast<eVisionaireTable>(10), 24, -1));
	group.AddType(TTypeData(kSceneActions, eTypeData::kLinkList, static_cast<eVisionaireTable>(7), 24, -1));
	group.AddType(TTypeData(kSceneSavegameFont, eTypeData::kLink, static_cast<eVisionaireTable>(3), 25, -1));
	group.AddType(TTypeData(kSceneParticleSystem, eTypeData::kLink, static_cast<eVisionaireTable>(23), 41, -1));
	group.AddType(TTypeData(kSceneLightMap, eTypeData::kPath, static_cast<eSaveGame>(2), 46, -1, 46, -1));
	group.AddType(TTypeData(kSceneScrollableArea, eTypeData::kRect, static_cast<eSaveGame>(2), 54, -1, 54, -1));
	group.AddType(TTypeData(kSceneBrightness, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 100, -1));
	group.AddType(TTypeData(kSceneWaySystems, eTypeData::kLinkList, static_cast<eVisionaireTable>(29), 99, -1));
	group.AddType(TTypeData(kSceneCurrentWaySystem, eTypeData::kLink, static_cast<eSaveGame>(2), 99, -1, 99, -1));
	group.AddType(TTypeData(kSceneActionAreas, eTypeData::kLinkList, static_cast<eVisionaireTable>(32), 120, -1));
	group.AddType(TTypeData(kSceneSavegameScreenshot, eTypeData::kPath, 170, -1));
	group.AddType(TTypeData(kSceneShaderSet, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 179, -1));
	group.AddType(TTypeData(kSceneAudioBusses, eTypeData::kLinkList, 184, -1));

	group.SetCreate(TTScene::OnCreate);
	group.SetInit(TTScene::OnInit);
}

// Recovered group of TTScript ("Script", table 30).
TTypeGroup &TTScript::GetTypeGroup() {
	static TTypeGroup typeGroup(650, static_cast<eVisionaireTable>(30), static_cast<eSaveGame>(0), 100, -1, -1, -1);
	return typeGroup;
}

void TTScript::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kScriptScript, eTypeData::kString, 1, -1));
	group.AddType(TTypeData(kScriptType, eTypeData::kInt, 1, -1));

	group.SetCreate(TTScript::OnCreate);
	group.SetInit(TTScript::OnInit);
}

// Recovered group of TTScriptVariable ("ScriptVariable", table 30).
TTypeGroup &TTScriptVariable::GetTypeGroup() {
	static TTypeGroup typeGroup(693, static_cast<eVisionaireTable>(30), static_cast<eSaveGame>(1), -1, -1, 133, -1);
	return typeGroup;
}

void TTScriptVariable::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kScriptVariableValueType, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 133, -1));
	group.AddType(TTypeData(kScriptVariableKeyType, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 133, -1));
	group.AddType(TTypeData(kScriptVariableValue, eTypeData::kString, static_cast<eSaveGame>(1), -1, -1, 133, -1));
	group.AddType(TTypeData(kScriptVariableIsGlobalVar, eTypeData::kBool, static_cast<eSaveGame>(1), -1, -1, 133, -1));
	group.AddType(TTypeData(kScriptVariableItems, eTypeData::kLinkList, static_cast<eSaveGame>(1), -1, -1, 133, -1));

	group.SetCreate(TTScriptVariable::OnCreate);
	group.SetInit(TTScriptVariable::OnInit);
}

// Recovered group of TTShader ("Shader", table 36).
TTypeGroup &TTShader::GetTypeGroup() {
	static TTypeGroup typeGroup(817, static_cast<eVisionaireTable>(36), 181, -1);
	return typeGroup;
}

void TTShader::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kShaderFS, eTypeData::kString, 181, -1));
	group.AddType(TTypeData(kShaderVS, eTypeData::kString, 181, -1));
	group.AddType(TTypeData(kShaderCompiled, eTypeData::kString, 181, -1));

	group.SetCreate(TTShader::OnCreate);
	group.SetInit(TTShader::OnInit);
}

// Recovered group of TTSprite ("Sprite", table 13).
TTypeGroup &TTSprite::GetTypeGroup() {
	static TTypeGroup typeGroup(207, static_cast<eVisionaireTable>(13), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTSprite::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kSpriteSprite, eTypeData::kSprite, 18, -1));

	group.SetCreate(TTSprite::OnCreate);
	group.SetInit(TTSprite::OnInit);
}

// Recovered group of TTText ("Text", table 14).
TTypeGroup &TTText::GetTypeGroup() {
	static TTypeGroup typeGroup(209, static_cast<eVisionaireTable>(14), static_cast<eSaveGame>(0), -1, -1, -1, -1);
	return typeGroup;
}

void TTText::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kTextAll, eTypeData::kLinkList, 23, 167));
	group.AddType(TTypeData(kTextTextLanguages, eTypeData::kTextList, 167, -1));

	group.SetCreate(TTText::OnCreate);
	group.SetInit(TTText::OnInit);
	group.SetNameInList(TTText::GetNameInList);
}

// Recovered group of TTTextLanguage ("TextLanguage", table 19).
TTypeGroup &TTTextLanguage::GetTypeGroup() {
	static TTypeGroup typeGroup(255, static_cast<eVisionaireTable>(19), static_cast<eSaveGame>(0), 23, 165, -1, -1);
	return typeGroup;
}

void TTTextLanguage::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kTextLanguageText, eTypeData::kString, 1, -1));
	group.AddType(TTypeData(kTextLanguageSound, eTypeData::kPath, 1, -1));
	group.AddType(TTypeData(kTextLanguageLanguage, eTypeData::kLink, 1, -1));

	group.SetCreate(TTTextLanguage::OnCreate);
	group.SetInit(TTTextLanguage::OnInit);
}

// Recovered group of TTValue ("Value", table 20).
TTypeGroup &TTValue::GetTypeGroup() {
	static TTypeGroup typeGroup(327, static_cast<eVisionaireTable>(20), 24, -1);
	return typeGroup;
}

void TTValue::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kValueInt, eTypeData::kInt, static_cast<eSaveGame>(2), 1, -1, 43, -1));
	group.AddType(TTypeData(kValueRandom, eTypeData::kBool, 25, -1));
	group.AddType(TTypeData(kValueRandomMin, eTypeData::kInt, 25, -1));
	group.AddType(TTypeData(kValueRandomMax, eTypeData::kInt, 25, -1));
	group.AddType(TTypeData(kValueString, eTypeData::kString, static_cast<eSaveGame>(2), 100, -1, 100, -1));
	group.AddType(TTypeData(kValueCurrent, eTypeData::kInt, static_cast<eSaveGame>(1), -1, -1, 37, 43));
	group.AddType(TTypeData(kValueFloat, eTypeData::kFloat, static_cast<eSaveGame>(2), 184, -1, 184, -1));

	group.SetCreate(TTValue::OnCreate);
	group.SetInit(TTValue::OnInit);
}

// Recovered group of TTWaySystem ("WaySystem", table 29).
TTypeGroup &TTWaySystem::GetTypeGroup() {
	static TTypeGroup typeGroup(637, static_cast<eVisionaireTable>(29), static_cast<eSaveGame>(0), 99, -1, -1, -1);
	return typeGroup;
}

void TTWaySystem::InitType(int versionLow, int versionHigh) {
	TTypeGroup &group = GetTypeGroup();

	group.ClearTypes(versionLow, versionHigh);
	group.AddType(TTypeData(kWaySystemBorder, eTypeData::kPointList, 1, -1));
	group.AddType(TTypeData(kWaySystemPoints, eTypeData::kLinkList, static_cast<eVisionaireTable>(5), 1, -1));

	group.SetCreate(TTWaySystem::OnCreate);
	group.SetInit(TTWaySystem::OnInit);
}

// Builds every record type for the given file-version range, in the order the
// binary's TVisionaireGame::InitWithVersion() does it.
void InitRecordTypes(int versionLow, int versionHigh) {
	TSAction::InitType(versionLow, versionHigh);
	TSAnimation::InitType(versionLow, versionHigh);
	TSText::InitType(versionLow, versionHigh);
	TTAction::InitType(versionLow, versionHigh);
	TTActionArea::InitType(versionLow, versionHigh);
	TTActionPart::InitType(versionLow, versionHigh);
	TTAnimation::InitType(versionLow, versionHigh);
	TTAnimationFrame::InitType(versionLow, versionHigh);
	TTAreaAction::InitType(versionLow, versionHigh);
	TTAudioBus::InitType(versionLow, versionHigh);
	TTButton::InitType(versionLow, versionHigh);
	TTCharacter::InitType(versionLow, versionHigh);
	TTClipboardObject::InitType(versionLow, versionHigh);
	TTCommentSet::InitType(versionLow, versionHigh);
	TTCommentSetEntry::InitType(versionLow, versionHigh);
	TTCondition::InitType(versionLow, versionHigh);
	TTCursor::InitType(versionLow, versionHigh);
	TTDialog::InitType(versionLow, versionHigh);
	TTDialogPart::InitType(versionLow, versionHigh);
	TTEvent::InitType(versionLow, versionHigh);
	TTFont::InitType(versionLow, versionHigh);
	TTGame::InitType(versionLow, versionHigh);
	TTInterface::InitType(versionLow, versionHigh);
	TTInterfaceClass::InitType(versionLow, versionHigh);
	TTLanguage::InitType(versionLow, versionHigh);
	TTLoading::InitType(versionLow, versionHigh);
	TTModel::InitType(versionLow, versionHigh);
	TTObject::InitType(versionLow, versionHigh);
	TTOutfit::InitType(versionLow, versionHigh);
	TTParticleContainer::InitType(versionLow, versionHigh);
	TTParticles::InitType(versionLow, versionHigh);
	TTPoint::InitType(versionLow, versionHigh);
	TTScene::InitType(versionLow, versionHigh);
	TTScript::InitType(versionLow, versionHigh);
	TTScriptVariable::InitType(versionLow, versionHigh);
	TTShader::InitType(versionLow, versionHigh);
	TTSprite::InitType(versionLow, versionHigh);
	TTText::InitType(versionLow, versionHigh);
	TTTextLanguage::InitType(versionLow, versionHigh);
	TTValue::InitType(versionLow, versionHigh);
	TTWaySystem::InitType(versionLow, versionHigh);
}
