// Generated by tools/gen_callbacks.py from the binary's OnCreate()/OnInit() default-value
// callbacks - do not edit the generated statements; the functions marked FIXME were not
// fully translatable and are finished by hand in vstables/recordCallbacksManual.cpp.

#include "vstables/records.h"

#include "TSText.h"
#include "TTAction.h"
#include "TTButton.h"
#include "TTScene.h"
#include "TTText.h"
#include "datastruct/visionaire.h"
#include "datastruct/visionaireobject.h"
#include "vstables/fieldIds.h"

void TSAction::OnCreate(TVisionaireObject *object) {
	object->SetValue(kActionActionPartIndex, -1, TSendEventEnum::kNoEvent);
	object->SetValue(kActionContinueWaitForEndIfElse, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kActionTimerStarted, false, TSendEventEnum::kNoEvent);
}

void TSAction::OnInit(TVisionaireObject *object) {
}

void TSAnimation::OnCreate(TVisionaireObject *object) {
	object->SetValue(kPlayOppositeDirection, false, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationCurrentSpriteIndex, -1, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationPreloaded, false, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationActive, false, TSendEventEnum::kNoEvent);
	object->SetValue(kFrameCount, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationSize, 0.0f, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationWaitingTime, 0, TSendEventEnum::kNoEvent);
}

void TSAnimation::OnInit(TVisionaireObject *object) {
}

// Confirmed (asm lines 1454169-1454176): a new active text is not active.
void TSText::OnCreate(TVisionaireObject *object) {
	object->SetValue(kTextActive, false, TSendEventEnum::kNoEvent);
}

void TSText::OnInit(TVisionaireObject *object) {
}

void TTAction::OnInit(TVisionaireObject *object) {
}

void TTActionArea::OnCreate(TVisionaireObject *object) {
}

void TTActionArea::OnInit(TVisionaireObject *object) {
}

void TTActionPart::OnCreate(TVisionaireObject *object) {
	object->SetValue(kActionPartCommand, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kActionPartAltInt, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kActionPartAltInt2, 0, TSendEventEnum::kNoEvent);
}

void TTActionPart::OnInit(TVisionaireObject *object) {
}

void TTAnimation::OnCreate(TVisionaireObject *object) {
	object->SetValue(kAnimationPosition, wxPoint{0, 0}, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationPause, 20, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationNumberOfLoops, 1, TSendEventEnum::kNoEvent);
	object->SetValue(kAnimationReplay, 0, TSendEventEnum::kNoEvent);
}

void TTAnimation::OnInit(TVisionaireObject *object) {
}

void TTAnimationFrame::OnCreate(TVisionaireObject *object) {
	object->SetValue(kAnimationFrameSoundVolume, 100, TSendEventEnum::kSendEvent);
}

void TTAnimationFrame::OnInit(TVisionaireObject *object) {
}

void TTAreaAction::OnInit(TVisionaireObject *object) {
}

void TTAudioBus::OnCreate(TVisionaireObject *object) {
}

void TTAudioBus::OnInit(TVisionaireObject *object) {
}

void TTButton::OnCreate(TVisionaireObject *object) {
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kButtonName);
	}
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kButtonConjunction);
	}
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(13, parent, kButtonActiveSprite);
	}
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(13, parent, kButtonInactiveSprite);
	}
	object->SetValue(kButtonType, 3, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonCommandType, 0, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonUse, 2, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonDraggable, false, TSendEventEnum::kSendEvent);
}

void TTButton::OnInit(TVisionaireObject *object) {
	object->SetValue(kButtonRotation, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonRotationCenter, wxPoint{-1, -1}, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonShaderSet, -1, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonScale, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonScaleX, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonScaleY, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kButtonMatrixId, 1, TSendEventEnum::kSendEvent);
}

void TTCharacter::OnInit(TVisionaireObject *object) {
	object->SetValue(kCharacterActive, true, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterAnimIndex, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterVisibility, 100, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterDestVisibility, 100, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterTimeToDestVisibility, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterDirection, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterFollowReachDistance, -1, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterTint, -1, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterSize, 0.0f, TSendEventEnum::kNoEvent);
	object->SetValue(kCharacterMatrixId, 1, TSendEventEnum::kSendEvent);
	object->SetValue(kCharacterShaderSet, -1, TSendEventEnum::kSendEvent);
}

void TTCommentSet::OnCreate(TVisionaireObject *object) {
}

void TTCommentSet::OnInit(TVisionaireObject *object) {
}

void TTCommentSetEntry::OnCreate(TVisionaireObject *object) {
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kCommentSetEntryText);
	}
}

void TTCommentSetEntry::OnInit(TVisionaireObject *object) {
}

void TTCondition::OnCreate(TVisionaireObject *object) {
	object->SetValue(kConditionIsVariable, true, TSendEventEnum::kSendEvent);
}

void TTCondition::OnInit(TVisionaireObject *object) {
}

void TTCursor::OnCreate(TVisionaireObject *object) {
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(9, parent, kCursorActiveAnimation);
	}
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(9, parent, kCursorInactiveAnimation);
	}
}

void TTCursor::OnInit(TVisionaireObject *object) {
}

void TTDialog::OnCreate(TVisionaireObject *object) {
}

void TTDialog::OnInit(TVisionaireObject *object) {
}

void TTDialogPart::OnCreate(TVisionaireObject *object) {
	object->SetValue(kDialogPartReturn, 0, TSendEventEnum::kSendEvent);
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kDialogPartText);
	}
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kDialogPartAnswerText);
	}
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kDialogPartAltText);
	}
}

void TTDialogPart::OnInit(TVisionaireObject *object) {
}

void TTEvent::OnCreate(TVisionaireObject *object) {
}

void TTEvent::OnInit(TVisionaireObject *object) {
}

void TTFont::OnCreate(TVisionaireObject *object) {
	object->SetValue(kFontTrueTypeFont, false, TSendEventEnum::kSendEvent);
	object->SetValue(kFontSize, 12.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kFontColor, 16777215, TSendEventEnum::kSendEvent);
	object->SetValue(kFontBorder, true, TSendEventEnum::kSendEvent);
	object->SetValue(kFontBorderColor, 0, TSendEventEnum::kSendEvent);
	object->SetValue(kFontBorderSize, 2.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kFontShadow, true, TSendEventEnum::kSendEvent);
	object->SetValue(kFontShadowOffset, wxPoint{1, 1}, TSendEventEnum::kSendEvent);
	object->SetValue(kFontAlphabet, wxString(L"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"), TSendEventEnum::kSendEvent);
	object->SetValue(kFontLetterSpacing, -4, TSendEventEnum::kSendEvent);
	object->SetValue(kVerticalLetterSpacing, 3, TSendEventEnum::kSendEvent);
	object->SetValue(kFontSpaceWidth, 10, TSendEventEnum::kSendEvent);
	object->SetValue(kFontAutoLineBreak, false, TSendEventEnum::kSendEvent);
	object->SetValue(kFontLineWidth, 100, TSendEventEnum::kSendEvent);
}

void TTFont::OnInit(TVisionaireObject *object) {
}

void TTGame::OnInit(TVisionaireObject *object) {
	object->SetValue(kGameTextOutput, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kGameObjectTextOutput, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kGameHideCursor, false, TSendEventEnum::kNoEvent);
	object->SetValue(kGameHideInterfaces, false, TSendEventEnum::kNoEvent);
	object->SetValue(kGameQuake, false, TSendEventEnum::kNoEvent);
	object->SetValue(kGameTextSpeed, 100, TSendEventEnum::kNoEvent);
	object->SetValue(kGameVideoSubtitlePosition, wxPoint{-1, -1}, TSendEventEnum::kNoEvent);
	object->SetValue(kGameShaderExclude, 0, TSendEventEnum::kNoEvent);
}

void TTInterface::OnInit(TVisionaireObject *object) {
	object->SetValue(kInterfaceVisible, true, TSendEventEnum::kNoEvent);
	object->SetValue(kInterfaceVisibility, 100, TSendEventEnum::kNoEvent);
	object->SetValue(kInterfaceDestVisibility, 100, TSendEventEnum::kNoEvent);
	object->SetValue(kInterfaceTimeToDestVisibility, 0, TSendEventEnum::kNoEvent);
	object->SetValue(kInterfaceItemsScrollPosition, 0, TSendEventEnum::kNoEvent);
}

void TTInterfaceClass::OnCreate(TVisionaireObject *object) {
}

void TTInterfaceClass::OnInit(TVisionaireObject *object) {
}

void TTLanguage::OnCreate(TVisionaireObject *object) {
}

void TTLanguage::OnInit(TVisionaireObject *object) {
}

void TTLoading::OnCreate(TVisionaireObject *object) {
}

void TTLoading::OnInit(TVisionaireObject *object) {
}

void TTModel::OnCreate(TVisionaireObject *object) {
}

void TTModel::OnInit(TVisionaireObject *object) {
}

void TTObject::OnCreate(TVisionaireObject *object) {
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kObjectName);
	}
	object->SetValue(kObjectScrollFactorX, 100, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectScrollFactorY, 100, TSendEventEnum::kSendEvent);
}

void TTObject::OnInit(TVisionaireObject *object) {
	object->SetValue(kObjectVisibility, 100, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectDestVisibility, 100, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectOffset, wxPoint{0, 0}, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectRotation, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectRotationCenter, wxPoint{-1, -1}, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectShaderSet, -1, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectScale, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectScaleX, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectScaleY, 0.0f, TSendEventEnum::kSendEvent);
	object->SetValue(kObjectMatrixId, 1, TSendEventEnum::kSendEvent);
}

void TTOutfit::OnInit(TVisionaireObject *object) {
}

void TTParticleContainer::OnCreate(TVisionaireObject *object) {
	object->SetValue(kParticleContainerLeadTime, 0, TSendEventEnum::kSendEvent);
	object->SetValue(kParticleContainerCameraZPosition, -3.0f, TSendEventEnum::kSendEvent);
}

void TTParticleContainer::OnInit(TVisionaireObject *object) {
}

void TTParticles::OnInit(TVisionaireObject *object) {
}

void TTPoint::OnCreate(TVisionaireObject *object) {
}

void TTPoint::OnInit(TVisionaireObject *object) {
}

void TTScene::OnCreate(TVisionaireObject *object) {
	{
		TVisObjRef parent(object);
		object->GetVisionaire()->CreateObject(14, parent, kSceneName);
	}
	object->SetValue(kSceneScrollOnEdges, false, TSendEventEnum::kSendEvent);
	object->SetValue(kSceneMusicVolume, 100, TSendEventEnum::kSendEvent);
	object->SetValue(kSceneMusicBalance, 0, TSendEventEnum::kSendEvent);
	object->SetValue(kSceneSavegameScrollStep, 1, TSendEventEnum::kSendEvent);
}

void TTScene::OnInit(TVisionaireObject *object) {
	object->SetValue(kSceneBrightness, 100, TSendEventEnum::kSendEvent);
}

void TTScript::OnCreate(TVisionaireObject *object) {
}

void TTScript::OnInit(TVisionaireObject *object) {
}

void TTScriptVariable::OnCreate(TVisionaireObject *object) {
}

void TTScriptVariable::OnInit(TVisionaireObject *object) {
}

void TTShader::OnCreate(TVisionaireObject *object) {
	object->SetValue(kShaderFS, wxString(L"?"), TSendEventEnum::kNoEvent);
	object->SetValue(kShaderVS, wxString(L"?"), TSendEventEnum::kNoEvent);
}

void TTShader::OnInit(TVisionaireObject *object) {
}

void TTSprite::OnCreate(TVisionaireObject *object) {
}

void TTSprite::OnInit(TVisionaireObject *object) {
}

void TTText::OnCreate(TVisionaireObject *object) {
}

void TTText::OnInit(TVisionaireObject *object) {
}

void TTTextLanguage::OnCreate(TVisionaireObject *object) {
}

void TTTextLanguage::OnInit(TVisionaireObject *object) {
}

void TTValue::OnCreate(TVisionaireObject *object) {
}

void TTValue::OnInit(TVisionaireObject *object) {
}

void TTWaySystem::OnCreate(TVisionaireObject *object) {
}

void TTWaySystem::OnInit(TVisionaireObject *object) {
}
