#!/usr/bin/env python3
"""
Regenerates src/engine/tests/test_field_offsets.c from
reversing/scripts/apply_structs.py's own SAFE_DECLS block -- every
"TYPE name; // +0xNN ..." field-level comment in there becomes an
offsetof() static assertion here, checked against the real compiler's
own layout of ags/*.h (see src/PLAN.md's "Step 0" and
ags/types.h's own byte-packing note for why this exists).

Run from the repo root:
    python3 src/engine/tools/generate_field_offset_tests.py

Safe to re-run any time apply_structs.py's own field list grows -- it
fully regenerates the output file rather than patching it. If a struct
gets fields added/renamed/re-offset upstream in apply_structs.py, this
script will emit new assertions for the new evidence; whether the
CORRESPONDING ags/*.h header needs a matching edit is a manual review
step (this script only ever reads apply_structs.py, never writes to
ags/*.h itself).
"""
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
APPLY_STRUCTS = REPO_ROOT / "reversing" / "scripts" / "apply_structs.py"
OUT_FILE = REPO_ROOT / "src" / "engine" / "tests" / "test_field_offsets.c"


def extract_safe_decls_lines():
    with open(APPLY_STRUCTS, encoding="utf-8") as f:
        lines = f.readlines()
    # SAFE_DECLS = r"""  ...content...  """
    start = None
    for i, line in enumerate(lines):
        if line.strip() == 'SAFE_DECLS = r"""':
            start = i + 1
            break
    if start is None:
        raise RuntimeError("Could not find SAFE_DECLS start in apply_structs.py")
    end = None
    for i in range(start, len(lines)):
        if lines[i].strip() == '"""':
            end = i
            break
    if end is None:
        raise RuntimeError("Could not find SAFE_DECLS end in apply_structs.py")
    return lines[start:end]


def parse_field_offsets(content_lines):
    current_struct = None
    entries = []
    for line in content_lines:
        s = line.strip()
        if s.startswith("struct ") and s.endswith("{"):
            m = re.match(r"struct\s+(\w+)\s*\{", s)
            if m:
                current_struct = m.group(1)
            continue
        if s == "};" or s.startswith("};"):
            current_struct = None
            continue
        if current_struct is None or s.startswith("//") or s == "":
            continue
        m = re.match(r"^([A-Za-z_][\w \*\[\]0-9,]*?)\s*;\s*//\s*\+0x([0-9A-Fa-f]+)", s)
        if not m:
            continue
        decl, off = m.groups()
        if "," in decl.split("[")[0]:
            # multi-name declarations (e.g. "int x, y, x2, y2") -- skip,
            # not individually offset-commented anyway.
            continue
        dm = re.match(r"^.*[\s\*](\w+)(\[[^\]]*\])*$", decl.strip())
        if not dm:
            continue
        entries.append((current_struct, dm.group(1), off))
    return entries


def main():
    entries = parse_field_offsets(extract_safe_decls_lines())

    out_lines = [
        "/* AUTO-GENERATED by src/engine/tools/generate_field_offset_tests.py",
        " * from reversing/scripts/apply_structs.py -- verifies every ags/*.h",
        " * field lands at its documented offset, using the real compiler's",
        " * own offsetof() rather than a hand-written model. Do not hand-edit;",
        " * re-run the generator instead.",
        " */",
        '#include "ags/all.h"',
        "#include <stddef.h>",
        "",
    ]
    for struct, field, off in entries:
        out_lines.append(
            f'AGS_STATIC_ASSERT(offsetof(struct {struct}, {field}) == 0x{off}, '
            f'"{struct}.{field} must be at +0x{off}");'
        )
    out_lines.append("")
    out_lines.append("int main(void) { return 0; }")
    out_lines.append("END_OF_MAIN()")
    out_lines.append("")

    OUT_FILE.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {len(entries)} field-offset assertions to {OUT_FILE}")


if __name__ == "__main__":
    main()
