"""
Writes docs23/messages.md: which function of the game code refers to which text string of the executable's data segment (offset and length only --
the text itself is copyrighted and is read from the player's executable at run time, see src23/exedata.c).

IDA has no cross-references for these strings (16-bit code loads them with immediates such as `mov bx, 7DA5h`), so this scans the exported disassembly
for immediates that point at the start of a printable NUL-terminated string in the data segment and attributes them to the enclosing procedure.

    python messages_doc.py <repo root>
"""
import re
import sys
from collections import defaultdict

GAMES = [
    ("Chapter 2", "yendor2/yendor2.asm", "yendor2/game/SW.EXE", 0x21660),
    ("Chapter 3", "yendor3/yendor3.asm", "yendor3/game/REGISTER.EXE", 0x21DB0),
]

PROC = re.compile(r"^(\w+)\s+proc\b")
IMM = re.compile(r"^\s+(?:mov|lea|push|cmp)\s+(?:bx|ax|dx|si|di|cx),\s*(?:offset\s+)?([0-9A-F]{3,4})h\b", re.I)
IMM_PTR = re.compile(r"ds:([0-9A-F]{4})h", re.I)


def string_at(data, base, offset):
    """Length of the printable string starting at the DS offset, or 0."""
    o = base + offset
    if o <= 0 or o >= len(data):
        return 0
    if o > 0 and data[o - 1] != 0 and not (32 <= data[o - 1] < 127):
        return 0
    end = o
    while end < len(data) and data[end] != 0 and end - o < 400:
        if not (32 <= data[end] < 127):
            return 0
        end += 1
    length = end - o
    if length < 3 or data[end:end + 1] != b"\0":
        return 0
    letters = sum(1 for c in data[o:end] if chr(c).isalpha())
    return length if letters * 2 >= length else 0


def scan(root, name, asm_path, exe_path, base):
    exe = open(root + "/" + exe_path, "rb").read()
    uses = defaultdict(lambda: defaultdict(set))  # function -> offset -> {length}
    func = None
    for line in open(root + "/" + asm_path, encoding="latin-1"):
        m = PROC.match(line)
        if m:
            func = m.group(1)
            continue
        if not func:
            continue
        for rx in (IMM,):
            m = rx.match(line)
            if m:
                off = int(m.group(1), 16)
                if off >= 0x4000:
                    length = string_at(exe, base, off)
                    if length:
                        uses[func][off].add(length)
    return uses


def main(root):
    out = [
        "# Message strings by function",
        "",
        "Generated by `src23/tools/messages_doc.py` from the exported disassembly and the executables: for every procedure, the data-segment offsets of the text",
        "strings it loads (`exedata.h`: file offset = `0x21660 + offset` in Chapter 2's `SW.EXE`, `0x21DB0 + offset` in Chapter 3's `REGISTER.EXE`) and their",
        "length. The text is not reproduced. A string can appear under several functions; an immediate that merely equals a string's address is possible but rare.",
        "",
    ]
    for name, asm, exe, base in GAMES:
        uses = scan(root, name, asm, exe, base)
        total = sum(len(v) for v in uses.values())
        out += ["## %s: %d strings in %d procedures" % (name, total, len(uses)), "", "| procedure | strings (offset:length) |", "|---|---|"]
        for func in sorted(uses):
            items = ["%04X:%d" % (off, min(uses[func][off])) for off in sorted(uses[func])]
            out.append("| `%s` | %s |" % (func, " ".join(items)))
        out.append("")
    open(root + "/docs23/messages.md", "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("written")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
