"""
Writes docs23/sound-events.md: every call of TriggerSoundEvent in the game code, grouped by procedure, with the sound event id loaded just before it
(a literal, one of the constants InitGlobals stores -- Chapter 2's `_valNN`, Chapter 3's raw `ds:` words -- or a field read from a record such as a
monster's own sound at +0x5C). The ids index the effect list of WORLD.DAT (audio.h: 221 VOC samples).

    python sound_events_doc.py <repo root>
"""
import re
import sys
from collections import defaultdict

GAMES = [("Chapter 2", "yendor2/yendor2.asm"), ("Chapter 3", "yendor3/yendor3.asm")]
PROC = re.compile(r"^(\w+)\s+proc\b")
MOV_AX = re.compile(r"^\s+mov\s+ax,\s*(.+?)\s*(?:;.*)?$")
INIT_V2 = re.compile(r"^\s+mov\s+(\w+),\s*([0-9A-F]+h|\d+)\b", re.I)
INIT_V3 = re.compile(r"^\s+mov\s+word ptr ds:([0-9A-F]+)h,\s*([0-9A-F]+h|\d+)\b", re.I)


def number(text):
    text = text.strip().rstrip(";").split()[0]
    return int(text[:-1], 16) if text.lower().endswith("h") else int(text)


def init_globals(lines):
    values = {}
    inside = False
    for line in lines:
        if re.match(r"^InitGlobals\s+proc", line):
            inside = True
            continue
        if inside and re.match(r"^InitGlobals\s+endp", line):
            break
        if inside:
            m = INIT_V2.match(line)
            if m:
                values[m.group(1)] = number(m.group(2))
            m = INIT_V3.match(line)
            if m:
                values["ds:%sh" % m.group(1).upper().lstrip("0")] = number(m.group(2))
    return values


def describe(source, values):
    source = source.strip()
    if re.fullmatch(r"[0-9A-F]+h|\d+", source, re.I):
        return "%d" % number(source)
    if source in values:
        return "%d (%s)" % (values[source], source)
    m = re.match(r"ds:([0-9A-F]+)h", source, re.I)
    if m:
        key = "ds:%sh" % m.group(1).upper().lstrip("0")
        if key in values:
            return "%d (%s)" % (values[key], key)
    return "from `%s`" % source


def main(root):
    out = [
        "# Sound events by procedure",
        "",
        "Generated by `src23/tools/sound_events_doc.py`: each `TriggerSoundEvent` call of the game code with the id loaded into `ax` just before it (an index into the",
        "effect list of `WORLD.DAT`, `audio.h`). A number in brackets names the `InitGlobals` constant it came from; `from ...` is a value read at run time (a record field).",
        "",
    ]
    for name, path in GAMES:
        lines = open(root + "/" + path, encoding="latin-1").read().split("\n")
        values = init_globals(lines)
        uses = defaultdict(list)
        func = None
        for i, line in enumerate(lines):
            m = PROC.match(line)
            if m:
                func = m.group(1)
            if func and re.match(r"^\s+call\s+TriggerSoundEvent\b", line) and func != "TriggerSoundEvent":
                for back in range(1, 6):
                    m = MOV_AX.match(lines[i - back])
                    if m:
                        uses[func].append(describe(m.group(1), values))
                        break
                else:
                    uses[func].append("(ax set earlier)")
        total = sum(len(v) for v in uses.values())
        out += ["## %s: %d calls in %d procedures" % (name, total, len(uses)), "", "| procedure | sound ids |", "|---|---|"]
        for func in sorted(uses):
            out.append("| `%s` | %s |" % (func, ", ".join(uses[func])))
        out.append("")
    open(root + "/docs23/sound-events.md", "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("written")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
