;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-337F-7354-97                      |
; |                       Paul Gilbert, ScummVM Team                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 0D547AFED1224E3CED46969DAB8F8D57527E2C2EA7D42D715EA5955D5C2AC8D0
; Input MD5    : 243A3F865017401308B5070F0A48BBCC
; Input CRC32  : AFEC2BD5

; ---------------------------------------------------------------------------
; File Name   : C:\dev\might_and_magic\mm2\drv\CGA.DRV
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 0C73h Loaded length: 0C73h

                .686p
                .mmx
                .model flat

; ===========================================================================

; Segment type: Pure code
drv             segment byte public 'CODE' use16
                assume cs:drv
                assume es:nothing, ss:nothing, ds:nothing, fs:nothing, gs:nothing

entry_00:
                jmp     near ptr drv_fn00_reset
; ---------------------------------------------------------------------------

entry_01:
                jmp     near ptr drv_fn01_select_page
; ---------------------------------------------------------------------------

entry_02:
                jmp     near ptr drv_fn02_set_color
; ---------------------------------------------------------------------------

entry_03:
                jmp     near ptr drv_fn03_plot_point
; ---------------------------------------------------------------------------

entry_04:
                jmp     near ptr drv_fn04_hline
; ---------------------------------------------------------------------------

entry_05:
                jmp     near ptr drv_fn05_vline
; ---------------------------------------------------------------------------

entry_06:
                jmp     near ptr drv_fn06_line
; ---------------------------------------------------------------------------

entry_07:
                jmp     near ptr drv_fn07_get_pixel
; ---------------------------------------------------------------------------

entry_08:
                jmp     near ptr drv_fn08_copy_rect_pages
; ---------------------------------------------------------------------------

entry_09:
                jmp     near ptr drv_fn09_copy_page
; ---------------------------------------------------------------------------

entry_0A:
                jmp     near ptr drv_fn0A_page_op
; ---------------------------------------------------------------------------

entry_0B:
                jmp     near ptr drv_fn0B_save_rect
; ---------------------------------------------------------------------------

entry_0C:
                jmp     near ptr drv_fn0C_restore_rect
; ---------------------------------------------------------------------------

entry_0D:
                jmp     near ptr drv_fn0D_scroll_rect_a
; ---------------------------------------------------------------------------

entry_0E:
                jmp     drv_fn0E_scroll_rect_b
; ---------------------------------------------------------------------------

entry_0F:
                jmp     near ptr drv_fn12_draw_op12
; ---------------------------------------------------------------------------

entry_10:
                jmp     near ptr drv_fn10_load_image
; ---------------------------------------------------------------------------

entry_11:
                jmp     near ptr drv_fn14_draw_image_alt
; ---------------------------------------------------------------------------

entry_12:
                jmp     near ptr drv_fn12_draw_op12
; ---------------------------------------------------------------------------

entry_13:
                jmp     near ptr drv_fn13_draw_image
; ---------------------------------------------------------------------------

entry_14:
                jmp     near ptr drv_fn14_draw_image_alt
; ---------------------------------------------------------------------------

entry_15:                               ; DATA XREF: drv_fn00_reset+3↓r
                                        ; drv_fn00_reset+A↓r ...
                jmp     near ptr drv_fn15_put_char
; ---------------------------------------------------------------------------

entry_16:
                jmp     near ptr drv_fn16_monster_setup
; ---------------------------------------------------------------------------

entry_17:
                jmp     near ptr drv_fn17_monster_draw
; ---------------------------------------------------------------------------
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
unk_84          db    0                 ; DATA XREF: sub_256+4↓r
                                        ; sub_256+F↓r ...
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db 0FCh
                db 0F0h
                db 0C0h
                db    0
                db  3Fh ; ?
                db  0Fh
                db    3
                db  3Fh ; ?
                db 0CFh
                db 0F3h
                db 0FCh
                db 0C0h
                db  30h ; 0
                db  0Ch
                db    3
                db    0
                db    3
                db  0Ch
                db  0Fh
                db  30h ; 0
                db  33h ; 3
                db  3Ch ; <
                db  3Fh ; ?
                db 0C0h
                db 0C3h
                db 0CCh
                db 0CFh
                db 0F0h
                db 0F3h
                db 0FCh
                db 0FFh
word_248        dw 0                    ; DATA XREF: drv_fn01_select_page+11↓w
word_24A        dw 0B800h               ; DATA XREF: sub_34C+3↓r
                                        ; drv_fn07_get_pixel↓r ...
word_24C        dw 0BC00h               ; DATA XREF: drv_fn00_reset+1E↓w
                                        ; drv_fn00_reset+23↓r ...
word_24E        dw 0                    ; DATA XREF: drv_fn03_plot_point+2↓w
                                        ; drv_fn03_plot_point+C↓w ...
byte_250        db 0                    ; DATA XREF: drv_fn02_set_color+2B↓w
byte_251        db 0                    ; DATA XREF: drv_fn02_set_color+20↓w
byte_252        db 0                    ; DATA XREF: drv_fn02_set_color+15↓w
byte_253        db 0                    ; DATA XREF: drv_fn02_set_color+A↓w
byte_254        db 0                    ; DATA XREF: drv_fn02_set_color↓w
                                        ; drv_fn02_set_color+E↓w ...
                db    0

; =============== S U B R O U T I N E =======================================


sub_256         proc near               ; CODE XREF: drv_fn00_reset+1B↓p
                                        ; drv_fn16_monster_setup:loc_A32↓p
                push    ds
                push    bx
                mov     ah, 30h
                int     21h             ; DOS - GET DOS VERSION
                                        ; Return: AL = major version number (00h for DOS 1.x)
                cmp     al, 3
                jz      short loc_283
                mov     bx, 0FFFFh
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     ax
                push    ax
                inc     ax
                sub     bx, ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                push    ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                push    ax
                pushf
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                jmp     short loc_29C
; ---------------------------------------------------------------------------

loc_283:                                ; CODE XREF: sub_256+8↑j
                mov     al, 1
                mov     bx, 2
                mov     ah, 58h
                int     21h             ; DOS - 3+ - GET/SET MEMORY ALLOCATION STRATEGY
                                        ; AL = function code: set allocation strategy
                pop     bx
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                push    ax
                pushf
                mov     al, 1
                mov     bx, 0
                mov     ah, 58h
                int     21h             ; DOS - 3+ - GET/SET MEMORY ALLOCATION STRATEGY
                                        ; AL = function code: set allocation strategy

loc_29C:                                ; CODE XREF: sub_256+2B↑j
                popf
                pop     bx
                jnb     short loc_2A5
                call    sub_A03
; ---------------------------------------------------------------------------
                xor     bx, bx

loc_2A5:                                ; CODE XREF: sub_256+48↑j
                pop     ds
                retn
sub_256         endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn00_reset  proc far                ; CODE XREF: drv:entry_00↑j
                mov     ax, 4
                int     10h             ; - VIDEO - SET VIDEO MODE
                                        ; AL = mode
                mov     bx, 0
                mov     ah, 0Bh
                int     10h             ; - VIDEO - SET COLOR PALETTE
                                        ; BH = 00h, BL = border color
                                        ; BH = 01h, BL = palette (0-3)
                mov     bx, 101h
                mov     ah, 0Bh
                int     10h             ; - VIDEO - SET COLOR PALETTE
                                        ; BH = 00h, BL = border color
                                        ; BH = 01h, BL = palette (0-3)
                mov     ax, 500h
                int     10h             ; - VIDEO - SELECT DISPLAY PAGE
                                        ; AL = display page, 0-7  for modes 0 & 1, 0-3  for modes 2 & 3
                mov     bx, 400h
                call    sub_256
                mov     cs:word_24C, bx
                mov     es, cs:word_24C
                xor     di, di
                xor     ax, ax
                mov     cx, 1000h
                rep stosw
                push    cs
                pop     ds
                mov     cx, 0C7h
                mov     di, 1D6h

loc_2E1:                                ; CODE XREF: drv_fn00_reset+56↓j
                mov     ax, cx
                mov     ah, al
                and     ax, 1FEh
                shl     ax, 1
                shl     ax, 1
                shl     ax, 1
                mov     dx, ax
                and     dh, 7
                shl     ax, 1
                shl     ax, 1
                add     dx, ax
                mov     [di], dx
                sub     di, 2
                loop    loc_2E1
                retf
drv_fn00_reset  endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn02_set_color proc far             ; CODE XREF: drv:entry_02↑j
                mov     cs:byte_254, 0
                mov     cl, 2
                and     al, 3
                mov     cs:byte_253, al
                or      cs:byte_254, al
                shl     al, cl
                mov     cs:byte_252, al
                or      cs:byte_254, al
                shl     al, cl
                mov     cs:byte_251, al
                or      cs:byte_254, al
                shl     al, cl
                mov     cs:byte_250, al
                or      cs:byte_254, al
                retf
drv_fn02_set_color endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn03_plot_point proc far            ; CODE XREF: drv:entry_03↑j
                jnb     short loc_341
                mov     cs:word_24E, 1

loc_341:                                ; CODE XREF: drv_fn03_plot_point↑j
                call    sub_34C
                mov     cs:word_24E, 0
                retf
drv_fn03_plot_point endp


; =============== S U B R O U T I N E =======================================


sub_34C         proc near               ; CODE XREF: drv_fn03_plot_point:loc_341↑p
                                        ; drv_fn06_line+62↓p
                push    ax
                push    bx
                push    cx
                mov     es, cs:word_24A
                shl     bx, 1
                mov     bx, cs:[bx+48h]
                mov     si, ax
                mov     cl, 2
                shr     ax, cl
                add     bx, ax
                mov     al, es:[bx]
                and     si, 3
                cmp     cs:word_24E, 0
                jnz     short loc_37D
                and     al, cs:[si+230h]
                or      al, cs:[si+250h]
                jmp     short loc_382
; ---------------------------------------------------------------------------

loc_37D:                                ; CODE XREF: sub_34C+23↑j
                xor     al, cs:[si+250h]

loc_382:                                ; CODE XREF: sub_34C+2F↑j
                mov     es:[bx], al
                pop     cx
                pop     bx
                pop     ax
                retn
sub_34C         endp

; ---------------------------------------------------------------------------
                db  90h
                db    6
                db    4
                db    2
                db    0

; =============== S U B R O U T I N E =======================================


drv_fn07_get_pixel proc far             ; CODE XREF: drv:entry_07↑j
                mov     es, cs:word_24A
                shl     bx, 1
                mov     bx, cs:[bx+48h]
                mov     si, ax
                mov     cl, 2
                shr     ax, cl
                add     bx, ax
                mov     al, es:[bx]
                and     si, 3
                and     al, cs:[si+234h]
                mov     cl, cs:[si+38Ah]
                shr     al, cl
                xor     ah, ah
                retf
drv_fn07_get_pixel endp

; ---------------------------------------------------------------------------
                db  90h
byte_3B8        db 0                    ; DATA XREF: sub_3BA+35↓w
                                        ; sub_3BA+58↓w ...
byte_3B9        db 0                    ; DATA XREF: sub_3BA+47↓w
                                        ; sub_3BA+54↓r ...

; =============== S U B R O U T I N E =======================================


sub_3BA         proc near               ; CODE XREF: drv_fn04_hline:loc_427↓p
                                        ; drv_fn08_copy_rect_pages+1A↓p ...
                shl     bx, 1
                mov     bx, cs:[bx+48h]
                mov     si, ax
                mov     di, cx
                mov     cl, 2
                push    di
                shr     si, cl
                shr     di, cl
                cmp     si, di
                pop     di
                pushf
                mov     si, ax
                shr     ax, cl
                add     bx, ax
                mov     dx, di
                sub     dx, si
                inc     dx
                and     si, 3
                mov     ax, 4
                sub     ax, si
                and     ax, 3
                sub     dx, ax
                mov     si, ax
                mov     al, cs:[si+228h]
                mov     cs:byte_3B8, al
                and     di, 3
                inc     di
                and     di, 3
                sub     dx, di
                mov     al, cs:[di+22Ch]
                mov     cs:byte_3B9, al
                shr     dx, cl
                mov     cx, dx
                popf
                jnz     short locret_41D
                xor     cx, cx
                mov     al, cs:byte_3B9
                and     cs:byte_3B8, al
                mov     cs:byte_3B9, 0

locret_41D:                             ; CODE XREF: sub_3BA+50↑j
                retn
sub_3BA         endp


; =============== S U B R O U T I N E =======================================


drv_fn04_hline  proc far                ; CODE XREF: drv:entry_04↑j
                jnb     short loc_427
                mov     cs:word_24E, 1

loc_427:                                ; CODE XREF: drv_fn04_hline↑j
                call    sub_3BA
                mov     es, cs:word_24A
                mov     di, bx
                mov     ah, cs:byte_3B8
                or      ah, ah
                jz      short loc_456
                mov     dl, es:[di]
                mov     al, cs:byte_254
                and     dl, ah
                not     ah
                and     al, ah
                cmp     cs:word_24E, 0
                jz      short loc_453
                xor     al, dl
                jmp     short loc_455
; ---------------------------------------------------------------------------

loc_453:                                ; CODE XREF: drv_fn04_hline+2F↑j
                or      al, dl

loc_455:                                ; CODE XREF: drv_fn04_hline+33↑j
                stosb

loc_456:                                ; CODE XREF: drv_fn04_hline+1A↑j
                jcxz    short loc_477
                mov     al, cs:byte_254
                mov     ah, al
                cmp     cs:word_24E, 0
                jz      short loc_470

loc_466:                                ; CODE XREF: drv_fn04_hline+4E↓j
                mov     al, es:[di]
                xor     al, ah
                stosb
                loop    loc_466
                jmp     short loc_477
; ---------------------------------------------------------------------------

loc_470:                                ; CODE XREF: drv_fn04_hline+46↑j
                shr     cx, 1
                rep stosw
                jnb     short loc_477
                stosb

loc_477:                                ; CODE XREF: drv_fn04_hline:loc_456↑j
                                        ; drv_fn04_hline+50↑j ...
                mov     ah, cs:byte_3B9
                or      ah, ah
                jz      short loc_49C
                mov     dl, es:[di]
                mov     al, cs:byte_254
                and     dl, ah
                not     ah
                and     al, ah
                cmp     cs:word_24E, 0
                jz      short loc_499
                xor     al, dl
                jmp     short loc_49B
; ---------------------------------------------------------------------------

loc_499:                                ; CODE XREF: drv_fn04_hline+75↑j
                or      al, dl

loc_49B:                                ; CODE XREF: drv_fn04_hline+79↑j
                stosb

loc_49C:                                ; CODE XREF: drv_fn04_hline+60↑j
                mov     cs:word_24E, 0
                retf
drv_fn04_hline  endp


; =============== S U B R O U T I N E =======================================


drv_fn05_vline  proc far                ; CODE XREF: drv:entry_05↑j
                jnb     short loc_4AD
                mov     cs:word_24E, 1

loc_4AD:                                ; CODE XREF: drv_fn05_vline↑j
                mov     es, cs:word_24A
                mov     si, ax
                shr     ax, 1
                shr     ax, 1
                and     si, 3
                sub     cx, bx
                inc     cx

loc_4BE:                                ; CODE XREF: drv_fn05_vline+36↓j
                mov     di, bx
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, ax
                mov     dl, es:[di]
                and     dl, cs:[si+230h]
                or      dl, cs:[si+250h]
                mov     es:[di], dl
                inc     bx
                loop    loc_4BE
                mov     cs:word_24E, 0
                retf
drv_fn05_vline  endp

; ---------------------------------------------------------------------------
word_4E4        dw 0                    ; DATA XREF: drv_fn06_line:loc_519↓w
                                        ; drv_fn06_line:loc_56F↓r
word_4E6        dw 0                    ; DATA XREF: drv_fn06_line:loc_50C↓w
                                        ; drv_fn06_line+80↓r
word_4E8        dw 0                    ; DATA XREF: drv_fn06_line+5A↓w
                                        ; drv_fn06_line+85↓r
word_4EA        dw 0                    ; DATA XREF: drv_fn06_line+40↓w
                                        ; drv_fn06_line+6A↓r
word_4EC        dw 0                    ; DATA XREF: drv_fn06_line+45↓w
                                        ; drv_fn06_line+6F↓r
word_4EE        dw 0                    ; DATA XREF: drv_fn06_line+50↓w
                                        ; drv_fn06_line+74↓r
word_4F0        dw 0                    ; DATA XREF: drv_fn06_line:loc_52A↓w
word_4F2        dw 0                    ; DATA XREF: drv_fn06_line+3B↓w
                                        ; drv_fn06_line+4A↓r

; =============== S U B R O U T I N E =======================================


drv_fn06_line   proc far                ; CODE XREF: drv:entry_06↑j
                jnb     short loc_4FD
                mov     cs:word_24E, 1

loc_4FD:                                ; CODE XREF: drv_fn06_line↑j
                mov     si, 1
                mov     di, si
                push    bx
                push    ax
                sub     dx, bx
                jge     short loc_50C
                neg     di
                neg     dx

loc_50C:                                ; CODE XREF: drv_fn06_line+12↑j
                mov     cs:word_4E6, di
                sub     cx, ax
                jge     short loc_519
                neg     si
                neg     cx

loc_519:                                ; CODE XREF: drv_fn06_line+1F↑j
                mov     cs:word_4E4, si
                cmp     cx, dx
                jge     short loc_528
                xor     si, si
                xchg    cx, dx
                jmp     short loc_52A
; ---------------------------------------------------------------------------

loc_528:                                ; CODE XREF: drv_fn06_line+2C↑j
                xor     di, di

loc_52A:                                ; CODE XREF: drv_fn06_line+32↑j
                mov     cs:word_4F0, cx
                mov     cs:word_4F2, dx
                mov     cs:word_4EA, si
                mov     cs:word_4EC, di
                mov     ax, cs:word_4F2
                shl     ax, 1
                mov     cs:word_4EE, ax
                sub     ax, cx
                mov     dx, ax
                sub     ax, cx
                mov     cs:word_4E8, ax
                inc     cx
                pop     ax
                pop     bx

loc_555:                                ; CODE XREF: drv_fn06_line+79↓j
                                        ; drv_fn06_line+8A↓j
                push    dx
                call    sub_34C
                pop     dx
                or      dx, dx
                jns     short loc_56F
                add     ax, cs:word_4EA
                add     bx, cs:word_4EC
                add     dx, cs:word_4EE
                loop    loc_555

loc_56F:                                ; CODE XREF: drv_fn06_line+68↑j
                add     ax, cs:word_4E4
                add     bx, cs:word_4E6
                add     dx, cs:word_4E8
                loop    loc_555
                mov     cs:word_24E, 0
                retf
drv_fn06_line   endp


; =============== S U B R O U T I N E =======================================


drv_fn01_select_page proc far           ; CODE XREF: drv:entry_01↑j
                mov     bx, 0B800h
                or      ax, ax
                jz      short loc_594
                mov     bx, cs:word_24C

loc_594:                                ; CODE XREF: drv_fn01_select_page+5↑j
                mov     cs:word_24A, bx
                mov     cs:word_248, ax
                retf
drv_fn01_select_page endp


; =============== S U B R O U T I N E =======================================


drv_fn0C_restore_rect proc far          ; CODE XREF: drv:entry_0C↑j
                mov     ds, ax
                xor     si, si
                lodsw
                mov     di, ax
                mov     cl, 2
                shr     di, cl
                lodsw
                push    ax
                lodsw
                mov     cx, ax
                lodsw
                mov     dx, ax
                mov     ax, di
                mov     es, cs:word_24A
                pop     bx

loc_5B9:                                ; CODE XREF: drv_fn0C_restore_rect+2C↓j
                mov     di, bx
                inc     bx
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, ax
                push    cx
                rep movsb
                pop     cx
                dec     dx
                jnz     short loc_5B9
                push    es
                mov     bx, ds
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                retf
drv_fn0C_restore_rect endp

; ---------------------------------------------------------------------------
                db  90h
word_5D8        dw 0                    ; DATA XREF: drv_fn0B_save_rect↓w
                                        ; drv_fn0B_save_rect+4B↓r
word_5DA        dw 0                    ; DATA XREF: drv_fn0B_save_rect+4↓w
                                        ; drv_fn0B_save_rect+50↓r
word_5DC        dw 0                    ; DATA XREF: drv_fn0B_save_rect+19↓w
                                        ; drv_fn0B_save_rect+55↓r
word_5DE        dw 0                    ; DATA XREF: drv_fn0B_save_rect+1E↓w
                                        ; drv_fn0B_save_rect+5C↓r

; =============== S U B R O U T I N E =======================================


drv_fn0B_save_rect proc far             ; CODE XREF: drv:entry_0B↑j
                mov     cs:word_5D8, ax
                mov     cs:word_5DA, bx
                mov     si, cx
                mov     cl, 2
                shr     ax, cl
                shr     si, cl
                sub     si, ax
                inc     si
                sub     dx, bx
                mov     cx, dx
                inc     cx
                mov     cs:word_5DC, si
                mov     cs:word_5DE, cx
                mov     di, dx
                push    ax
                mov     ax, si
                cwd
                mul     cx
                add     ax, 8
                shr     ax, 1
                shr     ax, 1
                shr     ax, 1
                shr     ax, 1
                inc     ax
                push    bx
                mov     bx, ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                jb      short loc_657
                mov     es, ax
                mov     ds, cs:word_24A
                pop     dx
                xor     di, di
                mov     ax, cs:word_5D8
                stosw
                mov     ax, cs:word_5DA
                stosw
                mov     ax, cs:word_5DC
                mov     cx, ax
                stosw
                mov     ax, cs:word_5DE
                stosw

loc_641:                                ; CODE XREF: drv_fn0B_save_rect+72↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+48h]
                add     si, dx
                push    cx
                rep movsb
                pop     cx
                inc     bx
                dec     ax
                jnz     short loc_641
                mov     ax, es
                push    ax

loc_657:                                ; CODE XREF: drv_fn0B_save_rect+3F↑j
                pop     ax
                retf
drv_fn0B_save_rect endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn08_copy_rect_pages proc far       ; CODE XREF: drv:entry_08↑j
                or      ax, ax
                mov     ax, 0B800h
                mov     bx, cs:word_24C
                jz      short loc_667
                xchg    ax, bx

loc_667:                                ; CODE XREF: drv_fn08_copy_rect_pages+A↑j
                push    dx
                push    ax
                push    bx
                push    cx
                mov     ax, cx
                mov     bx, dx
                mov     cx, si
                sub     di, dx
                push    di
                call    sub_3BA
                pop     ax
                pop     bx
                pop     es
                pop     ds
                pop     dx
                shr     bx, 1
                shr     bx, 1

loc_680:                                ; CODE XREF: drv_fn08_copy_rect_pages+66↓j
                push    ax
                push    cx
                mov     si, dx
                shl     si, 1
                mov     si, cs:[si+48h]
                add     si, bx
                mov     di, si
                mov     ah, cs:byte_3B8
                or      ah, ah
                jz      short loc_6A4
                lodsb
                and     es:[di], ah
                not     ah
                and     al, ah
                or      es:[di], al
                inc     di

loc_6A4:                                ; CODE XREF: drv_fn08_copy_rect_pages+3C↑j
                jcxz    short loc_6A8
                rep movsb

loc_6A8:                                ; CODE XREF: drv_fn08_copy_rect_pages:loc_6A4↑j
                mov     ah, cs:byte_3B9
                or      ah, ah
                jz      short loc_6BC
                lodsb
                and     es:[di], ah
                not     ah
                and     al, ah
                or      es:[di], al

loc_6BC:                                ; CODE XREF: drv_fn08_copy_rect_pages+55↑j
                inc     dx
                pop     cx
                pop     ax
                dec     ax
                jns     short loc_680
                retf
drv_fn08_copy_rect_pages endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn09_copy_page proc far             ; CODE XREF: drv:entry_09↑j
                mov     si, 0B800h
                mov     di, cs:word_24C
                or      ax, ax
                jz      short loc_6D2
                xchg    si, di

loc_6D2:                                ; CODE XREF: drv_fn09_copy_page+A↑j
                mov     ds, si
                mov     es, di
                xor     bx, bx

loc_6D8:                                ; CODE XREF: drv_fn09_copy_page+29↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+48h]
                mov     di, si
                mov     cx, 28h ; '('
                rep movsw
                inc     bx
                cmp     bx, 0C8h
                jl      short loc_6D8
                retf
drv_fn09_copy_page endp


; =============== S U B R O U T I N E =======================================


drv_fn0A_page_op proc far               ; CODE XREF: drv:entry_0A↑j
                mov     si, 0B800h
                mov     di, cs:word_24C
                or      ax, ax
                jz      short loc_6FE
                xchg    si, di

loc_6FE:                                ; CODE XREF: drv_fn0A_page_op+A↑j
                mov     ds, si
                mov     es, di
                xor     bx, bx

loc_704:                                ; CODE XREF: drv_fn0A_page_op+31↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+48h]
                mov     di, si
                mov     cx, 28h ; '('

loc_712:                                ; CODE XREF: drv_fn0A_page_op+2A↓j
                lodsw
                mov     dx, es:[di]
                stosw
                mov     [si-2], dx
                loop    loc_712
                inc     bx
                cmp     bx, 0C8h
                jl      short loc_704
                retf
drv_fn0A_page_op endp

; ---------------------------------------------------------------------------
word_724        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b↓w
                                        ; drv_fn0E_scroll_rect_b+46↓r ...
word_726        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b+36↓r
word_728        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b:loc_73E↓w
                                        ; drv_fn0E_scroll_rect_b:loc_769↓r ...

; =============== S U B R O U T I N E =======================================


drv_fn0E_scroll_rect_b proc near        ; CODE XREF: drv:entry_0E↑j
                mov     cs:word_724, si
                push    si
                or      si, si
                js      short loc_73A
                mov     di, dx
                sub     di, si
                jmp     short loc_73E
; ---------------------------------------------------------------------------

loc_73A:                                ; CODE XREF: drv_fn0E_scroll_rect_b+8↑j
                mov     di, bx
                sub     di, si

loc_73E:                                ; CODE XREF: drv_fn0E_scroll_rect_b+E↑j
                mov     cs:word_728, di
                sub     dx, bx
                pop     di
                mov     bp, di
                or      di, di
                jns     short loc_74E
                neg     di

loc_74E:                                ; CODE XREF: drv_fn0E_scroll_rect_b+20↑j
                sub     dx, di
                inc     dx
                push    dx
                call    sub_3BA
                pop     dx
                mov     ds, cs:word_24A
                mov     es, cs:word_24A
                mov     bx, cs:word_726
                shr     bx, 1
                shr     bx, 1

loc_769:                                ; CODE XREF: drv_fn0E_scroll_rect_b+A3↓j
                mov     si, cs:word_728
                mov     di, si
                add     di, cs:word_724
                cmp     di, 0C8h
                jnb     short loc_7B8
                shl     si, 1
                shl     di, 1
                mov     si, cs:[si+48h]
                mov     di, cs:[di+48h]
                add     si, bx
                add     di, bx
                push    cx
                mov     ah, cs:byte_3B8
                or      ah, ah
                jz      short loc_7A1
                lodsb
                and     [di], ah
                not     ah
                and     al, ah
                or      [di], al
                inc     di

loc_7A1:                                ; CODE XREF: drv_fn0E_scroll_rect_b+6B↑j
                jcxz    short loc_7A5
                rep movsb

loc_7A5:                                ; CODE XREF: drv_fn0E_scroll_rect_b:loc_7A1↑j
                mov     ah, cs:byte_3B9
                or      ah, ah
                jz      short loc_7B7
                lodsb
                and     [di], ah
                not     ah
                and     al, ah
                or      [di], al

loc_7B7:                                ; CODE XREF: drv_fn0E_scroll_rect_b+82↑j
                pop     cx

loc_7B8:                                ; CODE XREF: drv_fn0E_scroll_rect_b+4F↑j
                inc     cs:word_728
                test    cs:word_724, 8000h
                js      short loc_7CC
                sub     cs:word_728, 2

loc_7CC:                                ; CODE XREF: drv_fn0E_scroll_rect_b+9A↑j
                dec     dx
                jnz     short loc_769
drv_fn0E_scroll_rect_b endp

; [00000001 BYTES: COLLAPSED FUNCTION drv_fn0D_scroll_rect_a. PRESS NUMPAD+ TO EXPAND]
                db    0
                db  55h ; U
                db 0AAh
                db 0FFh
byte_7D4        db 0                    ; DATA XREF: drv_fn15_put_char+13↓w
                                        ; drv_fn15_put_char+64↓r ...
byte_7D5        db 0                    ; DATA XREF: drv_fn15_put_char+23↓w
                                        ; drv_fn15_put_char+BE↓r ...
byte_7D6        db 0                    ; DATA XREF: drv_fn15_put_char+28↓w
                                        ; drv_fn15_put_char+39↓w ...
                db    0

; =============== S U B R O U T I N E =======================================


drv_fn15_put_char proc far              ; CODE XREF: drv:entry_15↑j
                jnb     short loc_7E1
                mov     cs:word_24E, 1

loc_7E1:                                ; CODE XREF: drv_fn15_put_char↑j
                cmp     dh, 0FFh
                jnz     short loc_7E8
                inc     dh

loc_7E8:                                ; CODE XREF: drv_fn15_put_char+C↑j
                and     dl, 3
                mov     cs:byte_7D4, ah
                push    es
                pop     ds
                xor     bh, bh
                mov     bl, dl
                mov     dl, cs:[bx+7D0h]
                mov     cs:byte_7D5, dl
                mov     cs:byte_7D6, dh
                cmp     dh, 0FFh
                jz      short loc_816
                mov     bl, dh
                mov     dl, cs:[bx+7D0h]
                mov     cs:byte_7D6, dl

loc_816:                                ; CODE XREF: drv_fn15_put_char+30↑j
                mov     dl, ch
                xor     dh, dh
                mov     di, dx
                mov     bl, al
                mov     si, bx
                mov     dl, cl
                xor     dh, dh
                shl     dx, 1
                mov     cl, 3
                shl     si, cl
                shl     di, cl
                mov     es, cs:word_24A
                push    word ptr [si]
                push    word ptr [si+2]
                push    word ptr [si+4]
                push    word ptr [si+6]
                test    cs:byte_7D4, 4
                jz      short loc_848
                mov     byte ptr [si+7], 0FFh

loc_848:                                ; CODE XREF: drv_fn15_put_char+6A↑j
                test    cs:byte_7D4, 8
                jz      short loc_85B
                not     word ptr [si]
                not     word ptr [si+2]
                not     word ptr [si+4]
                not     word ptr [si+6]

loc_85B:                                ; CODE XREF: drv_fn15_put_char+76↑j
                mov     cx, 8
                mov     bx, di

loc_860:                                ; CODE XREF: drv_fn15_put_char+E4↓j
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, dx
                mov     al, cs:byte_7D6
                cmp     al, 0FFh
                jz      short loc_876
                mov     ah, al
                mov     es:[di], ax

loc_876:                                ; CODE XREF: drv_fn15_put_char+97↑j
                lodsb
                or      al, al
                jz      short loc_8B9
                push    bx
                mov     bl, al
                and     bx, 0F0h
                shr     bl, 1
                shr     bl, 1
                shr     bl, 1
                shr     bl, 1
                mov     bl, cs:[bx+238h]
                not     bl
                and     es:[di], bl
                not     bl
                and     bl, cs:byte_7D5
                or      es:[di], bl
                inc     di
                mov     bl, al
                and     bl, 0Fh
                mov     bl, cs:[bx+238h]
                not     bl
                and     es:[di], bl
                not     bl
                and     bl, cs:byte_7D5
                or      es:[di], bl
                pop     bx

loc_8B9:                                ; CODE XREF: drv_fn15_put_char+A1↑j
                inc     bx
                mov     di, bx
                loop    loc_860
                pop     word ptr [si-2]
                pop     word ptr [si-4]
                pop     word ptr [si-6]
                pop     word ptr [si-8]
                mov     cs:word_24E, 0
                retf
drv_fn15_put_char endp

; ---------------------------------------------------------------------------
                db    0
                db    3
                db  0Fh
                db  3Fh ; ?
word_8D6        dw 0                    ; DATA XREF: drv_fn13_draw_image+19↓w
                                        ; drv_fn13_draw_image+34↓r ...
word_8D8        dw 0                    ; DATA XREF: drv_fn13_draw_image+2F↓w
                                        ; drv_fn13_draw_image+66↓r ...

; =============== S U B R O U T I N E =======================================


drv_fn13_draw_image proc far            ; CODE XREF: drv:entry_13↑j
                mov     cs:byte_3B9, 0
                mov     ds, ax
                mov     es, cs:word_24A
                shl     bx, 1
                shl     bx, 1
                add     bx, 2
                mov     si, [bx]
                mov     bx, [bx+2]
                mov     cs:word_8D6, bx
                mov     di, dx
                shr     cx, 1
                shr     cx, 1
                mov     bx, cx
                lodsw
                mov     cx, ax
                lodsw
                push    cx
                shr     cx, 1
                shr     cx, 1
                mov     cs:word_8D8, cx
                cmp     cs:word_8D6, 0
                pop     cx
                jnz     short loc_92C
                push    bx
                mov     bx, cx
                and     bx, 3
                mov     bl, cs:[bx+8D2h]
                mov     cs:byte_3B9, bl
                or      bl, bl
                pop     bx
                jz      short $+2

loc_92C:                                ; CODE XREF: drv_fn13_draw_image+3B↑j
                                        ; drv_fn13_draw_image+50↑j
                mov     dx, ax
                cmp     cs:word_8D6, 0
                jnz     short loc_95F

loc_936:                                ; CODE XREF: drv_fn13_draw_image+82↓j
                push    di
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, bx
                mov     cx, cs:word_8D8
                rep movsb
                mov     ch, cs:byte_3B9
                or      ch, ch
                jz      short loc_959
                lodsb
                mov     ah, es:[di]
                and     ah, ch
                or      al, ah
                stosb

loc_959:                                ; CODE XREF: drv_fn13_draw_image+74↑j
                pop     di
                inc     di
                dec     dx
                jnz     short loc_936
                retf
; ---------------------------------------------------------------------------

loc_95F:                                ; CODE XREF: drv_fn13_draw_image+5A↑j
                push    bp
                mov     bp, dx

loc_962:                                ; CODE XREF: drv_fn13_draw_image+121↓j
                push    di
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, bx
                mov     cx, cs:word_8D8

loc_971:                                ; CODE XREF: drv_fn13_draw_image+119↓j
                lodsb
                push    si
                mov     si, cs:word_8D6
                mov     ah, [si]
                pop     si
                inc     cs:word_8D6
                mov     dl, es:[di]
                test    ah, 80h
                jz      short loc_98C
                and     al, 3Fh
                jmp     short loc_98F
; ---------------------------------------------------------------------------

loc_98C:                                ; CODE XREF: drv_fn13_draw_image+AC↑j
                and     dl, 3Fh

loc_98F:                                ; CODE XREF: drv_fn13_draw_image+B0↑j
                test    ah, 40h
                jz      short loc_998
                and     al, 0CFh
                jmp     short loc_99B
; ---------------------------------------------------------------------------

loc_998:                                ; CODE XREF: drv_fn13_draw_image+B8↑j
                and     dl, 0CFh

loc_99B:                                ; CODE XREF: drv_fn13_draw_image+BC↑j
                test    ah, 20h
                jz      short loc_9A4
                and     al, 0F3h
                jmp     short loc_9A7
; ---------------------------------------------------------------------------

loc_9A4:                                ; CODE XREF: drv_fn13_draw_image+C4↑j
                and     dl, 0F3h

loc_9A7:                                ; CODE XREF: drv_fn13_draw_image+C8↑j
                test    ah, 10h
                jz      short loc_9B0
                and     al, 0FCh
                jmp     short loc_9B3
; ---------------------------------------------------------------------------

loc_9B0:                                ; CODE XREF: drv_fn13_draw_image+D0↑j
                and     dl, 0FCh

loc_9B3:                                ; CODE XREF: drv_fn13_draw_image+D4↑j
                or      al, dl
                stosb
                dec     cx
                jcxz    short loc_9F6
                lodsb
                mov     dl, es:[di]
                test    ah, 8
                jz      short loc_9C6
                and     al, 3Fh
                jmp     short loc_9C9
; ---------------------------------------------------------------------------

loc_9C6:                                ; CODE XREF: drv_fn13_draw_image+E6↑j
                and     dl, 3Fh

loc_9C9:                                ; CODE XREF: drv_fn13_draw_image+EA↑j
                test    ah, 4
                jz      short loc_9D2
                and     al, 0CFh
                jmp     short loc_9D5
; ---------------------------------------------------------------------------

loc_9D2:                                ; CODE XREF: drv_fn13_draw_image+F2↑j
                and     dl, 0CFh

loc_9D5:                                ; CODE XREF: drv_fn13_draw_image+F6↑j
                test    ah, 2
                jz      short loc_9DE
                and     al, 0F3h
                jmp     short loc_9E1
; ---------------------------------------------------------------------------

loc_9DE:                                ; CODE XREF: drv_fn13_draw_image+FE↑j
                and     dl, 0F3h

loc_9E1:                                ; CODE XREF: drv_fn13_draw_image+102↑j
                test    ah, 1
                jz      short loc_9EA
                and     al, 0FCh
                jmp     short loc_9ED
; ---------------------------------------------------------------------------

loc_9EA:                                ; CODE XREF: drv_fn13_draw_image+10A↑j
                and     dl, 0FCh

loc_9ED:                                ; CODE XREF: drv_fn13_draw_image+10E↑j
                or      al, dl
                stosb
                dec     cx
                jcxz    short loc_9F6
                jmp     loc_971
; ---------------------------------------------------------------------------

loc_9F6:                                ; CODE XREF: drv_fn13_draw_image+DD↑j
                                        ; drv_fn13_draw_image+117↑j
                pop     di
                inc     di
                dec     bp
                jz      short loc_9FE
                jmp     loc_962
; ---------------------------------------------------------------------------

loc_9FE:                                ; CODE XREF: drv_fn13_draw_image+11F↑j
                pop     bp
                retf
drv_fn13_draw_image endp

; [00000001 BYTES: COLLAPSED FUNCTION drv_fn10_load_image. PRESS NUMPAD+ TO EXPAND]
; [00000001 BYTES: COLLAPSED FUNCTION drv_fn12_draw_op12. PRESS NUMPAD+ TO EXPAND]
; [00000001 BYTES: COLLAPSED FUNCTION drv_fn14_draw_image_alt. PRESS NUMPAD+ TO EXPAND]

; =============== S U B R O U T I N E =======================================

; Attributes: noreturn

sub_A03         proc near               ; CODE XREF: sub_256+4A↑p
                                        ; sub_A03↓j
                jmp     short sub_A03
sub_A03         endp

; ---------------------------------------------------------------------------
                db  90h
word_A06        dw 0                    ; DATA XREF: drv_fn16_monster_setup+29↓w
                                        ; drv_fn16_monster_setup+66↓r ...
word_A08        dw 0                    ; DATA XREF: drv_fn16_monster_setup+2↓w
                                        ; drv_fn16_monster_setup+BD↓r
word_A0A        dw 0                    ; DATA XREF: drv_fn16_monster_setup+16↓w

; =============== S U B R O U T I N E =======================================


drv_fn16_monster_setup proc far         ; CODE XREF: drv:entry_16↑j
                push    ds
                pop     es
                mov     cs:word_A08, bx
                mov     ds, ax
                xor     si, si
                lodsw
                mov     di, dx
                mov     dx, si
                stosb
                mov     cx, 900h
                mul     cx
                mov     cs:word_A0A, ax
                mov     bx, ax
                or      ax, ax
                jz      short loc_A32
                dec     bx
                mov     cl, 4
                shr     bx, cl
                inc     bx

loc_A32:                                ; CODE XREF: drv_fn16_monster_setup+1E↑j
                call    sub_256
                mov     cs:word_A06, bx
                push    ds
                mov     bx, 90h
                inc     bx
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                mov     es, ax
                xor     di, di
                mov     ax, di
                mov     cx, 480h
                rep stosw
                mov     ax, 0B800h
                mov     ds, ax
                assume ds:nothing
                mov     si, 20h ; ' '
                xor     di, di

loc_A58:                                ; CODE XREF: drv_fn16_monster_setup+62↓j
                push    si
                shl     si, 1
                mov     si, cs:[si+48h]
                add     si, 10h
                mov     cx, 0Ch
                rep movsw
                pop     si
                inc     si
                cmp     si, 80h
                jnz     short loc_A58
                push    es
                pop     ds
                assume ds:nothing
                mov     es, cs:word_A06
                xor     si, si
                mov     di, si
                mov     cx, 480h
                rep movsw
                push    ds
                pop     es
                pop     ds
                mov     ax, 1
                call    sub_AF2
                push    ds
                push    es
                xor     si, si
                lodsw
                push    ax
                mov     bx, cs:word_A06
                mov     ds, bx
                mov     es, bx
                mov     di, 900h

loc_A9B:                                ; CODE XREF: drv_fn16_monster_setup+99↓j
                dec     ax
                jz      short loc_AA7
                mov     cx, 480h
                xor     si, si
                rep movsw
                jmp     short loc_A9B
; ---------------------------------------------------------------------------

loc_AA7:                                ; CODE XREF: drv_fn16_monster_setup+90↑j
                pop     ax
                pop     es
                pop     ds

loc_AAA:                                ; CODE XREF: drv_fn16_monster_setup+A7↓j
                cmp     ax, 1
                jz      short loc_AB5
                call    sub_AF2
                dec     ax
                jmp     short loc_AAA
; ---------------------------------------------------------------------------

loc_AB5:                                ; CODE XREF: drv_fn16_monster_setup+A1↑j
                push    es
                mov     ax, ss
                mov     es, ax
                xor     si, si
                lodsw
                mov     dx, ax
                lodsw
                inc     dx
                shl     dx, 1
                mov     si, dx
                mov     cx, ax
                sub     cx, si
                mov     di, cs:word_A08
                rep movsb
                pop     bx
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                push    es
                mov     bx, ds
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                retf
drv_fn16_monster_setup endp

; ---------------------------------------------------------------------------
                db    6
                db    4
                db    2
                db    0
byte_AE8        db 0                    ; DATA XREF: sub_AF2+6D↓w
                                        ; sub_AF2+D5↓r
byte_AE9        db 0                    ; DATA XREF: sub_AF2+75↓w
                                        ; sub_AF2+A4↓w
word_AEA        dw 0                    ; DATA XREF: sub_AF2+45↓w
                                        ; sub_AF2+CB↓r ...
word_AEC        dw 0                    ; DATA XREF: sub_AF2+5F↓w
                                        ; sub_AF2+B5↓w ...
word_AEE        dw 0                    ; DATA XREF: sub_AF2+64↓w
                                        ; sub_AF2+BB↓w ...
byte_AF0        db 0                    ; DATA XREF: sub_AF2+3C↓w
                                        ; sub_AF2+AB↓r
byte_AF1        db 0                    ; DATA XREF: sub_AF2+B0↓w
                                        ; sub_AF2+DC↓r ...

; =============== S U B R O U T I N E =======================================


sub_AF2         proc near               ; CODE XREF: drv_fn16_monster_setup+7A↑p
                                        ; drv_fn16_monster_setup+A3↑p
                push    ax
                push    bx
                push    cx
                push    dx
                push    bp
                push    ds
                push    es
                dec     ax
                mov     dx, ax
                shl     ax, 1
                mov     si, ax
                mov     bp, [si+2]
                mov     ax, dx
                xor     dx, dx
                mov     cx, 900h
                mul     cx
                mov     di, ax
                xor     si, si
                mov     dx, ds
                push    es
                pop     ds
                mov     es, cs:word_A06
                push    ds
                mov     ds, dx
                mov     al, ds:[bp+0]
                cbw
                add     ax, 3
                mov     bx, ax
                and     bx, 3
                mov     bl, cs:[bx+0AE4h]
                mov     cs:byte_AF0, bl
                shr     ax, 1
                shr     ax, 1
                mov     cs:word_AEA, ax
                mov     al, ds:[bp+1]
                cbw
                add     ax, 6
                mov     cl, 3
                shl     ax, cl
                add     si, ax
                add     di, ax
                shl     ax, 1
                add     si, ax
                add     di, ax
                mov     cs:word_AEC, si
                mov     cs:word_AEE, di
                mov     al, ds:[bp+2]
                mov     cs:byte_AE8, al
                mov     al, ds:[bp+3]
                mov     cs:byte_AE9, al
                add     bp, 4
                pop     ds
                xor     ah, ah

loc_B71:                                ; CODE XREF: sub_AF2+120↓j
                push    ds
                mov     ds, dx
                mov     al, ds:[bp+0]
                inc     bp
                pop     ds
                mov     cl, al
                and     cx, 0F0h
                shr     cl, 1
                shr     cl, 1
                shr     cl, 1
                shr     cl, 1
                and     al, 0Fh
                or      al, 80h
                cmp     al, 84h
                jnb     short loc_B92
                and     al, 3

loc_B92:                                ; CODE XREF: sub_AF2+9C↑j
                                        ; sub_AF2+11E↓j
                or      ah, ah
                jnz     short loc_BCC
                dec     cs:byte_AE9
                js      short loc_C15
                mov     ah, cs:byte_AF0
                mov     cs:byte_AF1, ah
                add     cs:word_AEC, 18h
                add     cs:word_AEE, 18h
                mov     si, cs:word_AEC
                mov     di, cs:word_AEE
                add     si, cs:word_AEA
                add     di, cs:word_AEA
                mov     ah, cs:byte_AE8

loc_BCC:                                ; CODE XREF: sub_AF2+A2↑j
                mov     bl, cl
                mov     cl, cs:byte_AF1
                test    al, 80h
                jz      short loc_BE1
                mov     ch, [si]
                mov     bh, 3
                shl     bh, cl
                and     ch, bh
                jmp     short loc_BE8
; ---------------------------------------------------------------------------

loc_BE1:                                ; CODE XREF: sub_AF2+E3↑j
                mov     ch, al
                and     ch, 3
                shl     ch, cl

loc_BE8:                                ; CODE XREF: sub_AF2+ED↑j
                mov     bh, 3
                shl     bh, cl
                not     bh
                and     es:[di], bh
                or      es:[di], ch
                mov     cl, bl
                cmp     cs:byte_AF1, 0
                jnz     short loc_C06
                mov     cs:byte_AF1, 8
                inc     si
                inc     di

loc_C06:                                ; CODE XREF: sub_AF2+10A↑j
                sub     cs:byte_AF1, 2
                dec     ah
                dec     cl
                jns     short loc_B92
                jmp     loc_B71
; ---------------------------------------------------------------------------

loc_C15:                                ; CODE XREF: sub_AF2+A9↑j
                pop     es
                pop     ds
                pop     bp
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                retn
sub_AF2         endp


; =============== S U B R O U T I N E =======================================


drv_fn17_monster_draw proc far          ; CODE XREF: drv:entry_17↑j
                cmp     ax, 0FFFFh
                jnz     short loc_C3C
                mov     bx, cs:word_A06
                or      bx, bx
                jz      short loc_C3A
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                mov     cs:word_A06, 0

loc_C3A:                                ; CODE XREF: drv_fn17_monster_draw+C↑j
                jmp     short locret_C72
; ---------------------------------------------------------------------------

loc_C3C:                                ; CODE XREF: drv_fn17_monster_draw+3↑j
                push    bp
                mov     bp, 60h ; '`'
                mov     di, cx
                or      ax, ax
                jz      short loc_C4D
                mov     cx, 900h
                xor     dx, dx
                mul     cx

loc_C4D:                                ; CODE XREF: drv_fn17_monster_draw+27↑j
                mov     ds, cs:word_A06
                mov     si, ax
                mov     ax, 0B800h
                mov     es, ax
                assume es:nothing
                shr     bx, 1
                shr     bx, 1

loc_C5D:                                ; CODE XREF: drv_fn17_monster_draw+52↓j
                push    di
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, bx
                mov     cx, 0Ch
                rep movsw
                pop     di
                inc     di
                dec     bp
                jnz     short loc_C5D
                pop     bp

locret_C72:                             ; CODE XREF: drv_fn17_monster_draw:loc_C3A↑j
                retf
drv_fn17_monster_draw endp

drv             ends


                end
