;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-337F-7354-97                      |
; |                       Paul Gilbert, ScummVM Team                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : CE35578B8B21C1155C96E3C7AC11C51C05DDDD9283121BF2ECF57CD7E9248F0C
; Input MD5    : 931D0D8E25B9E94DB147D9D55A1EE6CA
; Input CRC32  : 459629C1

; ---------------------------------------------------------------------------
; File Name   : C:\dev\might_and_magic\mm2\drv\HGA.DRV
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 0CD3h Loaded length: 0CD3h

                .686p
                .mmx
                .model flat

; ===========================================================================

; Segment type: Pure code
drv             segment byte public 'CODE' use16
                assume cs:drv
                assume es:nothing, ss:nothing, ds:nothing, fs:nothing, gs:nothing

entry_00:
                jmp     near ptr drv_fn00_reset
; ---------------------------------------------------------------------------

entry_01:
                jmp     near ptr drv_fn01_select_page
; ---------------------------------------------------------------------------

entry_02:
                jmp     near ptr drv_fn02_set_color
; ---------------------------------------------------------------------------

entry_03:
                jmp     near ptr drv_fn03_plot_point
; ---------------------------------------------------------------------------

entry_04:
                jmp     near ptr drv_fn04_hline
; ---------------------------------------------------------------------------

entry_05:
                jmp     near ptr drv_fn05_vline
; ---------------------------------------------------------------------------

entry_06:
                jmp     near ptr drv_fn06_line
; ---------------------------------------------------------------------------

entry_07:
                jmp     near ptr drv_fn07_get_pixel
; ---------------------------------------------------------------------------

entry_08:
                jmp     near ptr drv_fn08_copy_rect_pages
; ---------------------------------------------------------------------------

entry_09:
                jmp     near ptr drv_fn09_copy_page
; ---------------------------------------------------------------------------

entry_0A:
                jmp     near ptr drv_fn0A_page_op
; ---------------------------------------------------------------------------

entry_0B:
                jmp     near ptr drv_fn0B_save_rect
; ---------------------------------------------------------------------------

entry_0C:
                jmp     near ptr drv_fn0C_restore_rect
; ---------------------------------------------------------------------------

entry_0D:
                jmp     near ptr drv_fn0D_scroll_rect_a
; ---------------------------------------------------------------------------

entry_0E:
                jmp     drv_fn0E_scroll_rect_b
; ---------------------------------------------------------------------------

entry_0F:
                jmp     near ptr drv_fn12_draw_op12
; ---------------------------------------------------------------------------

entry_10:
                jmp     near ptr drv_fn10_load_image
; ---------------------------------------------------------------------------

entry_11:
                jmp     near ptr drv_fn14_draw_image_alt
; ---------------------------------------------------------------------------

entry_12:
                jmp     near ptr drv_fn12_draw_op12
; ---------------------------------------------------------------------------

entry_13:
                jmp     near ptr drv_fn13_draw_image
; ---------------------------------------------------------------------------

entry_14:
                jmp     near ptr drv_fn14_draw_image_alt
; ---------------------------------------------------------------------------

entry_15:
                jmp     near ptr drv_fn15_put_char
; ---------------------------------------------------------------------------

entry_16:
                jmp     near ptr drv_fn16_monster_setup
; ---------------------------------------------------------------------------

entry_17:
                jmp     near ptr drv_fn17_monster_draw
; ---------------------------------------------------------------------------
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
unk_84          db    0                 ; DATA XREF: sub_256+3↓r
                                        ; sub_256+E↓r ...
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db 0FCh
                db 0F0h
                db 0C0h
                db    0
                db  3Fh ; ?
                db  0Fh
                db    3
                db  3Fh ; ?
                db 0CFh
                db 0F3h
                db 0FCh
                db 0C0h
                db  30h ; 0
                db  0Ch
                db    3
                db    0
                db    3
                db  0Ch
                db  0Fh
                db  30h ; 0
                db  33h ; 3
                db  3Ch ; <
                db  3Fh ; ?
                db 0C0h
                db 0C3h
                db 0CCh
                db 0CFh
                db 0F0h
                db 0F3h
                db 0FCh
                db 0FFh
word_248        dw 0                    ; DATA XREF: drv_fn01_select_page+11↓w
word_24A        dw 0B000h               ; DATA XREF: sub_3A4+3↓r
                                        ; drv_fn07_get_pixel↓r ...
word_24C        dw 0B800h               ; DATA XREF: drv_fn01_select_page+7↓r
                                        ; drv_fn08_copy_rect_pages+5↓r ...
word_24E        dw 0                    ; DATA XREF: drv_fn03_plot_point+2↓w
                                        ; drv_fn03_plot_point+C↓w ...
byte_250        db 0                    ; DATA XREF: drv_fn02_set_color+2B↓w
byte_251        db 0                    ; DATA XREF: drv_fn02_set_color+20↓w
byte_252        db 0                    ; DATA XREF: drv_fn02_set_color+15↓w
byte_253        db 0                    ; DATA XREF: drv_fn02_set_color+A↓w
byte_254        db 0                    ; DATA XREF: drv_fn02_set_color↓w
                                        ; drv_fn02_set_color+E↓w ...
                db    0

; =============== S U B R O U T I N E =======================================


sub_256         proc near               ; CODE XREF: drv_fn16_monster_setup:loc_A92↓p
                push    bx
                mov     ah, 30h
                int     21h             ; DOS - GET DOS VERSION
                                        ; Return: AL = major version number (00h for DOS 1.x)
                cmp     al, 3
                jz      short loc_282
                mov     bx, 0FFFFh
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     ax
                push    ax
                inc     ax
                sub     bx, ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                push    ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                push    ax
                pushf
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                jmp     short loc_29B
; ---------------------------------------------------------------------------

loc_282:                                ; CODE XREF: sub_256+7↑j
                mov     al, 1
                mov     bx, 2
                mov     ah, 58h
                int     21h             ; DOS - 3+ - GET/SET MEMORY ALLOCATION STRATEGY
                                        ; AL = function code: set allocation strategy
                pop     bx
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                push    ax
                pushf
                mov     al, 1
                mov     bx, 0
                mov     ah, 58h
                int     21h             ; DOS - 3+ - GET/SET MEMORY ALLOCATION STRATEGY
                                        ; AL = function code: set allocation strategy

loc_29B:                                ; CODE XREF: sub_256+2A↑j
                popf
                pop     bx
                jnb     short locret_2A4
                call    sub_A63
; ---------------------------------------------------------------------------
                xor     bx, bx

locret_2A4:                             ; CODE XREF: sub_256+47↑j
                retn
sub_256         endp

; ---------------------------------------------------------------------------
                db  90h
                db    0
                db    0
                db    0
                db  20h
                db    0
                db  40h ; @
                db    0
                db  60h ; `
                db    7
                db  50h ; P
                db    0
                db    0
                db  80h
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db 0B4h
                db    3
                db  0Ah
                db    0
                db    0
                db  35h ; 5
                db    1
                db  2Dh ; -
                db    2
                db  2Eh ; .
                db    3
                db    7
                db    4
                db  5Bh ; [
                db    5
                db    2
                db    6
                db  57h ; W
                db    7
                db  57h ; W
                db    9
                db    3

; =============== S U B R O U T I N E =======================================


drv_fn00_reset  proc far                ; CODE XREF: drv:entry_00↑j
                push    cs
                pop     ds
                mov     ax, 40h ; '@'
                mov     es, ax
                assume es:nothing
                mov     di, 49h ; 'I'
                mov     si, 2AEh
                mov     cx, 1Eh
                rep movsb
                mov     al, 3
                mov     dx, 3BFh
                out     dx, al          ; Printer Status Bits:
                                        ; 3: 0=printer signals an error
                                        ; 4: 1=printer is selected
                                        ; 5: 1=out of paper
                                        ; 6: 0=ready for next character
                                        ; 7: 0=busy or offline or error
                xor     al, al
                mov     dx, 3B8h
                out     dx, al
                mov     dx, 3B4h
                mov     si, 2CCh
                mov     cx, 9

loc_305:                                ; CODE XREF: drv_fn00_reset+29↓j
                lodsw
                out     dx, ax          ; Video: CRT cntrlr addr
                                        ; horizontal total
                loop    loc_305
                mov     dx, 3B8h
                mov     al, 0Ah
                out     dx, al
                mov     ax, 0B000h
                mov     es, ax
                assume es:nothing
                xor     ax, ax
                mov     di, ax
                mov     cx, 8000h
                rep stosw
                push    cs
                pop     es
                assume es:nothing
                mov     cx, 0C8h
                mov     di, 1D6h
                std

loc_326:                                ; CODE XREF: drv_fn00_reset+77↓j
                mov     dx, cx
                dec     dx
                add     dx, 4Ah ; 'J'
                mov     bx, dx
                and     bx, 3
                shl     bx, 1
                mov     ax, cs:[bx+2A6h]
                mov     bx, dx
                and     bl, 0FCh
                shr     bx, 1
                add     ax, bx
                shl     bx, 1
                shl     bx, 1
                add     ax, bx
                shl     bx, 1
                add     ax, bx
                shl     bx, 1
                shl     bx, 1
                add     ax, bx
                add     ax, 5
                stosw
                loop    loc_326
                cld
                retf
drv_fn00_reset  endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn02_set_color proc far             ; CODE XREF: drv:entry_02↑j
                mov     cs:byte_254, 0
                mov     cl, 2
                and     al, 3
                mov     cs:byte_253, al
                or      cs:byte_254, al
                shl     al, cl
                mov     cs:byte_252, al
                or      cs:byte_254, al
                shl     al, cl
                mov     cs:byte_251, al
                or      cs:byte_254, al
                shl     al, cl
                mov     cs:byte_250, al
                or      cs:byte_254, al
                retf
drv_fn02_set_color endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn03_plot_point proc far            ; CODE XREF: drv:entry_03↑j
                jnb     short loc_399
                mov     cs:word_24E, 1

loc_399:                                ; CODE XREF: drv_fn03_plot_point↑j
                call    sub_3A4
                mov     cs:word_24E, 0
                retf
drv_fn03_plot_point endp


; =============== S U B R O U T I N E =======================================


sub_3A4         proc near               ; CODE XREF: drv_fn03_plot_point:loc_399↑p
                                        ; drv_fn06_line+62↓p
                push    ax
                push    bx
                push    cx
                mov     es, cs:word_24A
                shl     bx, 1
                mov     bx, cs:[bx+48h]
                mov     si, ax
                mov     cl, 2
                shr     ax, cl
                add     bx, ax
                mov     al, es:[bx]
                and     si, 3
                cmp     cs:word_24E, 0
                jnz     short loc_3D5
                and     al, cs:[si+230h]
                or      al, cs:[si+250h]
                jmp     short loc_3DA
; ---------------------------------------------------------------------------

loc_3D5:                                ; CODE XREF: sub_3A4+23↑j
                xor     al, cs:[si+250h]

loc_3DA:                                ; CODE XREF: sub_3A4+2F↑j
                mov     es:[bx], al
                pop     cx
                pop     bx
                pop     ax
                retn
sub_3A4         endp

; ---------------------------------------------------------------------------
                db  90h
                db    6
                db    4
                db    2
                db    0

; =============== S U B R O U T I N E =======================================


drv_fn07_get_pixel proc far             ; CODE XREF: drv:entry_07↑j
                mov     es, cs:word_24A
                shl     bx, 1
                mov     bx, cs:[bx+48h]
                mov     si, ax
                mov     cl, 2
                shr     ax, cl
                add     bx, ax
                mov     al, es:[bx]
                and     si, 3
                and     al, cs:[si+234h]
                mov     cl, cs:[si+3E2h]
                shr     al, cl
                xor     ah, ah
                retf
drv_fn07_get_pixel endp

; ---------------------------------------------------------------------------
                db  90h
byte_410        db 0                    ; DATA XREF: sub_412+35↓w
                                        ; sub_412+5A↓w ...
byte_411        db 0                    ; DATA XREF: sub_412+47↓w
                                        ; sub_412+56↓r ...

; =============== S U B R O U T I N E =======================================


sub_412         proc near               ; CODE XREF: drv_fn04_hline:loc_481↓p
                                        ; drv_fn08_copy_rect_pages+1A↓p ...
                shl     bx, 1
                mov     bx, cs:[bx+48h]
                mov     si, ax
                mov     di, cx
                mov     cl, 2
                push    di
                shr     si, cl
                shr     di, cl
                cmp     si, di
                pop     di
                pushf
                mov     si, ax
                shr     ax, cl
                add     bx, ax
                mov     dx, di
                sub     dx, si
                inc     dx
                and     si, 3
                mov     ax, 4
                sub     ax, si
                and     ax, 3
                sub     dx, ax
                mov     si, ax
                mov     al, cs:[si+228h]
                mov     cs:byte_410, al
                and     di, 3
                inc     di
                and     di, 3
                sub     dx, di
                mov     al, cs:[di+22Ch]
                mov     cs:byte_411, al
                shr     dx, 1
                shr     dx, 1
                mov     cx, dx
                popf
                jnz     short locret_477
                xor     cx, cx
                mov     al, cs:byte_411
                and     cs:byte_410, al
                mov     cs:byte_411, 0

locret_477:                             ; CODE XREF: sub_412+52↑j
                retn
sub_412         endp


; =============== S U B R O U T I N E =======================================


drv_fn04_hline  proc far                ; CODE XREF: drv:entry_04↑j
                jnb     short loc_481
                mov     cs:word_24E, 1

loc_481:                                ; CODE XREF: drv_fn04_hline↑j
                call    sub_412
                mov     es, cs:word_24A
                mov     di, bx
                mov     ah, cs:byte_410
                or      ah, ah
                jz      short loc_4B0
                mov     dl, es:[di]
                mov     al, cs:byte_254
                and     dl, ah
                not     ah
                and     al, ah
                cmp     cs:word_24E, 0
                jz      short loc_4AD
                xor     al, dl
                jmp     short loc_4AF
; ---------------------------------------------------------------------------

loc_4AD:                                ; CODE XREF: drv_fn04_hline+2F↑j
                or      al, dl

loc_4AF:                                ; CODE XREF: drv_fn04_hline+33↑j
                stosb

loc_4B0:                                ; CODE XREF: drv_fn04_hline+1A↑j
                jcxz    short loc_4D1
                mov     al, cs:byte_254
                mov     ah, al
                cmp     cs:word_24E, 0
                jz      short loc_4CA

loc_4C0:                                ; CODE XREF: drv_fn04_hline+4E↓j
                mov     al, es:[di]
                xor     al, ah
                stosb
                loop    loc_4C0
                jmp     short loc_4D1
; ---------------------------------------------------------------------------

loc_4CA:                                ; CODE XREF: drv_fn04_hline+46↑j
                shr     cx, 1
                rep stosw
                jnb     short loc_4D1
                stosb

loc_4D1:                                ; CODE XREF: drv_fn04_hline:loc_4B0↑j
                                        ; drv_fn04_hline+50↑j ...
                mov     ah, cs:byte_411
                or      ah, ah
                jz      short loc_4F6
                mov     dl, es:[di]
                mov     al, cs:byte_254
                and     dl, ah
                not     ah
                and     al, ah
                cmp     cs:word_24E, 0
                jz      short loc_4F3
                xor     al, dl
                jmp     short loc_4F5
; ---------------------------------------------------------------------------

loc_4F3:                                ; CODE XREF: drv_fn04_hline+75↑j
                or      al, dl

loc_4F5:                                ; CODE XREF: drv_fn04_hline+79↑j
                stosb

loc_4F6:                                ; CODE XREF: drv_fn04_hline+60↑j
                mov     cs:word_24E, 0
                retf
drv_fn04_hline  endp


; =============== S U B R O U T I N E =======================================


drv_fn05_vline  proc far                ; CODE XREF: drv:entry_05↑j
                jnb     short loc_507
                mov     cs:word_24E, 1

loc_507:                                ; CODE XREF: drv_fn05_vline↑j
                mov     es, cs:word_24A
                mov     si, ax
                shr     ax, 1
                shr     ax, 1
                and     si, 3
                sub     cx, bx
                inc     cx

loc_518:                                ; CODE XREF: drv_fn05_vline+36↓j
                mov     di, bx
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, ax
                mov     dl, es:[di]
                and     dl, cs:[si+230h]
                or      dl, cs:[si+250h]
                mov     es:[di], dl
                inc     bx
                loop    loc_518
                mov     cs:word_24E, 0
                retf
drv_fn05_vline  endp

; ---------------------------------------------------------------------------
word_53E        dw 0                    ; DATA XREF: drv_fn06_line:loc_573↓w
                                        ; drv_fn06_line:loc_5C9↓r
word_540        dw 0                    ; DATA XREF: drv_fn06_line:loc_566↓w
                                        ; drv_fn06_line+80↓r
word_542        dw 0                    ; DATA XREF: drv_fn06_line+5A↓w
                                        ; drv_fn06_line+85↓r
word_544        dw 0                    ; DATA XREF: drv_fn06_line+40↓w
                                        ; drv_fn06_line+6A↓r
word_546        dw 0                    ; DATA XREF: drv_fn06_line+45↓w
                                        ; drv_fn06_line+6F↓r
word_548        dw 0                    ; DATA XREF: drv_fn06_line+50↓w
                                        ; drv_fn06_line+74↓r
word_54A        dw 0                    ; DATA XREF: drv_fn06_line:loc_584↓w
word_54C        dw 0                    ; DATA XREF: drv_fn06_line+3B↓w
                                        ; drv_fn06_line+4A↓r

; =============== S U B R O U T I N E =======================================


drv_fn06_line   proc far                ; CODE XREF: drv:entry_06↑j
                jnb     short loc_557
                mov     cs:word_24E, 1

loc_557:                                ; CODE XREF: drv_fn06_line↑j
                mov     si, 1
                mov     di, si
                push    bx
                push    ax
                sub     dx, bx
                jge     short loc_566
                neg     di
                neg     dx

loc_566:                                ; CODE XREF: drv_fn06_line+12↑j
                mov     cs:word_540, di
                sub     cx, ax
                jge     short loc_573
                neg     si
                neg     cx

loc_573:                                ; CODE XREF: drv_fn06_line+1F↑j
                mov     cs:word_53E, si
                cmp     cx, dx
                jge     short loc_582
                xor     si, si
                xchg    cx, dx
                jmp     short loc_584
; ---------------------------------------------------------------------------

loc_582:                                ; CODE XREF: drv_fn06_line+2C↑j
                xor     di, di

loc_584:                                ; CODE XREF: drv_fn06_line+32↑j
                mov     cs:word_54A, cx
                mov     cs:word_54C, dx
                mov     cs:word_544, si
                mov     cs:word_546, di
                mov     ax, cs:word_54C
                shl     ax, 1
                mov     cs:word_548, ax
                sub     ax, cx
                mov     dx, ax
                sub     ax, cx
                mov     cs:word_542, ax
                inc     cx
                pop     ax
                pop     bx

loc_5AF:                                ; CODE XREF: drv_fn06_line+79↓j
                                        ; drv_fn06_line+8A↓j
                push    dx
                call    sub_3A4
                pop     dx
                or      dx, dx
                jns     short loc_5C9
                add     ax, cs:word_544
                add     bx, cs:word_546
                add     dx, cs:word_548
                loop    loc_5AF

loc_5C9:                                ; CODE XREF: drv_fn06_line+68↑j
                add     ax, cs:word_53E
                add     bx, cs:word_540
                add     dx, cs:word_542
                loop    loc_5AF
                mov     cs:word_24E, 0
                retf
drv_fn06_line   endp


; =============== S U B R O U T I N E =======================================


drv_fn01_select_page proc far           ; CODE XREF: drv:entry_01↑j
                mov     bx, 0B000h
                or      ax, ax
                jz      short loc_5EE
                mov     bx, cs:word_24C

loc_5EE:                                ; CODE XREF: drv_fn01_select_page+5↑j
                mov     cs:word_24A, bx
                mov     cs:word_248, ax
                retf
drv_fn01_select_page endp


; =============== S U B R O U T I N E =======================================


drv_fn0C_restore_rect proc far          ; CODE XREF: drv:entry_0C↑j
                mov     ds, ax
                xor     si, si
                lodsw
                mov     di, ax
                mov     cl, 2
                shr     di, cl
                lodsw
                push    ax
                lodsw
                mov     cx, ax
                lodsw
                mov     dx, ax
                mov     ax, di
                mov     es, cs:word_24A
                pop     bx

loc_613:                                ; CODE XREF: drv_fn0C_restore_rect+2C↓j
                mov     di, bx
                inc     bx
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, ax
                push    cx
                rep movsb
                pop     cx
                dec     dx
                jnz     short loc_613
                push    es
                mov     bx, ds
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                retf
drv_fn0C_restore_rect endp

; ---------------------------------------------------------------------------
                db  90h
word_632        dw 0                    ; DATA XREF: drv_fn0B_save_rect↓w
                                        ; drv_fn0B_save_rect+4B↓r
word_634        dw 0                    ; DATA XREF: drv_fn0B_save_rect+4↓w
                                        ; drv_fn0B_save_rect+50↓r
word_636        dw 0                    ; DATA XREF: drv_fn0B_save_rect+19↓w
                                        ; drv_fn0B_save_rect+55↓r
word_638        dw 0                    ; DATA XREF: drv_fn0B_save_rect+1E↓w
                                        ; drv_fn0B_save_rect+5C↓r

; =============== S U B R O U T I N E =======================================


drv_fn0B_save_rect proc far             ; CODE XREF: drv:entry_0B↑j
                mov     cs:word_632, ax
                mov     cs:word_634, bx
                mov     si, cx
                mov     cl, 2
                shr     ax, cl
                shr     si, cl
                sub     si, ax
                inc     si
                sub     dx, bx
                mov     cx, dx
                inc     cx
                mov     cs:word_636, si
                mov     cs:word_638, cx
                mov     di, dx
                push    ax
                mov     ax, si
                cwd
                mul     cx
                add     ax, 8
                shr     ax, 1
                shr     ax, 1
                shr     ax, 1
                shr     ax, 1
                inc     ax
                push    bx
                mov     bx, ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                jb      short loc_6B1
                mov     es, ax
                mov     ds, cs:word_24A
                pop     dx
                xor     di, di
                mov     ax, cs:word_632
                stosw
                mov     ax, cs:word_634
                stosw
                mov     ax, cs:word_636
                mov     cx, ax
                stosw
                mov     ax, cs:word_638
                stosw

loc_69B:                                ; CODE XREF: drv_fn0B_save_rect+72↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+48h]
                add     si, dx
                push    cx
                rep movsb
                pop     cx
                inc     bx
                dec     ax
                jnz     short loc_69B
                mov     ax, es
                push    ax

loc_6B1:                                ; CODE XREF: drv_fn0B_save_rect+3F↑j
                pop     ax
                retf
drv_fn0B_save_rect endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn08_copy_rect_pages proc far       ; CODE XREF: drv:entry_08↑j
                or      ax, ax
                mov     ax, 0B000h
                mov     bx, cs:word_24C
                jz      short loc_6C1
                xchg    ax, bx

loc_6C1:                                ; CODE XREF: drv_fn08_copy_rect_pages+A↑j
                push    dx
                push    ax
                push    bx
                push    cx
                mov     ax, cx
                mov     bx, dx
                mov     cx, si
                sub     di, dx
                push    di
                call    sub_412
                pop     ax
                pop     bx
                pop     es
                pop     ds
                pop     dx
                shr     bx, 1
                shr     bx, 1

loc_6DA:                                ; CODE XREF: drv_fn08_copy_rect_pages+66↓j
                push    ax
                push    cx
                mov     si, dx
                shl     si, 1
                mov     si, cs:[si+48h]
                add     si, bx
                mov     di, si
                mov     ah, cs:byte_410
                or      ah, ah
                jz      short loc_6FE
                lodsb
                and     es:[di], ah
                not     ah
                and     al, ah
                or      es:[di], al
                inc     di

loc_6FE:                                ; CODE XREF: drv_fn08_copy_rect_pages+3C↑j
                jcxz    short loc_702
                rep movsb

loc_702:                                ; CODE XREF: drv_fn08_copy_rect_pages:loc_6FE↑j
                mov     ah, cs:byte_411
                or      ah, ah
                jz      short loc_716
                lodsb
                and     es:[di], ah
                not     ah
                and     al, ah
                or      es:[di], al

loc_716:                                ; CODE XREF: drv_fn08_copy_rect_pages+55↑j
                inc     dx
                pop     cx
                pop     ax
                dec     ax
                jns     short loc_6DA
                retf
drv_fn08_copy_rect_pages endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn09_copy_page proc far             ; CODE XREF: drv:entry_09↑j
                mov     si, 0B000h
                mov     di, cs:word_24C
                or      ax, ax
                jz      short loc_72C
                xchg    si, di

loc_72C:                                ; CODE XREF: drv_fn09_copy_page+A↑j
                mov     ds, si
                assume ds:nothing
                mov     es, di
                assume es:nothing
                xor     bx, bx

loc_732:                                ; CODE XREF: drv_fn09_copy_page+29↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+48h]
                mov     di, si
                mov     cx, 28h ; '('
                rep movsw
                inc     bx
                cmp     bx, 0C8h
                jl      short loc_732
                retf
drv_fn09_copy_page endp


; =============== S U B R O U T I N E =======================================


drv_fn0A_page_op proc far               ; CODE XREF: drv:entry_0A↑j
                mov     si, 0B000h
                mov     di, cs:word_24C
                or      ax, ax
                jz      short loc_758
                xchg    si, di

loc_758:                                ; CODE XREF: drv_fn0A_page_op+A↑j
                mov     ds, si
                mov     es, di
                xor     bx, bx

loc_75E:                                ; CODE XREF: drv_fn0A_page_op+31↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+48h]
                mov     di, si
                mov     cx, 28h ; '('

loc_76C:                                ; CODE XREF: drv_fn0A_page_op+2A↓j
                lodsw
                mov     dx, es:[di]
                stosw
                mov     [si-2], dx
                loop    loc_76C
                inc     bx
                cmp     bx, 0C8h
                jl      short loc_75E
                retf
drv_fn0A_page_op endp

; ---------------------------------------------------------------------------
word_77E        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b↓w
                                        ; drv_fn0E_scroll_rect_b+46↓r ...
word_780        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b+36↓r
word_782        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b:loc_798↓w
                                        ; drv_fn0E_scroll_rect_b:loc_7C3↓r ...

; =============== S U B R O U T I N E =======================================


drv_fn0E_scroll_rect_b proc near        ; CODE XREF: drv:entry_0E↑j
                mov     cs:word_77E, si
                push    si
                or      si, si
                js      short loc_794
                mov     di, dx
                sub     di, si
                jmp     short loc_798
; ---------------------------------------------------------------------------

loc_794:                                ; CODE XREF: drv_fn0E_scroll_rect_b+8↑j
                mov     di, bx
                sub     di, si

loc_798:                                ; CODE XREF: drv_fn0E_scroll_rect_b+E↑j
                mov     cs:word_782, di
                sub     dx, bx
                pop     di
                mov     bp, di
                or      di, di
                jns     short loc_7A8
                neg     di

loc_7A8:                                ; CODE XREF: drv_fn0E_scroll_rect_b+20↑j
                sub     dx, di
                inc     dx
                push    dx
                call    sub_412
                pop     dx
                mov     ds, cs:word_24A
                assume ds:nothing
                mov     es, cs:word_24A
                assume es:nothing
                mov     bx, cs:word_780
                shr     bx, 1
                shr     bx, 1

loc_7C3:                                ; CODE XREF: drv_fn0E_scroll_rect_b+A3↓j
                mov     si, cs:word_782
                mov     di, si
                add     di, cs:word_77E
                cmp     di, 0C8h
                jnb     short loc_812
                shl     si, 1
                shl     di, 1
                mov     si, cs:[si+48h]
                mov     di, cs:[di+48h]
                add     si, bx
                add     di, bx
                push    cx
                mov     ah, cs:byte_410
                or      ah, ah
                jz      short loc_7FB
                lodsb
                and     [di], ah
                not     ah
                and     al, ah
                or      [di], al
                inc     di

loc_7FB:                                ; CODE XREF: drv_fn0E_scroll_rect_b+6B↑j
                jcxz    short loc_7FF
                rep movsb

loc_7FF:                                ; CODE XREF: drv_fn0E_scroll_rect_b:loc_7FB↑j
                mov     ah, cs:byte_411
                or      ah, ah
                jz      short loc_811
                lodsb
                and     [di], ah
                not     ah
                and     al, ah
                or      [di], al

loc_811:                                ; CODE XREF: drv_fn0E_scroll_rect_b+82↑j
                pop     cx

loc_812:                                ; CODE XREF: drv_fn0E_scroll_rect_b+4F↑j
                inc     cs:word_782
                test    cs:word_77E, 8000h
                js      short loc_826
                sub     cs:word_782, 2

loc_826:                                ; CODE XREF: drv_fn0E_scroll_rect_b+9A↑j
                dec     dx
                jnz     short loc_7C3
drv_fn0E_scroll_rect_b endp

; [00000001 BYTES: COLLAPSED FUNCTION drv_fn0D_scroll_rect_a. PRESS NUMPAD+ TO EXPAND]
                db    0
                db  55h ; U
                db 0AAh
                db 0FFh
byte_82E        db 0                    ; DATA XREF: drv_fn15_put_char+13↓w
                                        ; drv_fn15_put_char+64↓r ...
byte_82F        db 0                    ; DATA XREF: drv_fn15_put_char+23↓w
                                        ; drv_fn15_put_char+BE↓r ...
byte_830        db 0                    ; DATA XREF: drv_fn15_put_char+28↓w
                                        ; drv_fn15_put_char+39↓w ...
                db    0

; =============== S U B R O U T I N E =======================================


drv_fn15_put_char proc far              ; CODE XREF: drv:entry_15↑j
                jnb     short loc_83B
                mov     cs:word_24E, 1

loc_83B:                                ; CODE XREF: drv_fn15_put_char↑j
                cmp     dh, 0FFh
                jnz     short loc_842
                inc     dh

loc_842:                                ; CODE XREF: drv_fn15_put_char+C↑j
                and     dl, 3
                mov     cs:byte_82E, ah
                push    es
                pop     ds
                xor     bh, bh
                mov     bl, dl
                mov     dl, cs:[bx+82Ah]
                mov     cs:byte_82F, dl
                mov     cs:byte_830, dh
                cmp     dh, 0FFh
                jz      short loc_870
                mov     bl, dh
                mov     dl, cs:[bx+82Ah]
                mov     cs:byte_830, dl

loc_870:                                ; CODE XREF: drv_fn15_put_char+30↑j
                mov     dl, ch
                xor     dh, dh
                mov     di, dx
                mov     bl, al
                mov     si, bx
                mov     dl, cl
                xor     dh, dh
                shl     dx, 1
                mov     cl, 3
                shl     si, cl
                shl     di, cl
                mov     es, cs:word_24A
                push    word ptr [si]
                push    word ptr [si+2]
                push    word ptr [si+4]
                push    word ptr [si+6]
                test    cs:byte_82E, 4
                jz      short loc_8A2
                mov     byte ptr [si+7], 0FFh

loc_8A2:                                ; CODE XREF: drv_fn15_put_char+6A↑j
                test    cs:byte_82E, 8
                jz      short loc_8B5
                not     word ptr [si]
                not     word ptr [si+2]
                not     word ptr [si+4]
                not     word ptr [si+6]

loc_8B5:                                ; CODE XREF: drv_fn15_put_char+76↑j
                mov     cx, 8
                mov     bx, di

loc_8BA:                                ; CODE XREF: drv_fn15_put_char+E4↓j
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, dx
                mov     al, cs:byte_830
                cmp     al, 0FFh
                jz      short loc_8D0
                mov     ah, al
                mov     es:[di], ax

loc_8D0:                                ; CODE XREF: drv_fn15_put_char+97↑j
                lodsb
                or      al, al
                jz      short loc_913
                push    bx
                mov     bl, al
                and     bx, 0F0h
                shr     bl, 1
                shr     bl, 1
                shr     bl, 1
                shr     bl, 1
                mov     bl, cs:[bx+238h]
                not     bl
                and     es:[di], bl
                not     bl
                and     bl, cs:byte_82F
                or      es:[di], bl
                inc     di
                mov     bl, al
                and     bl, 0Fh
                mov     bl, cs:[bx+238h]
                not     bl
                and     es:[di], bl
                not     bl
                and     bl, cs:byte_82F
                or      es:[di], bl
                pop     bx

loc_913:                                ; CODE XREF: drv_fn15_put_char+A1↑j
                inc     bx
                mov     di, bx
                loop    loc_8BA
                pop     word ptr [si-2]
                pop     word ptr [si-4]
                pop     word ptr [si-6]
                pop     word ptr [si-8]
                mov     cs:word_24E, 0
                retf
drv_fn15_put_char endp

; ---------------------------------------------------------------------------
                db    0
                db    3
                db  0Fh
                db  3Fh ; ?
word_930        dw 0                    ; DATA XREF: drv_fn13_draw_image+19↓w
                                        ; drv_fn13_draw_image+34↓r ...
word_932        dw 0                    ; DATA XREF: drv_fn13_draw_image+2F↓w
                                        ; drv_fn13_draw_image+52↓w ...

; =============== S U B R O U T I N E =======================================


drv_fn13_draw_image proc far            ; CODE XREF: drv:entry_13↑j
                mov     cs:byte_411, 0
                mov     ds, ax
                mov     es, cs:word_24A
                shl     bx, 1
                shl     bx, 1
                add     bx, 2
                mov     si, [bx]
                mov     bx, [bx+2]
                mov     cs:word_930, bx
                mov     di, dx
                shr     cx, 1
                shr     cx, 1
                mov     bx, cx
                lodsw
                mov     cx, ax
                lodsw
                push    cx
                shr     cx, 1
                shr     cx, 1
                mov     cs:word_932, cx
                cmp     cs:word_930, 0
                pop     cx
                jnz     short loc_98B
                push    bx
                mov     bx, cx
                and     bx, 3
                mov     bl, cs:[bx+92Ch]
                mov     cs:byte_411, bl
                or      bl, bl
                pop     bx
                jz      short loc_98B
                dec     cs:word_932

loc_98B:                                ; CODE XREF: drv_fn13_draw_image+3B↑j
                                        ; drv_fn13_draw_image+50↑j
                mov     dx, ax
                cmp     cs:word_930, 0
                jnz     short loc_9BE

loc_995:                                ; CODE XREF: drv_fn13_draw_image+87↓j
                push    di
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, bx
                mov     cx, cs:word_932
                rep movsb
                mov     ch, cs:byte_411
                or      ch, ch
                jz      short loc_9B8
                lodsb
                mov     ah, es:[di]
                and     ah, ch
                or      al, ah
                stosb

loc_9B8:                                ; CODE XREF: drv_fn13_draw_image+79↑j
                pop     di
                inc     di
                dec     dx
                jnz     short loc_995
                retf
; ---------------------------------------------------------------------------

loc_9BE:                                ; CODE XREF: drv_fn13_draw_image+5F↑j
                push    bp
                mov     bp, dx

loc_9C1:                                ; CODE XREF: drv_fn13_draw_image+126↓j
                push    di
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, bx
                mov     cx, cs:word_932

loc_9D0:                                ; CODE XREF: drv_fn13_draw_image+11E↓j
                lodsb
                push    si
                mov     si, cs:word_930
                mov     ah, [si]
                pop     si
                inc     cs:word_930
                mov     dl, es:[di]
                test    ah, 80h
                jz      short loc_9EB
                and     al, 3Fh
                jmp     short loc_9EE
; ---------------------------------------------------------------------------

loc_9EB:                                ; CODE XREF: drv_fn13_draw_image+B1↑j
                and     dl, 3Fh

loc_9EE:                                ; CODE XREF: drv_fn13_draw_image+B5↑j
                test    ah, 40h
                jz      short loc_9F7
                and     al, 0CFh
                jmp     short loc_9FA
; ---------------------------------------------------------------------------

loc_9F7:                                ; CODE XREF: drv_fn13_draw_image+BD↑j
                and     dl, 0CFh

loc_9FA:                                ; CODE XREF: drv_fn13_draw_image+C1↑j
                test    ah, 20h
                jz      short loc_A03
                and     al, 0F3h
                jmp     short loc_A06
; ---------------------------------------------------------------------------

loc_A03:                                ; CODE XREF: drv_fn13_draw_image+C9↑j
                and     dl, 0F3h

loc_A06:                                ; CODE XREF: drv_fn13_draw_image+CD↑j
                test    ah, 10h
                jz      short loc_A0F
                and     al, 0FCh
                jmp     short loc_A12
; ---------------------------------------------------------------------------

loc_A0F:                                ; CODE XREF: drv_fn13_draw_image+D5↑j
                and     dl, 0FCh

loc_A12:                                ; CODE XREF: drv_fn13_draw_image+D9↑j
                or      al, dl
                stosb
                dec     cx
                jcxz    short loc_A55
                lodsb
                mov     dl, es:[di]
                test    ah, 8
                jz      short loc_A25
                and     al, 3Fh
                jmp     short loc_A28
; ---------------------------------------------------------------------------

loc_A25:                                ; CODE XREF: drv_fn13_draw_image+EB↑j
                and     dl, 3Fh

loc_A28:                                ; CODE XREF: drv_fn13_draw_image+EF↑j
                test    ah, 4
                jz      short loc_A31
                and     al, 0CFh
                jmp     short loc_A34
; ---------------------------------------------------------------------------

loc_A31:                                ; CODE XREF: drv_fn13_draw_image+F7↑j
                and     dl, 0CFh

loc_A34:                                ; CODE XREF: drv_fn13_draw_image+FB↑j
                test    ah, 2
                jz      short loc_A3D
                and     al, 0F3h
                jmp     short loc_A40
; ---------------------------------------------------------------------------

loc_A3D:                                ; CODE XREF: drv_fn13_draw_image+103↑j
                and     dl, 0F3h

loc_A40:                                ; CODE XREF: drv_fn13_draw_image+107↑j
                test    ah, 1
                jz      short loc_A49
                and     al, 0FCh
                jmp     short loc_A4C
; ---------------------------------------------------------------------------

loc_A49:                                ; CODE XREF: drv_fn13_draw_image+10F↑j
                and     dl, 0FCh

loc_A4C:                                ; CODE XREF: drv_fn13_draw_image+113↑j
                or      al, dl
                stosb
                dec     cx
                jcxz    short loc_A55
                jmp     loc_9D0
; ---------------------------------------------------------------------------

loc_A55:                                ; CODE XREF: drv_fn13_draw_image+E2↑j
                                        ; drv_fn13_draw_image+11C↑j
                pop     di
                inc     di
                dec     bp
                jz      short loc_A5D
                jmp     loc_9C1
; ---------------------------------------------------------------------------

loc_A5D:                                ; CODE XREF: drv_fn13_draw_image+124↑j
                pop     bp
                retf
drv_fn13_draw_image endp

; ---------------------------------------------------------------------------
                db  90h
; [00000001 BYTES: COLLAPSED FUNCTION drv_fn10_load_image. PRESS NUMPAD+ TO EXPAND]
; [00000001 BYTES: COLLAPSED FUNCTION drv_fn12_draw_op12. PRESS NUMPAD+ TO EXPAND]
; [00000001 BYTES: COLLAPSED FUNCTION drv_fn14_draw_image_alt. PRESS NUMPAD+ TO EXPAND]

; =============== S U B R O U T I N E =======================================

; Attributes: noreturn

sub_A63         proc near               ; CODE XREF: sub_256+49↑p
                                        ; sub_A63↓j
                jmp     short sub_A63
sub_A63         endp

; ---------------------------------------------------------------------------
                db  90h
word_A66        dw 0                    ; DATA XREF: drv_fn16_monster_setup+29↓w
                                        ; drv_fn16_monster_setup+66↓r ...
word_A68        dw 0                    ; DATA XREF: drv_fn16_monster_setup+2↓w
                                        ; drv_fn16_monster_setup+BD↓r
word_A6A        dw 0                    ; DATA XREF: drv_fn16_monster_setup+16↓w

; =============== S U B R O U T I N E =======================================


drv_fn16_monster_setup proc far         ; CODE XREF: drv:entry_16↑j
                push    ds
                pop     es
                mov     cs:word_A68, bx
                mov     ds, ax
                xor     si, si
                lodsw
                mov     di, dx
                mov     dx, si
                stosb
                mov     cx, 900h
                mul     cx
                mov     cs:word_A6A, ax
                mov     bx, ax
                or      ax, ax
                jz      short loc_A92
                dec     bx
                mov     cl, 4
                shr     bx, cl
                inc     bx

loc_A92:                                ; CODE XREF: drv_fn16_monster_setup+1E↑j
                call    sub_256
                mov     cs:word_A66, bx
                push    ds
                mov     bx, 90h
                inc     bx
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                mov     es, ax
                xor     di, di
                mov     ax, di
                mov     cx, 480h
                rep stosw
                mov     ax, 0B000h
                mov     ds, ax
                assume ds:nothing
                mov     si, 20h ; ' '
                xor     di, di

loc_AB8:                                ; CODE XREF: drv_fn16_monster_setup+62↓j
                push    si
                shl     si, 1
                mov     si, cs:[si+48h]
                add     si, 10h
                mov     cx, 0Ch
                rep movsw
                pop     si
                inc     si
                cmp     si, 80h
                jnz     short loc_AB8
                push    es
                pop     ds
                assume ds:nothing
                mov     es, cs:word_A66
                xor     si, si
                mov     di, si
                mov     cx, 480h
                rep movsw
                push    ds
                pop     es
                pop     ds
                mov     ax, 1
                call    sub_B52
                push    ds
                push    es
                xor     si, si
                lodsw
                push    ax
                mov     bx, cs:word_A66
                mov     ds, bx
                mov     es, bx
                mov     di, 900h

loc_AFB:                                ; CODE XREF: drv_fn16_monster_setup+99↓j
                dec     ax
                jz      short loc_B07
                mov     cx, 480h
                xor     si, si
                rep movsw
                jmp     short loc_AFB
; ---------------------------------------------------------------------------

loc_B07:                                ; CODE XREF: drv_fn16_monster_setup+90↑j
                pop     ax
                pop     es
                pop     ds

loc_B0A:                                ; CODE XREF: drv_fn16_monster_setup+A7↓j
                cmp     ax, 1
                jz      short loc_B15
                call    sub_B52
                dec     ax
                jmp     short loc_B0A
; ---------------------------------------------------------------------------

loc_B15:                                ; CODE XREF: drv_fn16_monster_setup+A1↑j
                push    es
                mov     ax, ss
                mov     es, ax
                xor     si, si
                lodsw
                mov     dx, ax
                lodsw
                inc     dx
                shl     dx, 1
                mov     si, dx
                mov     cx, ax
                sub     cx, si
                mov     di, cs:word_A68
                rep movsb
                pop     bx
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                push    es
                mov     bx, ds
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                retf
drv_fn16_monster_setup endp

; ---------------------------------------------------------------------------
                db    6
                db    4
                db    2
                db    0
byte_B48        db 0                    ; DATA XREF: sub_B52+6D↓w
                                        ; sub_B52+D5↓r
byte_B49        db 0                    ; DATA XREF: sub_B52+75↓w
                                        ; sub_B52+A4↓w
word_B4A        dw 0                    ; DATA XREF: sub_B52+45↓w
                                        ; sub_B52+CB↓r ...
word_B4C        dw 0                    ; DATA XREF: sub_B52+5F↓w
                                        ; sub_B52+B5↓w ...
word_B4E        dw 0                    ; DATA XREF: sub_B52+64↓w
                                        ; sub_B52+BB↓w ...
byte_B50        db 0                    ; DATA XREF: sub_B52+3C↓w
                                        ; sub_B52+AB↓r
byte_B51        db 0                    ; DATA XREF: sub_B52+B0↓w
                                        ; sub_B52+DC↓r ...

; =============== S U B R O U T I N E =======================================


sub_B52         proc near               ; CODE XREF: drv_fn16_monster_setup+7A↑p
                                        ; drv_fn16_monster_setup+A3↑p
                push    ax
                push    bx
                push    cx
                push    dx
                push    bp
                push    ds
                push    es
                dec     ax
                mov     dx, ax
                shl     ax, 1
                mov     si, ax
                mov     bp, [si+2]
                mov     ax, dx
                xor     dx, dx
                mov     cx, 900h
                mul     cx
                mov     di, ax
                xor     si, si
                mov     dx, ds
                push    es
                pop     ds
                mov     es, cs:word_A66
                push    ds
                mov     ds, dx
                mov     al, ds:[bp+0]
                cbw
                add     ax, 3
                mov     bx, ax
                and     bx, 3
                mov     bl, cs:[bx+0B44h]
                mov     cs:byte_B50, bl
                shr     ax, 1
                shr     ax, 1
                mov     cs:word_B4A, ax
                mov     al, ds:[bp+1]
                cbw
                add     ax, 6
                mov     cl, 3
                shl     ax, cl
                add     si, ax
                add     di, ax
                shl     ax, 1
                add     si, ax
                add     di, ax
                mov     cs:word_B4C, si
                mov     cs:word_B4E, di
                mov     al, ds:[bp+2]
                mov     cs:byte_B48, al
                mov     al, ds:[bp+3]
                mov     cs:byte_B49, al
                add     bp, 4
                pop     ds
                xor     ah, ah

loc_BD1:                                ; CODE XREF: sub_B52+120↓j
                push    ds
                mov     ds, dx
                mov     al, ds:[bp+0]
                inc     bp
                pop     ds
                mov     cl, al
                and     cx, 0F0h
                shr     cl, 1
                shr     cl, 1
                shr     cl, 1
                shr     cl, 1
                and     al, 0Fh
                or      al, 80h
                cmp     al, 84h
                jnb     short loc_BF2
                and     al, 3

loc_BF2:                                ; CODE XREF: sub_B52+9C↑j
                                        ; sub_B52+11E↓j
                or      ah, ah
                jnz     short loc_C2C
                dec     cs:byte_B49
                js      short loc_C75
                mov     ah, cs:byte_B50
                mov     cs:byte_B51, ah
                add     cs:word_B4C, 18h
                add     cs:word_B4E, 18h
                mov     si, cs:word_B4C
                mov     di, cs:word_B4E
                add     si, cs:word_B4A
                add     di, cs:word_B4A
                mov     ah, cs:byte_B48

loc_C2C:                                ; CODE XREF: sub_B52+A2↑j
                mov     bl, cl
                mov     cl, cs:byte_B51
                test    al, 80h
                jz      short loc_C41
                mov     ch, [si]
                mov     bh, 3
                shl     bh, cl
                and     ch, bh
                jmp     short loc_C48
; ---------------------------------------------------------------------------

loc_C41:                                ; CODE XREF: sub_B52+E3↑j
                mov     ch, al
                and     ch, 3
                shl     ch, cl

loc_C48:                                ; CODE XREF: sub_B52+ED↑j
                mov     bh, 3
                shl     bh, cl
                not     bh
                and     es:[di], bh
                or      es:[di], ch
                mov     cl, bl
                cmp     cs:byte_B51, 0
                jnz     short loc_C66
                mov     cs:byte_B51, 8
                inc     si
                inc     di

loc_C66:                                ; CODE XREF: sub_B52+10A↑j
                sub     cs:byte_B51, 2
                dec     ah
                dec     cl
                jns     short loc_BF2
                jmp     loc_BD1
; ---------------------------------------------------------------------------

loc_C75:                                ; CODE XREF: sub_B52+A9↑j
                pop     es
                pop     ds
                pop     bp
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                retn
sub_B52         endp


; =============== S U B R O U T I N E =======================================


drv_fn17_monster_draw proc far          ; CODE XREF: drv:entry_17↑j
                cmp     ax, 0FFFFh
                jnz     short loc_C9C
                mov     bx, cs:word_A66
                or      bx, bx
                jz      short loc_C9A
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                mov     cs:word_A66, 0

loc_C9A:                                ; CODE XREF: drv_fn17_monster_draw+C↑j
                jmp     short locret_CD2
; ---------------------------------------------------------------------------

loc_C9C:                                ; CODE XREF: drv_fn17_monster_draw+3↑j
                push    bp
                mov     bp, 60h ; '`'
                mov     di, cx
                or      ax, ax
                jz      short loc_CAD
                mov     cx, 900h
                xor     dx, dx
                mul     cx

loc_CAD:                                ; CODE XREF: drv_fn17_monster_draw+27↑j
                mov     ds, cs:word_A66
                mov     si, ax
                mov     ax, 0B000h
                mov     es, ax
                assume es:nothing
                shr     bx, 1
                shr     bx, 1

loc_CBD:                                ; CODE XREF: drv_fn17_monster_draw+52↓j
                push    di
                shl     di, 1
                mov     di, cs:[di+48h]
                add     di, bx
                mov     cx, 0Ch
                rep movsw
                pop     di
                inc     di
                dec     bp
                jnz     short loc_CBD
                pop     bp

locret_CD2:                             ; CODE XREF: drv_fn17_monster_draw:loc_C9A↑j
                retf
drv_fn17_monster_draw endp

drv             ends


                end
