//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
// |                      License info: 48-337F-7354-97                      |
// |                       Paul Gilbert, ScummVM Team                        |
// +-------------------------------------------------------------------------+
//
//
//      This file should be used in the following way:
//         - reload executable into IDA with using switch -c
//         - use File, Load IDC file and load this file.
//
//      NOTE: This file doesn't contain all information from the database.
//

#define UNLOADED_FILE   1
#include <idc.idc>

static main(void)
{
        // set 'loading idc file' mode
        set_inf_attr(INF_GENFLAGS, INFFL_LOADIDC|get_inf_attr(INF_GENFLAGS));
        GenInfo();            // various settings
        Segments();           // segmentation
        Enums();              // enumerations
        Structures();         // structure types
        ApplyStrucTInfos();   // structure type infos
        Patches();            // manual patches
        SegRegs();            // segment register values
        Bytes();              // individual bytes (code,data)
        Functions();          // function definitions
        // clear 'loading idc file' mode
        set_inf_attr(INF_GENFLAGS, ~INFFL_LOADIDC&get_inf_attr(INF_GENFLAGS));
}

//------------------------------------------------------------------------
// General information

static GenInfo(void) {

        delete_all_segments();    // purge database
	set_processor_type("metapc", SETPROC_USER);
	set_inf_attr(INF_COMPILER, 0);
	set_inf_attr(INF_STRLIT_BREAK, 0xA);
	set_flag(INF_CMTFLG, SCF_ALLCMT, 0);
	set_flag(INF_OUTFLAGS, OFLG_SHOW_VOID, 0);
	set_inf_attr(INF_XREFNUM, 2);
	set_flag(INF_OUTFLAGS, OFLG_SHOW_AUTO, 1);
	set_inf_attr(INF_INDENT, 16);
	set_inf_attr(INF_CMT_INDENT, 40);
	set_inf_attr(INF_MAXREF, 0x10);
}

//------------------------------------------------------------------------
// Information about segmentation

static Segments(void) {
	set_selector(0X1,0);

	add_segm_ex(0,0XC6C,0X1,0,1,2,ADDSEG_NOSREG);
	SegRename(0,"drv");
	SegClass (0,"CODE");
	SegDefReg(0x0,"es",0x0);
	SegDefReg(0x0,"ss",0x0);
	SegDefReg(0x0,"ds",0x0);
	SegDefReg(0x0,"fs",0x0);
	SegDefReg(0x0,"gs",0x0);
	set_segm_type(0,2);
	set_inf_attr(INF_LOW_OFF, 0xFFFFFFFF);
	set_inf_attr(INF_HIGH_OFF, 0xC6C);
}

//------------------------------------------------------------------------
// Information about enum types

static Enums(void) {
        auto id;
        begin_type_updating(UTP_ENUM);
        end_type_updating(UTP_ENUM);
}

//------------------------------------------------------------------------
// Information about type information for structure members

static ApplyStrucTInfos() {
}

//------------------------------------------------------------------------
// Information about structure types

static Structures(void) {
        auto id;
        begin_type_updating(UTP_STRUCT);
}

//------------------------------------------------------------------------
// Information about bytes

static Bytes_0(void) {
        auto x;
#define id x

	update_extra_cmt		(0,	E_PREV + 0,	"; File Name   : C:\\dev\\might_and_magic\\mm2\\drv\\TGA.DRV");
	update_extra_cmt		(0,	E_PREV + 1,	"; Format      : Binary file");
	update_extra_cmt		(0,	E_PREV + 2,	"; Base Address: 0000h Range: 0000h - 0C6Ch Loaded length: 0C6Ch");
	create_insn	(0);
	set_name	(0,	"entry_00");
	create_insn	(0X3);
	set_name	(0X3,	"entry_01");
	create_insn	(0X6);
	set_name	(0X6,	"entry_02");
	create_insn	(0X9);
	set_name	(0X9,	"entry_03");
	create_insn	(0XC);
	set_name	(0XC,	"entry_04");
	create_insn	(0XF);
	set_name	(0XF,	"entry_05");
	create_insn	(0X12);
	set_name	(0X12,	"entry_06");
	create_insn	(0X15);
	set_name	(0X15,	"entry_07");
	create_insn	(0X18);
	set_name	(0X18,	"entry_08");
	create_insn	(0X1B);
	set_name	(0X1B,	"entry_09");
	create_insn	(0X1E);
	set_name	(0X1E,	"entry_0A");
	create_insn	(0X21);
	set_name	(0X21,	"entry_0B");
	create_insn	(0X24);
	set_name	(0X24,	"entry_0C");
	create_insn	(0X27);
	set_name	(0X27,	"entry_0D");
	create_insn	(0X2A);
	set_name	(0X2A,	"entry_0E");
	create_insn	(0X2D);
	set_name	(0X2D,	"entry_0F");
	create_insn	(0X30);
	set_name	(0X30,	"entry_10");
	create_insn	(0X33);
	set_name	(0X33,	"entry_11");
	create_insn	(0X36);
	set_name	(0X36,	"entry_12");
	create_insn	(0X39);
	set_name	(0X39,	"entry_13");
	create_insn	(0X3C);
	set_name	(0X3C,	"entry_14");
	create_insn	(0X3F);
	set_name	(0X3F,	"entry_15");
	create_insn	(0X42);
	set_name	(0X42,	"entry_16");
	create_insn	(0X45);
	set_name	(0X45,	"entry_17");
	create_insn	(0X48);
	set_name	(0X48,	"entry_18");
	create_insn	(0X4B);
	set_name	(0X4B,	"entry_19");
	create_insn	(0X4E);
	set_name	(0X4E,	"entry_1A");
	create_insn	(0X51);
	set_name	(0X51,	"entry_1B");
	create_insn	(0X54);
	set_name	(0X54,	"entry_1C");
	create_insn	(0X57);
	set_name	(0X57,	"entry_1D");
	create_insn	(0X5A);
	set_name	(0X5A,	"entry_1E");
	create_insn	(0X5D);
	set_name	(0X5D,	"entry_1F");
	create_word	(0X64);
	create_byte	(0X29E);
	create_byte	(0X29F);
	create_byte	(0X2A0);
	create_word	(0X2A2);
	create_word	(0X2A4);
	create_word	(0X2A6);
	create_word	(0X2A8);
	create_insn	(0X2AA);
	create_insn	(x=0X2AF);
	op_hex		(x,	1);
	set_cmt	(0X2B1,	"DOS - 2+ - ALLOCATE MEMORY\nBX = number of 16-byte paragraphs desired",	0);
	create_insn	(x=0X2B1);
	op_hex		(x,	0);
	create_insn	(x=0X2B8);
	op_hex		(x,	1);
	set_cmt	(0X2BA,	"DOS - 2+ - ALLOCATE MEMORY\nBX = number of 16-byte paragraphs desired",	0);
	create_insn	(x=0X2BA);
	op_hex		(x,	0);
	create_insn	(x=0X2BE);
	op_hex		(x,	1);
	set_cmt	(0X2C0,	"DOS - 2+ - ALLOCATE MEMORY\nBX = number of 16-byte paragraphs desired",	0);
	create_insn	(x=0X2C0);
	op_hex		(x,	0);
	create_insn	(x=0X2C8);
	op_hex		(x,	1);
	set_cmt	(0X2CA,	"DOS - 2+ - FREE MEMORY\nES = segment address of area to be freed",	0);
	create_insn	(x=0X2CA);
	op_hex		(x,	0);
	create_insn	(0X2D4);
	create_insn	(0X2E7);
	set_cmt	(0X2EA,	"- VIDEO - SET VIDEO MODE\nAL = mode",	0);
	create_insn	(x=0X2EA);
	op_hex		(x,	0);
	set_cmt	(0X2F1,	"DOS - ",	0);
	create_insn	(x=0X2F1);
	op_hex		(x,	0);
	create_insn	(x=0X2F3);
	op_hex		(x,	1);
	set_cmt	(0X2F6,	"DOS - 2+ - QUIT WITH EXIT CODE (EXIT)\nAL = exit code",	0);
	create_insn	(x=0X2F6);
	op_hex		(x,	0);
	create_insn	(0X300);
	set_name	(0X300,	"drv_fn00_reset");
	set_cmt	(0X31E,	"- VIDEO - SET VIDEO MODE\nAL = mode",	0);
	create_insn	(x=0X31E);
	op_hex		(x,	0);
	create_insn	(x=0X33B);
	op_hex		(x,	1);
	create_insn	(x=0X33E);
	op_hex		(x,	1);
	create_insn	(x=0X347);
	op_hex		(x,	1);
	create_insn	(x=0X35E);
	op_hex		(x,	1);
	set_name	(0X35E,	"drv_fn02_set_color");
	create_insn	(0X376);
	set_name	(0X376,	"drv_fn03_plot_point");
	create_insn	(0X38A);
	create_insn	(x=0X392);
	op_hex		(x,	1);
	create_insn	(x=0X39B);
	op_hex		(x,	1);
	create_insn	(x=0X3A2);
	op_hex		(x,	1);
	create_insn	(0X3B9);
	create_insn	(0X3C6);
	set_name	(0X3C6,	"drv_fn07_get_pixel");
	create_insn	(x=0X3CB);
	op_hex		(x,	1);
	create_insn	(x=0X3D4);
	op_hex		(x,	1);
	create_insn	(x=0X3D7);
	op_hex		(x,	1);
	create_insn	(x=0X3E6);
	op_hex		(x,	1);
	create_byte	(0X3EE);
	create_byte	(0X3EF);
	create_insn	(x=0X3F0);
	op_hex		(x,	1);
	create_insn	(x=0X3FC);
	op_hex		(x,	1);
	create_insn	(x=0X3FE);
	op_hex		(x,	1);
	create_insn	(x=0X406);
	op_hex		(x,	1);
	create_insn	(x=0X415);
	op_hex		(x,	1);
	create_insn	(x=0X425);
	op_hex		(x,	1);
	create_insn	(x=0X42F);
	op_hex		(x,	1);
	create_insn	(0X448);
	set_name	(0X448,	"drv_fn04_hline");
	create_insn	(x=0X47C);
	op_hex		(x,	1);
	create_insn	(0X4A4);
	set_name	(0X4A4,	"drv_fn05_vline");
	create_insn	(x=0X4B4);
	op_hex		(x,	1);
	create_insn	(x=0X4B6);
	op_hex		(x,	1);
	create_insn	(x=0X4BE);
	op_hex		(x,	1);
	create_word	(0X4E2);
	create_word	(0X4E4);
	create_word	(0X4E6);
	create_word	(0X4E8);
	create_word	(0X4EA);
	create_word	(0X4EC);
	create_word	(0X4EE);
	create_word	(0X4F0);
	create_insn	(0X4F2);
	set_name	(0X4F2,	"drv_fn06_line");
	create_insn	(0X526);
	create_insn	(x=0X540);
	op_hex		(x,	1);
	create_insn	(0X586);
	set_name	(0X586,	"drv_fn01_select_page");
	create_insn	(0X59C);
	set_name	(0X59C,	"drv_fn0C_restore_rect");
	create_insn	(x=0X5A3);
	op_hex		(x,	1);
	create_insn	(x=0X5B8);
	op_hex		(x,	1);
	create_insn	(x=0X5CD);
	op_hex		(x,	1);
	set_cmt	(0X5CF,	"DOS - 2+ - FREE MEMORY\nES = segment address of area to be freed",	0);
	create_insn	(x=0X5CF);
	op_hex		(x,	0);
	create_word	(0X5D4);
	create_word	(0X5D6);
	create_word	(0X5D8);
	create_word	(0X5DA);
	create_insn	(0X5DC);
	set_name	(0X5DC,	"drv_fn0B_save_rect");
	create_insn	(x=0X5E7);
	op_hex		(x,	1);
	create_insn	(x=0X5E9);
	op_hex		(x,	1);
	create_insn	(x=0X608);
	op_hex		(x,	1);
	create_insn	(x=0X60A);
	op_hex		(x,	1);
	create_insn	(x=0X60C);
	op_hex		(x,	1);
	create_insn	(x=0X60E);
	op_hex		(x,	1);
	create_insn	(x=0X614);
	op_hex		(x,	1);
	set_cmt	(0X616,	"DOS - 2+ - ALLOCATE MEMORY\nBX = number of 16-byte paragraphs desired",	0);
	create_insn	(x=0X616);
	op_hex		(x,	0);
	create_insn	(x=0X63D);
	op_hex		(x,	1);
	create_insn	(0X654);
	set_name	(0X654,	"drv_fn08_copy_rect_pages");
	create_insn	(x=0X676);
	op_hex		(x,	1);
	create_insn	(x=0X67C);
	op_hex		(x,	1);
	create_insn	(0X6BC);
	set_name	(0X6BC,	"drv_fn09_copy_page");
	create_insn	(x=0X6D2);
	op_hex		(x,	1);
	create_insn	(0X6E8);
	set_name	(0X6E8,	"drv_fn0A_page_op");
	create_insn	(x=0X6FE);
	op_hex		(x,	1);
	create_insn	(0X71C);
	set_name	(0X71C,	"drv_fn18");
	create_word	(0X722);
	create_word	(0X724);
	create_word	(0X726);
	create_insn	(0X728);
	set_name	(0X728,	"drv_fn0E_scroll_rect_b");
	create_insn	(0X738);
	create_insn	(x=0X763);
	op_hex		(x,	1);
	create_insn	(x=0X777);
	op_hex		(x,	1);
	create_insn	(x=0X779);
	op_hex		(x,	1);
	create_insn	(x=0X7B9);
	op_hex		(x,	1);
	create_insn	(0X7CB);
	set_name	(0X7CB,	"drv_fn0D_scroll_rect_a");
	create_word	(0X7CC);
	create_word	(0X7CE);
	create_word	(0X7D0);
	create_insn	(0X7D2);
	set_name	(0X7D2,	"drv_fn13_draw_image");
	create_insn	(x=0X7D9);
	op_hex		(x,	1);
	create_insn	(x=0X7DB);
	op_hex		(x,	1);
	create_insn	(x=0X7E8);
	op_hex		(x,	1);
	create_insn	(x=0X7F9);
	op_hex		(x,	1);
	create_insn	(x=0X806);
	op_hex		(x,	1);
	create_insn	(x=0X821);
	op_hex		(x,	1);
	create_insn	(x=0X82A);
	op_hex		(x,	1);
	create_insn	(x=0X831);
	op_hex		(x,	1);
	create_insn	(x=0X83B);
	op_hex		(x,	1);
	create_word	(0X850);
	create_insn	(0X852);
	create_insn	(x=0X85D);
	op_hex		(x,	1);
	create_insn	(x=0X882);
	op_hex		(x,	1);
	create_insn	(x=0X8A7);
	op_hex		(x,	1);
	create_insn	(x=0X8B1);
	op_hex		(x,	1);
	create_insn	(x=0X8CA);
	op_hex		(x,	1);
	create_insn	(x=0X8CF);
	op_hex		(x,	1);
	create_insn	(0X8E8);
	create_byte	(0X8FA);
	create_byte	(0X8FB);
	create_byte	(0X8FC);
	create_insn	(0X8FE);
	set_name	(0X8FE,	"drv_fn15_put_char");
	create_insn	(x=0X907);
	op_hex		(x,	1);
	create_insn	(x=0X943);
	op_hex		(x,	1);
	create_insn	(x=0X945);
	op_hex		(x,	1);
	create_insn	(x=0X95D);
	op_hex		(x,	1);
	create_insn	(x=0X969);
	op_hex		(x,	1);
	create_insn	(x=0X981);
	op_hex		(x,	1);
	create_insn	(x=0X9A6);
	op_hex		(x,	1);
	create_insn	(0X9E0);
	set_name	(0X9E0,	"drv_fn10_load_image");
	create_insn	(0X9E2);
	set_name	(0X9E2,	"drv_fn12_draw_op12");
	create_insn	(x=0X9F4);
	op_hex		(x,	1);
	create_insn	(x=0X9FB);
	op_hex		(x,	1);
	create_insn	(0XA0E);
	set_name	(0XA0E,	"drv_fn0F_load_res_a");
	create_insn	(0XA14);
	set_name	(0XA14,	"drv_fn14_draw_image_alt");
	create_insn	(0XA15);
	set_name	(0XA15,	"drv_fn1F");
	create_word	(0XA26);
	create_word	(0XA28);
	create_word	(0XA2A);
	create_insn	(0XA2C);
	set_name	(0XA2C,	"drv_fn16_monster_setup");
	create_insn	(x=0XA5F);
	op_hex		(x,	1);
	set_cmt	(0XA61,	"DOS - 2+ - ALLOCATE MEMORY\nBX = number of 16-byte paragraphs desired",	0);
	create_insn	(x=0XA61);
	op_hex		(x,	0);
	create_insn	(x=0XA79);
	op_hex		(x,	1);
	create_insn	(0XAC7);
	create_insn	(0XAD5);
	create_insn	(x=0XAE1);
	op_hex		(x,	1);
	create_insn	(x=0XAF4);
	op_hex		(x,	1);
	set_cmt	(0XAF6,	"DOS - 2+ - FREE MEMORY\nES = segment address of area to be freed",	0);
	create_insn	(x=0XAF6);
	op_hex		(x,	0);
	create_insn	(x=0XAFE);
	op_hex		(x,	1);
	set_cmt	(0XB00,	"DOS - 2+ - FREE MEMORY\nES = segment address of area to be freed",	0);
	create_insn	(x=0XB00);
	op_hex		(x,	0);
	create_byte	(0XB04);
	create_byte	(0XB05);
	create_word	(0XB06);
	create_word	(0XB08);
	create_word	(0XB0A);
	create_insn	(0XB0C);
	create_insn	(x=0XB16);
	op_hex		(x,	1);
	create_insn	(x=0XB2A);
	op_plain_offset	(x,	1,	0);
	op_plain_offset	(x,	129,	0);
	create_insn	(x=0XB41);
	op_hex		(x,	1);
	create_insn	(x=0XB57);
	op_hex		(x,	1);
	create_insn	(x=0XB88);
	op_hex		(x,	1);
	create_insn	(x=0XB8C);
	op_hex		(x,	1);
	create_insn	(x=0XB8E);
	op_hex		(x,	1);
	create_insn	(x=0XB90);
	op_hex		(x,	1);
	create_insn	(x=0XB92);
	op_hex		(x,	1);
	create_insn	(x=0XB94);
	op_hex		(x,	1);
	create_insn	(x=0XB96);
	op_hex		(x,	1);
	create_insn	(x=0XB9C);
	op_hex		(x,	1);
	create_insn	(x=0XBD0);
	op_hex		(x,	1);
	create_insn	(x=0XBD6);
	op_hex		(x,	1);
	create_insn	(x=0XBDB);
	op_hex		(x,	1);
	create_insn	(x=0XBE0);
	op_hex		(x,	1);
	create_insn	(0XBE5);
	create_insn	(x=0XBE7);
	op_hex		(x,	1);
	create_insn	(x=0XBEC);
	op_hex		(x,	1);
	create_insn	(x=0XBEE);
	op_hex		(x,	1);
	create_insn	(x=0XBF0);
	op_hex		(x,	1);
	create_insn	(x=0XBF2);
	op_hex		(x,	1);
	create_insn	(x=0XBF4);
	op_hex		(x,	1);
	create_insn	(x=0XBFE);
	op_hex		(x,	1);
	create_insn	(0XC10);
	create_insn	(0XC18);
	set_name	(0XC18,	"drv_fn17_monster_draw");
	create_insn	(x=0XC29);
	op_hex		(x,	1);
	set_cmt	(0XC2B,	"DOS - 2+ - FREE MEMORY\nES = segment address of area to be freed",	0);
	create_insn	(x=0XC2B);
	op_hex		(x,	0);
	create_insn	(0XC37);
	create_insn	(x=0XC54);
	op_hex		(x,	1);
	create_insn	(x=0XC57);
	op_hex		(x,	1);
}

static Functions_0(void) {

	add_func    (0X2AA,0X2D8);
	set_func_flags(0X2AA,0x5000);
	set_frame_size(0X2AA, 0, 0, 0);
	add_func    (0X2E7,0X2F8);
	set_func_flags(0X2E7,0x1401);
	add_func    (0X300,0X35E);
	set_func_flags(0X300,0x5402);
	set_frame_size(0X300, 0, 0, 0);
	add_func    (0X35E,0X376);
	set_func_flags(0X35E,0x5402);
	set_frame_size(0X35E, 0, 0, 0);
	add_func    (0X376,0X38A);
	set_func_flags(0X376,0x5402);
	set_frame_size(0X376, 0, 0, 0);
	add_func    (0X38A,0X3C5);
	set_func_flags(0X38A,0x5400);
	set_frame_size(0X38A, 0X4, 0, 0);
	add_func    (0X3C6,0X3EE);
	set_func_flags(0X3C6,0x5402);
	set_frame_size(0X3C6, 0, 0, 0);
	add_func    (0X3F0,0X448);
	set_func_flags(0X3F0,0x5400);
	set_frame_size(0X3F0, 0, 0, 0);
	add_func    (0X448,0X4A4);
	set_func_flags(0X448,0x5402);
	set_frame_size(0X448, 0, 0, 0);
	add_func    (0X4A4,0X4E2);
	set_func_flags(0X4A4,0x5402);
	set_frame_size(0X4A4, 0, 0, 0);
	add_func    (0X4F2,0X586);
	set_func_flags(0X4F2,0x5402);
	set_frame_size(0X4F2, 0, 0, 0);
	add_func    (0X586,0X59C);
	set_func_flags(0X586,0x5402);
	set_frame_size(0X586, 0, 0, 0);
	add_func    (0X59C,0X5D3);
	set_func_flags(0X59C,0x5402);
	set_frame_size(0X59C, 0, 0, 0);
	add_func    (0X5DC,0X653);
	set_func_flags(0X5DC,0x5402);
	set_frame_size(0X5DC, 0, 0, 0);
	add_func    (0X654,0X6BB);
	set_func_flags(0X654,0x5402);
	set_frame_size(0X654, 0, 0, 0);
	add_func    (0X6BC,0X6E8);
	set_func_flags(0X6BC,0x5402);
	set_frame_size(0X6BC, 0, 0, 0);
	add_func    (0X6E8,0X71C);
	set_func_flags(0X6E8,0x5402);
	set_frame_size(0X6E8, 0, 0, 0);
	add_func    (0X71C,0X721);
	set_func_flags(0X71C,0x5402);
	set_frame_size(0X71C, 0, 0, 0);
	add_func    (0X728,0X7CB);
	set_func_flags(0X728,0x5400);
	set_frame_size(0X728, 0X2, 0, 0);
	add_func    (0X7CB,0X7CC);
	set_func_flags(0X7CB,0x5442);
	set_frame_size(0X7CB, 0, 0, 0);
	add_func    (0X7D2,0X8E9);
	set_func_flags(0X7D2,0x5402);
	set_frame_size(0X7D2, 0, 0, 0);
	add_func    (0X8FE,0X9E0);
	set_func_flags(0X8FE,0x5402);
	set_frame_size(0X8FE, 0, 0, 0);
	add_func    (0X9E0,0X9E1);
	set_func_flags(0X9E0,0x5442);
	set_frame_size(0X9E0, 0, 0, 0);
	add_func    (0X9E2,0XA0E);
	set_func_flags(0X9E2,0x5402);
	set_frame_size(0X9E2, 0, 0, 0);
	add_func    (0XA0E,0XA13);
	set_func_flags(0XA0E,0x5402);
	set_frame_size(0XA0E, 0, 0, 0);
	add_func    (0XA14,0XA15);
	set_func_flags(0XA14,0x5442);
	set_frame_size(0XA14, 0, 0, 0);
	add_func    (0XA15,0XA16);
	set_func_flags(0XA15,0x5442);
	set_frame_size(0XA15, 0, 0, 0);
	add_func    (0XA2C,0XB04);
	set_func_flags(0XA2C,0x5402);
	set_frame_size(0XA2C, 0, 0, 0);
	add_func    (0XB0C,0XC18);
	set_func_flags(0XB0C,0x5400);
	set_frame_size(0XB0C, 0XA, 0, 0);
	add_func    (0XC18,0XC6C);
	set_func_flags(0XC18,0x5402);
	set_frame_size(0XC18, 0, 0, 0);
}

//------------------------------------------------------------------------
// Information about functions

static Functions(void) {

	Functions_0();
}

//------------------------------------------------------------------------
// Information about segment registers

static SegRegs(void) {
	split_sreg_range(0,"es",0,3);
	split_sreg_range(0X2C8,"es",0,3);
	split_sreg_range(0X2CD,"es",0,3);
	split_sreg_range(0X325,"es",0,3);
	split_sreg_range(0X330,"es",0,3);
	split_sreg_range(0X392,"es",0,3);
	split_sreg_range(0X3CB,"es",0,3);
	split_sreg_range(0X459,"es",0,3);
	split_sreg_range(0X4B2,"es",0,3);
	split_sreg_range(0X5B4,"es",0,3);
	split_sreg_range(0X5CD,"es",0,3);
	split_sreg_range(0X5D2,"es",0,3);
	split_sreg_range(0X61D,"es",0,3);
	split_sreg_range(0X674,"es",0,3);
	split_sreg_range(0X6CE,"es",0,3);
	split_sreg_range(0X6FA,"es",0,3);
	split_sreg_range(0X75E,"es",0,3);
	split_sreg_range(0X7D9,"es",0,3);
	split_sreg_range(0X952,"es",0,3);
	split_sreg_range(0X9E7,"es",0,3);
	split_sreg_range(0XA2E,"es",0,3);
	split_sreg_range(0XA65,"es",0,3);
	split_sreg_range(0XA97,"es",0,3);
	split_sreg_range(0XAA2,"es",0,3);
	split_sreg_range(0XAB8,"es",0,3);
	split_sreg_range(0XAC9,"es",0,3);
	split_sreg_range(0XADA,"es",0,3);
	split_sreg_range(0XAF4,"es",0,3);
	split_sreg_range(0XAF9,"es",0,3);
	split_sreg_range(0XAFE,"es",0,3);
	split_sreg_range(0XB03,"es",0,3);
	split_sreg_range(0XB36,"es",0,3);
	split_sreg_range(0XC11,"es",0,3);
	split_sreg_range(0XC29,"es",0,3);
	split_sreg_range(0XC2E,"es",0,3);
	split_sreg_range(0XC54,"es",0XB800,3);
	split_sreg_range(0,"ss",0,3);
	split_sreg_range(0,"ds",0,3);
	split_sreg_range(0X2D7,"ds",0,3);
	split_sreg_range(0X2F1,"ds",0,3);
	split_sreg_range(0X30B,"ds",0X50,3);
	split_sreg_range(0X59E,"ds",0,3);
	split_sreg_range(0X622,"ds",0,3);
	split_sreg_range(0X675,"ds",0,3);
	split_sreg_range(0X6CC,"ds",0,3);
	split_sreg_range(0X6F8,"ds",0,3);
	split_sreg_range(0X759,"ds",0,3);
	split_sreg_range(0X7D4,"ds",0,3);
	split_sreg_range(0X911,"ds",0,3);
	split_sreg_range(0X9EC,"ds",0,3);
	split_sreg_range(0XA35,"ds",0,3);
	split_sreg_range(0XA73,"ds",0XB800,3);
	split_sreg_range(0XA92,"ds",0,3);
	split_sreg_range(0XAA3,"ds",0,3);
	split_sreg_range(0XAB6,"ds",0,3);
	split_sreg_range(0XACA,"ds",0,3);
	split_sreg_range(0XB31,"ds",0,3);
	split_sreg_range(0XB39,"ds",0,3);
	split_sreg_range(0XB7B,"ds",0,3);
	split_sreg_range(0XB80,"ds",0,3);
	split_sreg_range(0XB86,"ds",0,3);
	split_sreg_range(0XC12,"ds",0,3);
	split_sreg_range(0XC4D,"ds",0,3);
	split_sreg_range(0,"fs",0,3);
	split_sreg_range(0,"gs",0,3);
}

//------------------------------------------------------------------------
// Information about all patched bytes:

static Patches(void) {
}

//------------------------------------------------------------------------
// Call all byte feature functions:

static Bytes(void) {
	Bytes_0();
        end_type_updating(UTP_STRUCT);
}

// End of file.
