;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-337F-7354-97                      |
; |                       Paul Gilbert, ScummVM Team                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 15B89202C95A5B1097EB4C35DEF1713278BE506A90F89D0255C24363746D5820
; Input MD5    : 46C502588BBE94B6CC11B5F4C1E70447
; Input CRC32  : 5A52BBEE

; ---------------------------------------------------------------------------
; File Name   : C:\dev\might_and_magic\mm2\drv\TGA.DRV
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 0C6Ch Loaded length: 0C6Ch

                .686p
                .mmx
                .model flat

; ===========================================================================

; Segment type: Pure code
drv             segment byte public 'CODE' use16
                assume cs:drv
                assume es:nothing, ss:nothing, ds:nothing, fs:nothing, gs:nothing

entry_00:
                jmp     near ptr drv_fn00_reset
; ---------------------------------------------------------------------------

entry_01:
                jmp     near ptr drv_fn01_select_page
; ---------------------------------------------------------------------------

entry_02:
                jmp     near ptr drv_fn02_set_color
; ---------------------------------------------------------------------------

entry_03:
                jmp     near ptr drv_fn03_plot_point
; ---------------------------------------------------------------------------

entry_04:
                jmp     near ptr drv_fn04_hline
; ---------------------------------------------------------------------------

entry_05:
                jmp     near ptr drv_fn05_vline
; ---------------------------------------------------------------------------

entry_06:
                jmp     near ptr drv_fn06_line
; ---------------------------------------------------------------------------

entry_07:
                jmp     near ptr drv_fn07_get_pixel
; ---------------------------------------------------------------------------

entry_08:
                jmp     near ptr drv_fn08_copy_rect_pages
; ---------------------------------------------------------------------------

entry_09:
                jmp     near ptr drv_fn09_copy_page
; ---------------------------------------------------------------------------

entry_0A:
                jmp     near ptr drv_fn0A_page_op
; ---------------------------------------------------------------------------

entry_0B:
                jmp     near ptr drv_fn0B_save_rect
; ---------------------------------------------------------------------------

entry_0C:
                jmp     near ptr drv_fn0C_restore_rect
; ---------------------------------------------------------------------------

entry_0D:
                jmp     near ptr drv_fn0D_scroll_rect_a
; ---------------------------------------------------------------------------

entry_0E:
                jmp     drv_fn0E_scroll_rect_b
; ---------------------------------------------------------------------------

entry_0F:
                jmp     near ptr drv_fn0F_load_res_a
; ---------------------------------------------------------------------------

entry_10:
                jmp     near ptr drv_fn10_load_image
; ---------------------------------------------------------------------------

entry_11:
                jmp     near ptr drv_fn14_draw_image_alt
; ---------------------------------------------------------------------------

entry_12:
                jmp     near ptr drv_fn12_draw_op12
; ---------------------------------------------------------------------------

entry_13:
                jmp     near ptr drv_fn13_draw_image
; ---------------------------------------------------------------------------

entry_14:
                jmp     near ptr drv_fn14_draw_image_alt
; ---------------------------------------------------------------------------

entry_15:                               ; DATA XREF: sub_2E7+3↓r
                                        ; drv_fn00_reset+1E↓r
                jmp     near ptr drv_fn15_put_char
; ---------------------------------------------------------------------------

entry_16:
                jmp     near ptr drv_fn16_monster_setup
; ---------------------------------------------------------------------------

entry_17:
                jmp     near ptr drv_fn17_monster_draw
; ---------------------------------------------------------------------------

entry_18:
                jmp     near ptr drv_fn18
; ---------------------------------------------------------------------------

entry_19:
                jmp     near ptr drv_fn1F
; ---------------------------------------------------------------------------

entry_1A:
                jmp     near ptr drv_fn1F
; ---------------------------------------------------------------------------

entry_1B:
                jmp     near ptr drv_fn1F
; ---------------------------------------------------------------------------

entry_1C:
                jmp     near ptr drv_fn1F
; ---------------------------------------------------------------------------

entry_1D:
                jmp     near ptr drv_fn1F
; ---------------------------------------------------------------------------

entry_1E:
                jmp     near ptr drv_fn1F
; ---------------------------------------------------------------------------

entry_1F:
                jmp     near ptr drv_fn1F
; ---------------------------------------------------------------------------
                db    0
                db    0
                db    0
                db    0
word_64         dw 0                    ; DATA XREF: drv_fn12_draw_op12+5↓r
                                        ; drv_fn0F_load_res_a↓w
                db 0FFh
                db 0FFh
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
unk_84          db    0                 ; DATA XREF: sub_2AA+7↓r
                                        ; sub_2AA+10↓r ...
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db  0Fh
                db 0F0h
                db    0
                db  0Fh
                db 0F0h
                db 0FFh
byte_29E        db 0                    ; DATA XREF: drv_fn02_set_color+A↓w
byte_29F        db 0                    ; DATA XREF: drv_fn02_set_color+2↓w
                                        ; drv_fn02_set_color+E↓r
byte_2A0        db 0                    ; DATA XREF: drv_fn02_set_color+13↓w
                                        ; drv_fn04_hline+1F↓r ...
                db  90h
word_2A2        dw 0                    ; DATA XREF: drv_fn01_select_page+11↓w
                                        ; drv_fn18↓r
word_2A4        dw 0B800h               ; DATA XREF: sub_38A+3↓r
                                        ; drv_fn07_get_pixel↓r ...
word_2A6        dw 0                    ; DATA XREF: drv_fn00_reset+16↓w
                                        ; drv_fn00_reset+20↓r ...
word_2A8        dw 0                    ; DATA XREF: drv_fn03_plot_point+2↓w
                                        ; drv_fn03_plot_point+C↓w ...

; =============== S U B R O U T I N E =======================================


sub_2AA         proc near               ; CODE XREF: drv_fn00_reset+3↓p
                                        ; drv_fn00_reset+13↓p ...
                push    ds
                push    bx
                mov     bx, 0FFFFh
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     ax
                push    ax
                inc     ax
                sub     bx, ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                push    ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                push    ax
                pushf
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                popf
                pop     bx
                jnb     short loc_2D6
                call    sub_2E7
; ---------------------------------------------------------------------------
                xor     bx, bx

loc_2D6:                                ; CODE XREF: sub_2AA+25↑j
                pop     ds
                retn
sub_2AA         endp

; ---------------------------------------------------------------------------
                db  4Fh ; O
                db  75h ; u
                db  74h ; t
                db  20h
                db  6Fh ; o
                db  66h ; f
                db  20h
                db  4Dh ; M
                db  65h ; e
                db  6Dh ; m
                db  6Fh ; o
                db  72h ; r
                db  79h ; y
                db  0Dh
                db  0Ah

; =============== S U B R O U T I N E =======================================

; Attributes: noreturn

sub_2E7         proc near               ; CODE XREF: sub_2AA+27↑p
                mov     ax, 3
                int     10h             ; - VIDEO - SET VIDEO MODE
                                        ; AL = mode
                mov     dx, 2D8h
                push    cs
                pop     ds
                int     21h             ; DOS -
                mov     ax, 4C01h
                int     21h             ; DOS - 2+ - QUIT WITH EXIT CODE (EXIT)
sub_2E7         endp                    ; AL = exit code

; ---------------------------------------------------------------------------
                db    0
                db    0
                db    0
                db  20h
                db    0
                db  40h ; @
                db    0
                db  60h ; `

; =============== S U B R O U T I N E =======================================


drv_fn00_reset  proc far                ; CODE XREF: drv:entry_00↑j
                mov     bx, 400h
                call    sub_2AA
                mov     ax, 50h ; 'P'
                mov     ds, ax
                assume ds:nothing
                mov     si, 10h
                mov     [si], bx
                mov     bx, 800h
                call    sub_2AA
                mov     cs:word_2A6, bx
                mov     ax, 9
                int     10h             ; - VIDEO - SET VIDEO MODE
                                        ; AL = mode
                mov     es, cs:word_2A6
                xor     di, di
                xor     ax, ax
                mov     cx, 4000h
                rep stosw
                push    cs
                pop     es
                mov     cx, 0C7h
                mov     di, 1F6h
                std

loc_337:                                ; CODE XREF: drv_fn00_reset+5A↓j
                mov     dx, cx
                mov     bx, dx
                and     bx, 3
                shl     bx, 1
                mov     ax, cs:[bx+2F8h]
                mov     bx, dx
                and     bx, 1FCh
                mov     cl, 3
                shl     bx, cl
                add     ax, bx
                dec     cl
                shl     bx, cl
                add     ax, bx
                stosw
                mov     cx, dx
                loop    loc_337
                cld
                retf
drv_fn00_reset  endp


; =============== S U B R O U T I N E =======================================


drv_fn02_set_color proc far             ; CODE XREF: drv:entry_02↑j
                and     al, 0Fh
                mov     cs:byte_29F, al
                mov     cl, 4
                shl     al, cl
                mov     cs:byte_29E, al
                or      al, cs:byte_29F
                mov     cs:byte_2A0, al
                retf
drv_fn02_set_color endp


; =============== S U B R O U T I N E =======================================


drv_fn03_plot_point proc far            ; CODE XREF: drv:entry_03↑j
                jnb     short loc_37F
                mov     cs:word_2A8, 1

loc_37F:                                ; CODE XREF: drv_fn03_plot_point↑j
                call    sub_38A
                mov     cs:word_2A8, 0
                retf
drv_fn03_plot_point endp


; =============== S U B R O U T I N E =======================================


sub_38A         proc near               ; CODE XREF: drv_fn03_plot_point:loc_37F↑p
                                        ; drv_fn06_line+62↓p
                push    ax
                push    bx
                push    cx
                mov     es, cs:word_2A4
                shl     bx, 1
                mov     bx, cs:[bx+68h]
                mov     si, ax
                shr     ax, 1
                add     bx, ax
                mov     al, es:[bx]
                and     si, 1
                cmp     cs:word_2A8, 0
                jnz     short loc_3B9
                and     al, cs:[si+298h]
                or      al, cs:[si+29Eh]
                jmp     short loc_3BE
; ---------------------------------------------------------------------------

loc_3B9:                                ; CODE XREF: sub_38A+21↑j
                xor     al, cs:[si+29Eh]

loc_3BE:                                ; CODE XREF: sub_38A+2D↑j
                mov     es:[bx], al
                pop     cx
                pop     bx
                pop     ax
                retn
sub_38A         endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn07_get_pixel proc far             ; CODE XREF: drv:entry_07↑j
                mov     es, cs:word_2A4
                shl     bx, 1
                mov     bx, cs:[bx+68h]
                mov     si, ax
                and     si, 1
                shr     ax, 1
                add     bx, ax
                mov     ah, es:[bx]
                or      si, si
                jnz     short loc_3E6
                mov     cl, 4
                shr     ah, cl

loc_3E6:                                ; CODE XREF: drv_fn07_get_pixel+1A↑j
                and     ah, 0Fh
                mov     al, ah
                xor     ah, ah
                retf
drv_fn07_get_pixel endp

; ---------------------------------------------------------------------------
byte_3EE        db 0                    ; DATA XREF: sub_3F0+1F↓w
                                        ; sub_3F0+29↓w ...
byte_3EF        db 0                    ; DATA XREF: sub_3F0:loc_41F↓w
                                        ; sub_3F0+39↓w ...

; =============== S U B R O U T I N E =======================================


sub_3F0         proc near               ; CODE XREF: drv_fn04_hline:loc_451↓p
                                        ; drv_fn08_copy_rect_pages+1A↓p ...
                shl     bx, 1
                mov     bx, cs:[bx+68h]
                mov     si, ax
                mov     di, cx
                push    di
                shr     si, 1
                shr     di, 1
                cmp     si, di
                pop     di
                pushf
                mov     si, ax
                shr     ax, 1
                add     bx, ax
                mov     dx, di
                sub     dx, si
                inc     dx
                mov     cs:byte_3EE, 0
                shr     si, 1
                jnb     short loc_41F
                mov     cs:byte_3EE, 0F0h

loc_41F:                                ; CODE XREF: sub_3F0+27↑j
                mov     cs:byte_3EF, 0
                shr     di, 1
                jb      short loc_42F
                mov     cs:byte_3EF, 0Fh

loc_42F:                                ; CODE XREF: sub_3F0+37↑j
                shr     dx, 1
                mov     cx, dx
                popf
                jnz     short locret_447
                xor     cx, cx
                mov     al, cs:byte_3EF
                and     cs:byte_3EE, al
                mov     cs:byte_3EF, 0

locret_447:                             ; CODE XREF: sub_3F0+44↑j
                retn
sub_3F0         endp


; =============== S U B R O U T I N E =======================================


drv_fn04_hline  proc far                ; CODE XREF: drv:entry_04↑j
                jnb     short loc_451
                mov     cs:word_2A8, 1

loc_451:                                ; CODE XREF: drv_fn04_hline↑j
                call    sub_3F0
                mov     es, cs:word_2A4
                mov     di, bx
                mov     ah, cs:byte_3EE
                or      ah, ah
                jz      short loc_474
                mov     dl, es:[di]
                mov     al, cs:byte_2A0
                and     dl, ah
                not     ah
                and     al, ah
                or      al, dl
                stosb

loc_474:                                ; CODE XREF: drv_fn04_hline+1A↑j
                jcxz    short loc_483
                mov     al, cs:byte_2A0
                mov     ah, al
                shr     cx, 1
                rep stosw
                jnb     short loc_483
                stosb

loc_483:                                ; CODE XREF: drv_fn04_hline:loc_474↑j
                                        ; drv_fn04_hline+38↑j
                mov     ah, cs:byte_3EF
                or      ah, ah
                jz      short loc_49C
                mov     dl, es:[di]
                mov     al, cs:byte_2A0
                and     dl, ah
                not     ah
                and     al, ah
                or      al, dl
                stosb

loc_49C:                                ; CODE XREF: drv_fn04_hline+42↑j
                mov     cs:word_2A8, 0
                retf
drv_fn04_hline  endp


; =============== S U B R O U T I N E =======================================


drv_fn05_vline  proc far                ; CODE XREF: drv:entry_05↑j
                jnb     short loc_4AD
                mov     cs:word_2A8, 1

loc_4AD:                                ; CODE XREF: drv_fn05_vline↑j
                mov     es, cs:word_2A4
                mov     si, ax
                shr     ax, 1
                and     si, 1
                sub     cx, bx
                inc     cx

loc_4BC:                                ; CODE XREF: drv_fn05_vline+34↓j
                mov     di, bx
                shl     di, 1
                mov     di, cs:[di+68h]
                add     di, ax
                mov     dl, es:[di]
                and     dl, cs:[si+298h]
                or      dl, cs:[si+29Eh]
                mov     es:[di], dl
                inc     bx
                loop    loc_4BC
                mov     cs:word_2A8, 0
                retf
drv_fn05_vline  endp

; ---------------------------------------------------------------------------
word_4E2        dw 0                    ; DATA XREF: drv_fn06_line:loc_517↓w
                                        ; drv_fn06_line:loc_56D↓r
word_4E4        dw 0                    ; DATA XREF: drv_fn06_line:loc_50A↓w
                                        ; drv_fn06_line+80↓r
word_4E6        dw 0                    ; DATA XREF: drv_fn06_line+5A↓w
                                        ; drv_fn06_line+85↓r
word_4E8        dw 0                    ; DATA XREF: drv_fn06_line+40↓w
                                        ; drv_fn06_line+6A↓r
word_4EA        dw 0                    ; DATA XREF: drv_fn06_line+45↓w
                                        ; drv_fn06_line+6F↓r
word_4EC        dw 0                    ; DATA XREF: drv_fn06_line+50↓w
                                        ; drv_fn06_line+74↓r
word_4EE        dw 0                    ; DATA XREF: drv_fn06_line:loc_528↓w
word_4F0        dw 0                    ; DATA XREF: drv_fn06_line+3B↓w
                                        ; drv_fn06_line+4A↓r

; =============== S U B R O U T I N E =======================================


drv_fn06_line   proc far                ; CODE XREF: drv:entry_06↑j
                jnb     short loc_4FB
                mov     cs:word_2A8, 1

loc_4FB:                                ; CODE XREF: drv_fn06_line↑j
                mov     si, 1
                mov     di, si
                push    bx
                push    ax
                sub     dx, bx
                jge     short loc_50A
                neg     di
                neg     dx

loc_50A:                                ; CODE XREF: drv_fn06_line+12↑j
                mov     cs:word_4E4, di
                sub     cx, ax
                jge     short loc_517
                neg     si
                neg     cx

loc_517:                                ; CODE XREF: drv_fn06_line+1F↑j
                mov     cs:word_4E2, si
                cmp     cx, dx
                jge     short loc_526
                xor     si, si
                xchg    cx, dx
                jmp     short loc_528
; ---------------------------------------------------------------------------

loc_526:                                ; CODE XREF: drv_fn06_line+2C↑j
                xor     di, di

loc_528:                                ; CODE XREF: drv_fn06_line+32↑j
                mov     cs:word_4EE, cx
                mov     cs:word_4F0, dx
                mov     cs:word_4E8, si
                mov     cs:word_4EA, di
                mov     ax, cs:word_4F0
                shl     ax, 1
                mov     cs:word_4EC, ax
                sub     ax, cx
                mov     dx, ax
                sub     ax, cx
                mov     cs:word_4E6, ax
                inc     cx
                pop     ax
                pop     bx

loc_553:                                ; CODE XREF: drv_fn06_line+79↓j
                                        ; drv_fn06_line+8A↓j
                push    dx
                call    sub_38A
                pop     dx
                or      dx, dx
                jns     short loc_56D
                add     ax, cs:word_4E8
                add     bx, cs:word_4EA
                add     dx, cs:word_4EC
                loop    loc_553

loc_56D:                                ; CODE XREF: drv_fn06_line+68↑j
                add     ax, cs:word_4E2
                add     bx, cs:word_4E4
                add     dx, cs:word_4E6
                loop    loc_553
                mov     cs:word_2A8, 0
                retf
drv_fn06_line   endp


; =============== S U B R O U T I N E =======================================


drv_fn01_select_page proc far           ; CODE XREF: drv:entry_01↑j
                mov     bx, 0B800h
                or      ax, ax
                jz      short loc_592
                mov     bx, cs:word_2A6

loc_592:                                ; CODE XREF: drv_fn01_select_page+5↑j
                mov     cs:word_2A4, bx
                mov     cs:word_2A2, ax
                retf
drv_fn01_select_page endp


; =============== S U B R O U T I N E =======================================


drv_fn0C_restore_rect proc far          ; CODE XREF: drv:entry_0C↑j
                mov     ds, ax
                assume ds:nothing
                xor     si, si
                lodsw
                mov     di, ax
                shr     di, 1
                lodsw
                push    ax
                lodsw
                mov     cx, ax
                lodsw
                mov     dx, ax
                mov     ax, di
                mov     es, cs:word_2A4
                pop     bx

loc_5B5:                                ; CODE XREF: drv_fn0C_restore_rect+2A↓j
                mov     di, bx
                inc     bx
                shl     di, 1
                mov     di, cs:[di+68h]
                add     di, ax
                push    cx
                rep movsb
                pop     cx
                dec     dx
                jnz     short loc_5B5
                push    es
                mov     bx, ds
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                retf
drv_fn0C_restore_rect endp

; ---------------------------------------------------------------------------
                db  90h
word_5D4        dw 0                    ; DATA XREF: drv_fn0B_save_rect↓w
                                        ; drv_fn0B_save_rect+49↓r
word_5D6        dw 0                    ; DATA XREF: drv_fn0B_save_rect+4↓w
                                        ; drv_fn0B_save_rect+4E↓r
word_5D8        dw 0                    ; DATA XREF: drv_fn0B_save_rect+17↓w
                                        ; drv_fn0B_save_rect+53↓r
word_5DA        dw 0                    ; DATA XREF: drv_fn0B_save_rect+1C↓w
                                        ; drv_fn0B_save_rect+5A↓r

; =============== S U B R O U T I N E =======================================


drv_fn0B_save_rect proc far             ; CODE XREF: drv:entry_0B↑j
                mov     cs:word_5D4, ax
                mov     cs:word_5D6, bx
                mov     si, cx
                shr     ax, 1
                shr     si, 1
                sub     si, ax
                inc     si
                sub     dx, bx
                mov     cx, dx
                inc     cx
                mov     cs:word_5D8, si
                mov     cs:word_5DA, cx
                mov     di, dx
                push    ax
                mov     ax, si
                cwd
                mul     cx
                add     ax, 8
                shr     ax, 1
                shr     ax, 1
                shr     ax, 1
                shr     ax, 1
                inc     ax
                push    bx
                mov     bx, ax
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                pop     bx
                jb      short loc_651
                mov     es, ax
                mov     ds, cs:word_2A4
                pop     dx
                xor     di, di
                mov     ax, cs:word_5D4
                stosw
                mov     ax, cs:word_5D6
                stosw
                mov     ax, cs:word_5D8
                mov     cx, ax
                stosw
                mov     ax, cs:word_5DA
                stosw

loc_63B:                                ; CODE XREF: drv_fn0B_save_rect+70↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+68h]
                add     si, dx
                push    cx
                rep movsb
                pop     cx
                inc     bx
                dec     ax
                jnz     short loc_63B
                mov     ax, es
                push    ax

loc_651:                                ; CODE XREF: drv_fn0B_save_rect+3D↑j
                pop     ax
                retf
drv_fn0B_save_rect endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn08_copy_rect_pages proc far       ; CODE XREF: drv:entry_08↑j
                or      ax, ax
                mov     ax, 0B800h
                mov     bx, cs:word_2A6
                jz      short loc_661
                xchg    ax, bx

loc_661:                                ; CODE XREF: drv_fn08_copy_rect_pages+A↑j
                push    dx
                push    ax
                push    bx
                push    cx
                mov     ax, cx
                mov     bx, dx
                mov     cx, si
                sub     di, dx
                push    di
                call    sub_3F0
                pop     ax
                pop     bx
                pop     es
                pop     ds
                pop     dx
                shr     bx, 1

loc_678:                                ; CODE XREF: drv_fn08_copy_rect_pages+64↓j
                push    ax
                push    cx
                mov     si, dx
                shl     si, 1
                mov     si, cs:[si+68h]
                add     si, bx
                mov     di, si
                mov     ah, cs:byte_3EE
                or      ah, ah
                jz      short loc_69C
                lodsb
                and     es:[di], ah
                not     ah
                and     al, ah
                or      es:[di], al
                inc     di

loc_69C:                                ; CODE XREF: drv_fn08_copy_rect_pages+3A↑j
                jcxz    short loc_6A0
                rep movsb

loc_6A0:                                ; CODE XREF: drv_fn08_copy_rect_pages:loc_69C↑j
                mov     ah, cs:byte_3EF
                or      ah, ah
                jz      short loc_6B4
                lodsb
                and     es:[di], ah
                not     ah
                and     al, ah
                or      es:[di], al

loc_6B4:                                ; CODE XREF: drv_fn08_copy_rect_pages+53↑j
                inc     dx
                pop     cx
                pop     ax
                dec     ax
                jns     short loc_678
                retf
drv_fn08_copy_rect_pages endp

; ---------------------------------------------------------------------------
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn09_copy_page proc far             ; CODE XREF: drv:entry_09↑j
                mov     si, 0B800h
                mov     di, cs:word_2A6
                or      ax, ax
                jz      short loc_6CA
                xchg    si, di

loc_6CA:                                ; CODE XREF: drv_fn09_copy_page+A↑j
                mov     ds, si
                mov     es, di
                xor     bx, bx

loc_6D0:                                ; CODE XREF: drv_fn09_copy_page+29↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+68h]
                mov     di, si
                mov     cx, 50h ; 'P'
                rep movsw
                inc     bx
                cmp     bx, 0C8h
                jl      short loc_6D0
                retf
drv_fn09_copy_page endp


; =============== S U B R O U T I N E =======================================


drv_fn0A_page_op proc far               ; CODE XREF: drv:entry_0A↑j
                mov     si, 0B800h
                mov     di, cs:word_2A6
                or      ax, ax
                jz      short loc_6F6
                xchg    si, di

loc_6F6:                                ; CODE XREF: drv_fn0A_page_op+A↑j
                mov     ds, si
                mov     es, di
                xor     bx, bx

loc_6FC:                                ; CODE XREF: drv_fn0A_page_op+31↓j
                mov     si, bx
                shl     si, 1
                mov     si, cs:[si+68h]
                mov     di, si
                mov     cx, 50h ; 'P'

loc_70A:                                ; CODE XREF: drv_fn0A_page_op+2A↓j
                lodsw
                mov     dx, es:[di]
                stosw
                mov     [si-2], dx
                loop    loc_70A
                inc     bx
                cmp     bx, 0C8h
                jl      short loc_6FC
                retf
drv_fn0A_page_op endp


; =============== S U B R O U T I N E =======================================


drv_fn18        proc far                ; CODE XREF: drv:entry_18↑j
                mov     ax, cs:word_2A2
                retf
drv_fn18        endp

; ---------------------------------------------------------------------------
                db  90h
word_722        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b↓w
                                        ; drv_fn0E_scroll_rect_b+44↓r ...
word_724        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b+36↓r
word_726        dw 0                    ; DATA XREF: drv_fn0E_scroll_rect_b:loc_73C↓w
                                        ; drv_fn0E_scroll_rect_b:loc_765↓r ...

; =============== S U B R O U T I N E =======================================


drv_fn0E_scroll_rect_b proc near        ; CODE XREF: drv:entry_0E↑j
                mov     cs:word_722, si
                push    si
                or      si, si
                js      short loc_738
                mov     di, dx
                sub     di, si
                jmp     short loc_73C
; ---------------------------------------------------------------------------

loc_738:                                ; CODE XREF: drv_fn0E_scroll_rect_b+8↑j
                mov     di, bx
                sub     di, si

loc_73C:                                ; CODE XREF: drv_fn0E_scroll_rect_b+E↑j
                mov     cs:word_726, di
                sub     dx, bx
                pop     di
                mov     bp, di
                or      di, di
                jns     short loc_74C
                neg     di

loc_74C:                                ; CODE XREF: drv_fn0E_scroll_rect_b+20↑j
                sub     dx, di
                inc     dx
                push    dx
                call    sub_3F0
                pop     dx
                mov     ds, cs:word_2A4
                mov     es, cs:word_2A4
                mov     bx, cs:word_724
                shr     bx, 1

loc_765:                                ; CODE XREF: drv_fn0E_scroll_rect_b+A1↓j
                mov     si, cs:word_726
                mov     di, si
                add     di, cs:word_722
                cmp     di, 0C8h
                jnb     short loc_7B4
                shl     si, 1
                shl     di, 1
                mov     si, cs:[si+68h]
                mov     di, cs:[di+68h]
                add     si, bx
                add     di, bx
                push    cx
                mov     ah, cs:byte_3EE
                or      ah, ah
                jz      short loc_79D
                lodsb
                and     [di], ah
                not     ah
                and     al, ah
                or      [di], al
                inc     di

loc_79D:                                ; CODE XREF: drv_fn0E_scroll_rect_b+69↑j
                jcxz    short loc_7A1
                rep movsb

loc_7A1:                                ; CODE XREF: drv_fn0E_scroll_rect_b:loc_79D↑j
                mov     ah, cs:byte_3EF
                or      ah, ah
                jz      short loc_7B3
                lodsb
                and     [di], ah
                not     ah
                and     al, ah
                or      [di], al

loc_7B3:                                ; CODE XREF: drv_fn0E_scroll_rect_b+80↑j
                pop     cx

loc_7B4:                                ; CODE XREF: drv_fn0E_scroll_rect_b+4D↑j
                inc     cs:word_726
                test    cs:word_722, 8000h
                js      short loc_7C8
                sub     cs:word_726, 2

loc_7C8:                                ; CODE XREF: drv_fn0E_scroll_rect_b+98↑j
                dec     dx
                jnz     short loc_765
drv_fn0E_scroll_rect_b endp

; [00000001 BYTES: COLLAPSED FUNCTION drv_fn0D_scroll_rect_a. PRESS NUMPAD+ TO EXPAND]
word_7CC        dw 0                    ; DATA XREF: drv_fn13_draw_image+11↓w
                                        ; drv_fn13_draw_image:loc_816↓r ...
word_7CE        dw 0                    ; DATA XREF: drv_fn13_draw_image+29↓w
                                        ; drv_fn13_draw_image+2E↓w ...
word_7D0        dw 0                    ; DATA XREF: drv_fn13_draw_image+22↓w
                                        ; drv_fn13_draw_image:loc_831↓r ...

; =============== S U B R O U T I N E =======================================


drv_fn13_draw_image proc far            ; CODE XREF: drv:entry_13↑j
                mov     ds, ax
                mov     es, cs:word_2A4
                shl     bx, 1
                shl     bx, 1
                mov     si, [bx+2]
                mov     bx, [bx+4]
                mov     cs:word_7CC, bx
                shr     cx, 1
                mov     bx, dx
                mov     dx, cx
                lodsw
                mov     cx, ax
                lodsw
                mov     bp, ax
                mov     cs:word_7D0, cx
                shr     cx, 1
                mov     cs:word_7CE, cx
                adc     cs:word_7CE, 0

loc_806:                                ; CODE XREF: drv_fn13_draw_image+42↓j
                test    cs:word_7CE, 3
                jz      short loc_816
                inc     cs:word_7CE
                jnz     short loc_806

loc_816:                                ; CODE XREF: drv_fn13_draw_image+3B↑j
                cmp     cs:word_7CC, 0
                jnz     short loc_852

loc_81E:                                ; CODE XREF: drv_fn13_draw_image+7A↓j
                push    cx
                push    bx
                push    si
                shl     bx, 1
                mov     di, cs:[bx+68h]
                add     di, dx
                shr     cx, 1
                rep movsw
                jnb     short loc_831
                movsb

loc_831:                                ; CODE XREF: drv_fn13_draw_image+5C↑j
                test    cs:word_7D0, 1
                jz      short loc_842
                lodsb
                and     byte ptr es:[di], 0Fh
                or      es:[di], al

loc_842:                                ; CODE XREF: drv_fn13_draw_image+66↑j
                pop     si
                pop     bx
                pop     cx
                add     si, cs:word_7CE
                inc     bx
                dec     bp
                jnz     short loc_81E
                retf
; ---------------------------------------------------------------------------
                db  90h
word_850        dw 0                    ; DATA XREF: drv_fn13_draw_image:loc_852↓w
                                        ; drv_fn13_draw_image+86↓r ...
; ---------------------------------------------------------------------------

loc_852:                                ; CODE XREF: drv_fn13_draw_image+4A↑j
                mov     cs:word_850, bx

loc_857:                                ; CODE XREF: drv_fn13_draw_image+113↓j
                push    si
                mov     bx, cs:word_850
                shl     bx, 1
                mov     di, cs:[bx+68h]
                add     di, dx
                push    cx
                mov     bx, cx

loc_869:                                ; CODE XREF: drv_fn13_draw_image+D3↓j
                mov     cl, 6
                push    si
                mov     si, cs:word_7CC
                mov     al, [si]
                mov     ah, al
                inc     cs:word_7CC
                pop     si

loc_87B:                                ; CODE XREF: drv_fn13_draw_image+D1↓j
                mov     al, ah
                push    si
                mov     si, ax
                shr     si, cl
                and     si, 3
                mov     al, cs:[si+29Ah]
                and     es:[di], al
                pop     si
                push    ax
                mov     ah, al
                lodsb
                not     ah
                and     al, ah
                or      es:[di], al
                inc     di
                pop     ax
                sub     cl, 2
                dec     bx
                jz      short loc_8A7
                or      cl, cl
                jns     short loc_87B
                js      short loc_869

loc_8A7:                                ; CODE XREF: drv_fn13_draw_image+CD↑j
                test    cs:word_7D0, 1
                jz      short loc_8D6
                lodsb
                and     al, 0F0h
                or      cl, cl
                jns     short loc_8C8
                mov     cl, 6
                push    di
                mov     di, cs:word_7CC
                mov     ah, es:[di]
                inc     cs:word_7CC
                pop     di

loc_8C8:                                ; CODE XREF: drv_fn13_draw_image+E3↑j
                shr     ah, cl
                test    ah, 2
                jnz     short loc_8D6
                and     byte ptr es:[di], 0Fh
                or      es:[di], al

loc_8D6:                                ; CODE XREF: drv_fn13_draw_image+DC↑j
                                        ; drv_fn13_draw_image+FB↑j
                pop     cx
                pop     si
                add     si, cs:word_7CE
                inc     cs:word_850
                dec     bp
                jz      short locret_8E8
                jmp     loc_857
; ---------------------------------------------------------------------------

locret_8E8:                             ; CODE XREF: drv_fn13_draw_image+111↑j
                retf
drv_fn13_draw_image endp

; ---------------------------------------------------------------------------
                db  90h
                db    0
                db  11h
                db  22h ; "
                db  33h ; 3
                db  44h ; D
                db  55h ; U
                db  66h ; f
                db  77h ; w
                db  88h
                db  99h
                db 0AAh
                db 0BBh
                db 0CCh
                db 0DDh
                db 0EEh
                db 0FFh
byte_8FA        db 0                    ; DATA XREF: drv_fn15_put_char+C↓w
                                        ; drv_fn15_put_char+5F↓r ...
byte_8FB        db 0                    ; DATA XREF: drv_fn15_put_char+1C↓w
                                        ; drv_fn15_put_char+BA↓r
byte_8FC        db 0                    ; DATA XREF: drv_fn15_put_char+21↓w
                                        ; drv_fn15_put_char+32↓w ...
                db    0

; =============== S U B R O U T I N E =======================================


drv_fn15_put_char proc far              ; CODE XREF: drv:entry_15↑j
                jnb     short loc_907
                mov     cs:word_2A8, 1

loc_907:                                ; CODE XREF: drv_fn15_put_char↑j
                and     dl, 0Fh
                mov     cs:byte_8FA, ah
                push    es
                pop     ds
                xor     bh, bh
                mov     bl, dl
                mov     dl, cs:[bx+8EAh]
                mov     cs:byte_8FB, dl
                mov     cs:byte_8FC, dh
                cmp     dh, 0FFh
                jz      short loc_935
                mov     bl, dh
                mov     dl, cs:[bx+8EAh]
                mov     cs:byte_8FC, dl

loc_935:                                ; CODE XREF: drv_fn15_put_char+29↑j
                mov     dl, ch
                xor     dh, dh
                mov     di, dx
                mov     bl, al
                mov     si, bx
                mov     dl, cl
                xor     dh, dh
                shl     dx, 1
                shl     dx, 1
                mov     cl, 3
                shl     si, cl
                shl     di, cl
                mov     es, cs:word_2A4
                push    word ptr [si]
                push    word ptr [si+2]
                push    word ptr [si+4]
                push    word ptr [si+6]
                test    cs:byte_8FA, 4
                jz      short loc_969
                mov     byte ptr [si+7], 0FFh

loc_969:                                ; CODE XREF: drv_fn15_put_char+65↑j
                test    cs:byte_8FA, 8
                jz      short loc_97C
                not     word ptr [si]
                not     word ptr [si+2]
                not     word ptr [si+4]
                not     word ptr [si+6]

loc_97C:                                ; CODE XREF: drv_fn15_put_char+71↑j
                mov     cx, 8
                mov     bx, di

loc_981:                                ; CODE XREF: drv_fn15_put_char+CC↓j
                shl     di, 1
                mov     di, cs:[di+68h]
                add     di, dx
                mov     al, cs:byte_8FC
                cmp     al, 0FFh
                jz      short loc_999
                mov     ah, al
                stosw
                stosw
                sub     di, 4

loc_999:                                ; CODE XREF: drv_fn15_put_char+92↑j
                lodsb
                or      al, al
                jz      short loc_9C7
                push    bx
                push    cx
                mov     cl, 6

loc_9A2:                                ; CODE XREF: drv_fn15_put_char+C5↓j
                mov     bl, al
                shr     bl, cl
                and     bx, 3
                sub     cl, 2
                mov     bl, cs:[bx+29Ah]
                not     bl
                and     es:[di], bl
                not     bl
                and     bl, cs:byte_8FB
                or      es:[di], bl
                inc     di
                or      cl, cl
                jns     short loc_9A2
                pop     cx
                pop     bx

loc_9C7:                                ; CODE XREF: drv_fn15_put_char+9E↑j
                inc     bx
                mov     di, bx
                loop    loc_981
                pop     word ptr [si-2]
                pop     word ptr [si-4]
                pop     word ptr [si-6]
                pop     word ptr [si-8]
                mov     cs:word_2A8, 0
                retf
drv_fn15_put_char endp

; [00000001 BYTES: COLLAPSED FUNCTION drv_fn10_load_image. PRESS NUMPAD+ TO EXPAND]
                db  90h

; =============== S U B R O U T I N E =======================================


drv_fn12_draw_op12 proc far             ; CODE XREF: drv:entry_12↑j
                mov     es, cs:word_2A4
                mov     ds, cs:word_64
                mov     dx, cx
                mov     si, ax
                mov     cl, 5
                shl     si, cl
                shr     bx, 1
                mov     ax, 8

loc_9F9:                                ; CODE XREF: drv_fn12_draw_op12+29↓j
                mov     di, dx
                shl     di, 1
                mov     di, cs:[di+68h]
                add     di, bx
                mov     cx, 4
                rep movsb
                inc     dx
                dec     ax
                jnz     short loc_9F9
                retf
drv_fn12_draw_op12 endp


; =============== S U B R O U T I N E =======================================


drv_fn0F_load_res_a proc far            ; CODE XREF: drv:entry_0F↑j
                mov     cs:word_64, ax
                retf
drv_fn0F_load_res_a endp

; ---------------------------------------------------------------------------
                db  90h
; [00000001 BYTES: COLLAPSED FUNCTION drv_fn14_draw_image_alt. PRESS NUMPAD+ TO EXPAND]
; [00000001 BYTES: COLLAPSED FUNCTION drv_fn1F. PRESS NUMPAD+ TO EXPAND]
unk_A16         db    0                 ; DATA XREF: sub_B0C+1E↓o
                db    1
                db    2
                db    9
                db    6
                db    8
                db  0Ah
                db    3
                db    4
                db    5
                db    7
                db  0Bh
                db  0Ch
                db  0Dh
                db  0Eh
                db  0Fh
word_A26        dw 0                    ; DATA XREF: drv_fn16_monster_setup+29↓w
                                        ; drv_fn16_monster_setup+66↓r ...
word_A28        dw 0                    ; DATA XREF: drv_fn16_monster_setup+2↓w
                                        ; drv_fn16_monster_setup+BD↓r
word_A2A        dw 0                    ; DATA XREF: drv_fn16_monster_setup+16↓w

; =============== S U B R O U T I N E =======================================


drv_fn16_monster_setup proc far         ; CODE XREF: drv:entry_16↑j
                push    ds
                pop     es
                mov     cs:word_A28, bx
                mov     ds, ax
                xor     si, si
                lodsw
                mov     di, dx
                mov     dx, si
                stosb
                mov     cx, 1200h
                mul     cx
                mov     cs:word_A2A, ax
                mov     bx, ax
                or      ax, ax
                jz      short loc_A52
                dec     bx
                mov     cl, 4
                shr     bx, cl
                inc     bx

loc_A52:                                ; CODE XREF: drv_fn16_monster_setup+1E↑j
                call    sub_2AA
                mov     cs:word_A26, bx
                push    ds
                mov     bx, 120h
                inc     bx
                mov     ah, 48h
                int     21h             ; DOS - 2+ - ALLOCATE MEMORY
                                        ; BX = number of 16-byte paragraphs desired
                mov     es, ax
                xor     di, di
                mov     ax, di
                mov     cx, 900h
                rep stosw
                mov     ax, 0B800h
                mov     ds, ax
                assume ds:nothing
                mov     si, 20h ; ' '
                xor     di, di

loc_A78:                                ; CODE XREF: drv_fn16_monster_setup+62↓j
                push    si
                shl     si, 1
                mov     si, cs:[si+68h]
                add     si, 20h ; ' '
                mov     cx, 18h
                rep movsw
                pop     si
                inc     si
                cmp     si, 80h
                jnz     short loc_A78
                push    es
                pop     ds
                assume ds:nothing
                mov     es, cs:word_A26
                xor     si, si
                mov     di, si
                mov     cx, 900h
                rep movsw
                push    ds
                pop     es
                pop     ds
                mov     ax, 1
                call    sub_B0C
                push    ds
                push    es
                xor     si, si
                lodsw
                push    ax
                mov     bx, cs:word_A26
                mov     ds, bx
                mov     es, bx
                mov     di, 1200h

loc_ABB:                                ; CODE XREF: drv_fn16_monster_setup+99↓j
                dec     ax
                jz      short loc_AC7
                mov     cx, 900h
                xor     si, si
                rep movsw
                jmp     short loc_ABB
; ---------------------------------------------------------------------------

loc_AC7:                                ; CODE XREF: drv_fn16_monster_setup+90↑j
                pop     ax
                pop     es
                pop     ds

loc_ACA:                                ; CODE XREF: drv_fn16_monster_setup+A7↓j
                cmp     ax, 1
                jz      short loc_AD5
                call    sub_B0C
                dec     ax
                jmp     short loc_ACA
; ---------------------------------------------------------------------------

loc_AD5:                                ; CODE XREF: drv_fn16_monster_setup+A1↑j
                push    es
                mov     ax, ss
                mov     es, ax
                xor     si, si
                lodsw
                mov     dx, ax
                lodsw
                inc     dx
                shl     dx, 1
                mov     si, dx
                mov     cx, ax
                sub     cx, si
                mov     di, cs:word_A28
                rep movsb
                pop     bx
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                push    es
                mov     bx, ds
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                retf
drv_fn16_monster_setup endp

; ---------------------------------------------------------------------------
byte_B04        db 0                    ; DATA XREF: sub_B0C+5F↓w
                                        ; sub_B0C+BF↓r
byte_B05        db 0                    ; DATA XREF: sub_B0C+67↓w
                                        ; sub_B0C+98↓w
word_B06        dw 0                    ; DATA XREF: sub_B0C+37↓w
                                        ; sub_B0C+B5↓r ...
word_B08        dw 0                    ; DATA XREF: sub_B0C+51↓w
                                        ; sub_B0C+9F↓w ...
word_B0A        dw 0                    ; DATA XREF: sub_B0C+56↓w
                                        ; sub_B0C+A5↓w ...

; =============== S U B R O U T I N E =======================================


sub_B0C         proc near               ; CODE XREF: drv_fn16_monster_setup+7A↑p
                                        ; drv_fn16_monster_setup+A3↑p
                push    ax
                push    bx
                push    cx
                push    dx
                push    bp
                push    ds
                push    es
                dec     ax
                mov     dx, ax
                shl     ax, 1
                mov     si, ax
                mov     bp, [si+2]
                mov     ax, dx
                xor     dx, dx
                mov     cx, 1200h
                mul     cx
                mov     di, ax
                xor     si, si
                mov     bx, offset unk_A16
                mov     dx, ds
                push    es
                pop     ds
                mov     es, cs:word_A26
                push    ds
                mov     ds, dx
                mov     al, ds:[bp+0]
                cbw
                add     ax, 6
                shr     ax, 1
                mov     cs:word_B06, ax
                mov     al, ds:[bp+1]
                cbw
                add     ax, 6
                mov     cl, 4
                shl     ax, cl
                add     si, ax
                add     di, ax
                shl     ax, 1
                add     si, ax
                add     di, ax
                mov     cs:word_B08, si
                mov     cs:word_B0A, di
                mov     al, ds:[bp+2]
                mov     cs:byte_B04, al
                mov     al, ds:[bp+3]
                mov     cs:byte_B05, al
                add     bp, 4
                pop     ds
                xor     ah, ah

loc_B7D:                                ; CODE XREF: sub_B0C+101↓j
                push    ds
                mov     ds, dx
                mov     al, ds:[bp+0]
                inc     bp
                pop     ds
                mov     cl, al
                and     cx, 0F0h
                shr     cl, 1
                shr     cl, 1
                shr     cl, 1
                shr     cl, 1
                and     al, 0Fh
                or      al, 80h
                cmp     al, 85h
                jz      short loc_BA0
                and     al, 7Fh
                xlat    byte ptr cs:[bx]

loc_BA0:                                ; CODE XREF: sub_B0C+8E↑j
                                        ; sub_B0C+FF↓j
                or      ah, ah
                jnz     short loc_BD0
                dec     cs:byte_B05
                js      short loc_C10
                add     cs:word_B08, 30h ; '0'
                add     cs:word_B0A, 30h ; '0'
                mov     si, cs:word_B08
                mov     di, cs:word_B0A
                add     si, cs:word_B06
                add     di, cs:word_B06
                mov     ah, cs:byte_B04

loc_BD0:                                ; CODE XREF: sub_B0C+96↑j
                test    al, 80h
                jz      short loc_BE5
                mov     ch, [si]
                test    ah, 1
                jz      short loc_BE0
                and     ch, 0Fh
                jmp     short loc_BF4
; ---------------------------------------------------------------------------

loc_BE0:                                ; CODE XREF: sub_B0C+CD↑j
                and     ch, 0F0h
                jmp     short loc_BF4
; ---------------------------------------------------------------------------

loc_BE5:                                ; CODE XREF: sub_B0C+C6↑j
                mov     ch, al
                test    ah, 1
                jnz     short loc_BF4
                shl     ch, 1
                shl     ch, 1
                shl     ch, 1
                shl     ch, 1

loc_BF4:                                ; CODE XREF: sub_B0C+D2↑j
                                        ; sub_B0C+D7↑j ...
                test    ah, 1
                jnz     short loc_BFE
                mov     es:[di], ch
                jmp     short loc_C07
; ---------------------------------------------------------------------------

loc_BFE:                                ; CODE XREF: sub_B0C+EB↑j
                and     byte ptr es:[di], 0F0h
                or      es:[di], ch
                inc     si
                inc     di

loc_C07:                                ; CODE XREF: sub_B0C+F0↑j
                dec     ah
                dec     cl
                jns     short loc_BA0
                jmp     loc_B7D
; ---------------------------------------------------------------------------

loc_C10:                                ; CODE XREF: sub_B0C+9D↑j
                pop     es
                pop     ds
                pop     bp
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                retn
sub_B0C         endp


; =============== S U B R O U T I N E =======================================


drv_fn17_monster_draw proc far          ; CODE XREF: drv:entry_17↑j
                cmp     ax, 0FFFFh
                jnz     short loc_C37
                mov     bx, cs:word_A26
                or      bx, bx
                jz      short loc_C35
                push    es
                mov     es, bx
                mov     ah, 49h
                int     21h             ; DOS - 2+ - FREE MEMORY
                                        ; ES = segment address of area to be freed
                pop     es
                mov     cs:word_A26, 0

loc_C35:                                ; CODE XREF: drv_fn17_monster_draw+C↑j
                jmp     short locret_C6B
; ---------------------------------------------------------------------------

loc_C37:                                ; CODE XREF: drv_fn17_monster_draw+3↑j
                push    bp
                mov     bp, 60h ; '`'
                mov     di, cx
                or      ax, ax
                jz      short loc_C48
                mov     cx, 1200h
                xor     dx, dx
                mul     cx

loc_C48:                                ; CODE XREF: drv_fn17_monster_draw+27↑j
                mov     ds, cs:word_A26
                mov     si, ax
                mov     ax, 0B800h
                mov     es, ax
                assume es:nothing
                shr     bx, 1

loc_C56:                                ; CODE XREF: drv_fn17_monster_draw+50↓j
                push    di
                shl     di, 1
                mov     di, cs:[di+68h]
                add     di, bx
                mov     cx, 18h
                rep movsw
                pop     di
                inc     di
                dec     bp
                jnz     short loc_C56
                pop     bp

locret_C6B:                             ; CODE XREF: drv_fn17_monster_draw:loc_C35↑j
                retf
drv_fn17_monster_draw endp

drv             ends


                end
