"""Generates src/mm2_tables_gen.c: numeric tables read from the EXE's DGROUP (see docs/).
    python gen_c_tables.py > ../src/mm2_tables_gen.c"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mm2_layout import Layout  # noqa: E402

lay = Layout()
d, _ = lay.read_segment(lay.dgroup)


def u8(a, n): return list(d[a:a + n])
def u16(a, n): return list(struct.unpack_from("<%dH" % n, d, a))
def u32(a, n): return list(struct.unpack_from("<%dI" % n, d, a))


def arr(ctype, name, vals, per=8):
    lines = ["%s %s[%d] = {" % (ctype, name, len(vals))]
    for i in range(0, len(vals), per):
        lines.append("\t" + ", ".join(str(v) for v in vals[i:i + per]) + ",")
    lines.append("};")
    return "\n".join(lines)


out = ["/* Generated by tools/gen_c_tables.py from MM2.EXE DGROUP; do not edit. */",
       '#include "mm2_tables.h"', ""]
out.append(arr("const uint32_t", "MM2_EXP_TABLE", u32(0x2E5C + 2 * 4, 9) + [0] * 0 + u32(0x2E5C + 0x24 + 8, 9), 9) + "  /* [group][level 2..10] */")
out.append("")
out.append(arr("const uint16_t", "MM2_TOWN_MULT", u16(0x2F04, 5)))
out.append(arr("const uint16_t", "MM2_TOWN_HP_DIV", u16(0x2F0E, 5)))
out.append(arr("const uint16_t", "MM2_HP_PER_LEVEL", u16(0x2F18, 8)))
out.append(arr("const uint8_t", "MM2_SWING_DIV", u8(0x101A, 8)))
out.append(arr("const uint8_t", "MM2_HIT_DIV", u8(0x1012, 8)))
out.append(arr("const uint8_t", "MM2_MONSTER_TOHIT", u8(0x103A, 16)))
out.append(arr("const uint8_t", "MM2_STAT_BRACKET", u8(0x4D84, 23)))
out.append(arr("const uint8_t", "MM2_RACE_STAT_ADJ", u8(0x93C, 35), 7) + "  /* [race][Might,Int,Per,End,Spd,Acc,Luck]; 255 = -1 */")
out.append(arr("const uint8_t", "MM2_RACE_RESIST", u8(0x6AE, 48), 6) + "  /* [k][race] k = 0..7 -> char +16+k */")
out.append(arr("const uint8_t", "MM2_START_THIEVERY", u8(0x6DE, 8)))
out.append(arr("const uint16_t", "MM2_START_HP", u16(0x6E6, 8)))
out.append(arr("const uint16_t", "MM2_ENDURANCE_HP", u16(0x6F2, 22)))
out.append(arr("const uint16_t", "MM2_START_SP", u16(0x71E, 23)))
out.append(arr("const uint8_t", "MM2_START_AC", u8(0x74D, 15)))
out.append(arr("const uint8_t", "MM2_START_ITEM", u8(0x75C, 64), 8) + "  /* [tier][class] */")
print("\n".join(out))
