#!/usr/bin/env python3
"""Replaces numeric field ids at game-data accessor call sites with the named
constants from vstables/fieldIds.h (generated by gen_field_ids.py), e.g.

    _ref.GetBool(0x124)   ->   _ref.GetBool(kSceneIsMenu)

Only the property-accessor family (GetInt/GetBool/GetLink/SetValue/...) is
touched, and only hex literals that are known field ids. Files that change get
`#include "vstables/fieldIds.h"` added. Idempotent.

Usage: python tools/apply_field_ids.py [source dir] [xml_names.tsv]
"""
import csv
import os
import re
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else "src/deponia1"
NAMES = sys.argv[2] if len(sys.argv) > 2 else "manifest/xml_names.tsv"

ACCESSORS = ("GetBool|GetInt|GetFloat|GetStr|GetStrHolder|GetStrings|GetPath|GetLink|GetLinks|GetPoint|GetPoints|"
             "GetRect|GetRects|GetList|GetSprite|GetTexts|SetValue|SetLink|ClearLink|SetLinkAnyObject")
CALL = re.compile(r"\b(" + ACCESSORS + r")\(0x([0-9A-Fa-f]+)\b")

by_id = {}
used = set()
with open(NAMES, encoding="utf-8") as f:
    for r in csv.DictReader(f, delimiter="\t"):
        ident = int(r["id"])
        if ident in by_id:
            continue
        name = r["name"]
        const = "k" + name[0].upper() + name[1:]
        if const in used:
            const = f"{const}_0x{ident:X}"
        used.add(const)
        by_id[ident] = const


def process(path):
    with open(path, encoding="utf-8", newline="") as f:
        text = f.read()
    changed = [0]

    def repl(m):
        ident = int(m.group(2), 16)
        if ident not in by_id:
            return m.group(0)
        changed[0] += 1
        return f"{m.group(1)}({by_id[ident]}"

    new = CALL.sub(repl, text)
    if changed[0] == 0:
        return 0
    if '#include "vstables/fieldIds.h"' not in new:
        include = '#include "vstables/fieldIds.h"\n'
        m = re.search(r'#include "datastruct/visobjref\.h"\r?\n', new)
        if m:
            new = new[:m.end()] + include + new[m.end():]
        else:
            ms = list(re.finditer(r'^#include .*\r?\n', new, re.M))
            if ms:
                new = new[:ms[-1].end()] + include + new[ms[-1].end():]
            else:
                new = include + new
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(new)
    return changed[0]


total = 0
for dirpath, _, files in os.walk(ROOT):
    for name in files:
        if name.endswith((".cpp", ".h")) and name != "fieldIds.h":
            n = process(os.path.join(dirpath, name))
            if n:
                print(f"{os.path.join(dirpath, name)}: {n}")
                total += n
print(f"{total} replacements")
