#!/usr/bin/env python3
"""Generates the data-record schema code from manifest/schema_*.tsv (see
extract_schema.py): for every record class (TTFont, TTScene, TSAction, ...)

    static TTypeGroup &GetTypeGroup();
    static void InitType(int versionLow, int versionHigh);

The group's constructor arguments come from the class's static initializer in
the binary, the field list from its InitType(); both are written out exactly as
read. The classes without a hand-written header (see HAND_HEADERS) are also
declared here, in vstables/records.h; the others get the two declarations
patched into their own header (this script does that idempotently).

Writes src/<game>/vstables/records.h and records.cpp.

Usage: python tools/gen_records.py [game dir, default src/deponia1]
"""
import csv
import os
import re
import sys

GAME = sys.argv[1] if len(sys.argv) > 1 else "src/deponia1"

TYPE_NAMES = {0: "kBool", 1: "kInt", 2: "kString", 3: "kPath", 4: "kFloat", 5: "kUnused5", 6: "kRectList",
              7: "kSpriteList", 8: "kPointList", 9: "kStringList", 10: "kIntList", 11: "kPathList",
              12: "kFloatList", 13: "kPoint", 14: "kRect", 15: "kSprite", 16: "kLink", 17: "kLinkList",
              18: "kTextList"}

# Classes that already have a hand-written header: (header, class)
HAND_HEADERS = {"TTScene": "TTScene.h", "TTAction": "TTAction.h", "TTButton": "TTButton.h",
                "TTText": "TTText.h", "TSText": "TSText.h"}

# Classes whose callbacks include GetNameInList.
def const_names():
    used = set()
    by_id = {}
    with open("manifest/xml_names.tsv", encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            ident = int(r["id"])
            if ident in by_id:
                continue
            name = r["name"]
            const = "k" + name[0].upper() + name[1:]
            if const in used:
                const = f"{const}_0x{ident:X}"
            used.add(const)
            by_id[ident] = const
    return by_id


CONSTS = const_names()


def field_const(ident):
    return CONSTS.get(ident, f"static_cast<eFieldId>({ident})")


def load():
    groups = {}
    with open("manifest/schema_groups.tsv", encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            groups[r["class"]] = r
    fields = {}
    with open("manifest/schema_fields.tsv", encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            fields.setdefault(r["class"], []).append(r)
    for rows in fields.values():
        rows.sort(key=lambda r: int(r["order"]))
    return groups, fields


def num(v):
    return str(int(v))


def type_data(row):
    t = TYPE_NAMES[int(row["type"])]
    ident = field_const(int(row["id"]))
    kind = row["kind"]
    vin, vout = num(row["version_in"]), num(row["version_out"])
    if kind == "plain":
        return f"TTypeData({ident}, eTypeData::{t}, {vin}, {vout})"
    if kind == "link":
        return f"TTypeData({ident}, eTypeData::{t}, static_cast<eVisionaireTable>({num(row['link'])}), {vin}, {vout})"
    return (f"TTypeData({ident}, eTypeData::{t}, static_cast<eSaveGame>({num(row['savegame'])}), {vin}, {vout}, "
            f"{num(row['save_in'])}, {num(row['save_out'])})")


def main():
    groups, fields = load()
    classes = sorted(groups)

    h = ["// Generated by tools/gen_records.py from manifest/schema_*.tsv - do not edit.",
         "//",
         "// The data-record classes of the game schema: each is a typed handle onto one",
         "// kind of game-data object (a TVisObjRef) and owns the TTypeGroup describing",
         "// that kind's fields. Recovered from the static initializers and InitType()",
         "// functions of the original (Deponia_Linux.asm lines 1446937-1526200); the",
         "// classes that have a hand-written header declare their own copies of",
         "// GetTypeGroup()/InitType().",
         "#pragma once",
         "",
         '#include "datastruct/typegrp.h"',
         '#include "datastruct/visobjref.h"',
         "",
         "class TVisionaireObject;",
         ""]
    c = ["// Generated by tools/gen_records.py from manifest/schema_*.tsv - do not edit.",
         "",
         '#include "vstables/records.h"',
         "",
         '#include "TSText.h"',
         '#include "TTAction.h"',
         '#include "TTButton.h"',
         '#include "TTScene.h"',
         '#include "TTText.h"',
         '#include "vstables/fieldIds.h"',
         ""]

    for cls in classes:
        g = groups[cls]
        cb = [x for x in g["callbacks"].split(",") if x]
        hand = cls in HAND_HEADERS
        if not hand:
            h.append(f"class {cls} : public TVisObjRef {{")
            h.append("public:")
            h.append(f"\t{cls}() = default;")
            h.append(f"\texplicit {cls}(const TVisObjRef &ref) : TVisObjRef(ref) {{")
            h.append("\t}")
            h.append("")
            h.append("\tstatic TTypeGroup &GetTypeGroup();")
            h.append("\tstatic void InitType(int versionLow, int versionHigh);")
            if "OnCreate" in cb:
                h.append("\tstatic void OnCreate(TVisionaireObject *object);")
            if "OnInit" in cb:
                h.append("\tstatic void OnInit(TVisionaireObject *object);")
            if "GetNameInList" in cb:
                h.append("\tstatic wxString GetNameInList(const TVisionaireObject *object);")
            h.append("};")
            h.append("")

        table = f"static_cast<eVisionaireTable>({num(g['table'])})"
        desc = num(g["desc"])
        vin, vout = num(g["version_in"]), num(g["version_out"])
        c.append(f"// Recovered group of {cls} (\"{g['desc_name']}\", table {num(g['table'])}).")
        c.append(f"TTypeGroup &{cls}::GetTypeGroup() {{")
        if g["form"] == "save":
            c.append(f"\tstatic TTypeGroup typeGroup({desc}, {table}, static_cast<eSaveGame>({g['save_type']}), {vin}, {vout}, "
                     f"{g['save_in']}, {g['save_out']});")
        else:
            c.append(f"\tstatic TTypeGroup typeGroup({desc}, {table}, {vin}, {vout});")
        c.append("\treturn typeGroup;")
        c.append("}")
        c.append("")
        c.append(f"void {cls}::InitType(int versionLow, int versionHigh) {{")
        c.append("\tTTypeGroup &group = GetTypeGroup();")
        c.append("")
        c.append("\tgroup.ClearTypes(versionLow, versionHigh);")
        for row in fields.get(cls, []):
            c.append(f"\tgroup.AddType({type_data(row)});")
        cbs = []
        if "OnCreate" in cb:
            cbs.append(f"\tgroup.SetCreate({cls}::OnCreate);")
        if "OnInit" in cb:
            cbs.append(f"\tgroup.SetInit({cls}::OnInit);")
        if "GetNameInList" in cb:
            cbs.append(f"\tgroup.SetNameInList({cls}::GetNameInList);")
        if cbs:
            c.append("")
            c.extend(cbs)
        c.append("}")
        c.append("")

    c.append("// Builds every record type for the given file-version range, in the order the")
    c.append("// binary's TVisionaireGame::InitWithVersion() does it.")
    c.append("void InitRecordTypes(int versionLow, int versionHigh) {")
    for cls in classes:
        c.append(f"\t{cls}::InitType(versionLow, versionHigh);")
    c.append("}")
    c.append("")
    h.append("/** Builds every record type for a file-version range. */")
    h.append("void InitRecordTypes(int versionLow, int versionHigh);")
    h.append("")

    with open(os.path.join(GAME, "vstables", "records.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(h))
    with open(os.path.join(GAME, "vstables", "records.cpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(c))

    # patch the hand-written headers
    for cls, header in HAND_HEADERS.items():
        path = os.path.join(GAME, header)
        text = open(path, encoding="utf-8", newline="").read()
        nl = "\r\n" if "\r\n" in text else "\n"
        text = text.replace("\r\n", "\n")
        if "static TTypeGroup &GetTypeGroup();" in text:
            continue
        cb = [x for x in groups[cls]["callbacks"].split(",") if x]
        decl = ["\t// Recovered from the binary's schema (vstables/records.cpp).",
                "\tstatic TTypeGroup &GetTypeGroup();",
                "\tstatic void InitType(int versionLow, int versionHigh);"]
        if "OnCreate" in cb:
            decl.append("\tstatic void OnCreate(TVisionaireObject *object);")
        if "OnInit" in cb:
            decl.append("\tstatic void OnInit(TVisionaireObject *object);")
        if "GetNameInList" in cb:
            decl.append("\tstatic wxString GetNameInList(const TVisionaireObject *object);")
        m = re.search(r"class %s\b[^{]*\{\npublic:\n" % cls, text)
        if not m:
            print("cannot patch", header)
            continue
        text = text[:m.end()] + "\n".join(decl) + "\n\n" + text[m.end():]
        if '#include "datastruct/typegrp.h"' not in text:
            text = text.replace("#pragma once\n", '#pragma once\n\n#include "datastruct/typegrp.h"\n', 1)
        open(path, "w", encoding="utf-8", newline="").write(text.replace("\n", nl))
    print(f"{len(classes)} classes")


main()
