#!/usr/bin/env python3
"""Generates <game>/vstables/xmlNamesData.h from manifest/xml_names.tsv: the
two name tables the engine registers through TXMLNames::AddXMLName().

TXMLNames::InitXMLNamesIntern() adds ids 1-58 one by one and then ids 59-99 in
a loop, all under the placeholder name "DSunused"; TVisionaireGame::
InitXMLNames() adds ids 100 up (the data-field names). The header holds both as
plain `const char *` arrays in id order.

Usage: python tools/gen_xml_names.py [manifest/xml_names.tsv] [out.h]
"""
import csv
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "manifest/xml_names.tsv"
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/deponia1/vstables/xmlNamesData.h"

names = {}
with open(SRC, encoding="utf-8") as f:
    for r in csv.DictReader(f, delimiter="\t"):
        names[int(r["id"])] = r["name"]

intern = [names[i] for i in range(1, 59)]
game = [names[i] for i in range(100, max(names) + 1)]
assert len(game) == max(names) - 99, "gap in the data-field ids"


def emit(f, ident, items):
    f.write(f"static const char *const {ident}[] = {{\n")
    for name in items:
        f.write(f'\t"{name}",\n')
    f.write("};\n")


with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("""// Generated by tools/gen_xml_names.py from manifest/xml_names.tsv - do not edit.
//
// The XML names the engine registers with TXMLNames::AddXMLName(): ids 1-58
// (TXMLNames::InitXMLNamesIntern) followed by ids 59-99, all "DSunused" (a
// loop in that function), then ids 100 up (TVisionaireGame::InitXMLNames).
#pragma once

""")
    emit(f, "kInternXMLNames", intern)
    f.write("\n")
    emit(f, "kGameXMLNames", game)
print(f"{len(intern)} intern + {len(game)} game names -> {OUT}")
