#!/usr/bin/env python3
"""Generates <game>/vstables/fieldIds.h from manifest/xml_names.tsv.

Every property of a game-data record (TVisObjRef::GetInt(0x124),
SetLink(0x1F7, ...), ...) is addressed by a numeric field id; the engine's own
XML names for those ids (extracted by extract_xml_names.py) name them, e.g.
0x124 = "SceneIsMenu". The header gives each a `kCamelCase` constant so call
sites read GetBool(kSceneIsMenu) instead of GetBool(0x124).

Usage: python tools/gen_field_ids.py [manifest/xml_names.tsv] [out.h]
"""
import csv
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "manifest/xml_names.tsv"
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/deponia1/vstables/fieldIds.h"

seen = {}
rows = []
with open(SRC, encoding="utf-8") as f:
    for r in csv.DictReader(f, delimiter="\t"):
        ident = int(r["id"])
        name = r["name"]
        if ident in seen:
            continue  # an id re-added under a second name keeps the first
        seen[ident] = name
        rows.append((ident, name))

used = set()
lines = []
for ident, name in sorted(rows):
    const = "k" + name[0].upper() + name[1:]
    if const in used:
        const = f"{const}_0x{ident:X}"
    used.add(const)
    lines.append(f"\t{const} = 0x{ident:X},")

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("""// Generated by tools/gen_field_ids.py from manifest/xml_names.tsv - do not edit.
//
// Field ids of the game-data schema (the integer every TVisObjRef/
// TVisionaireObject property accessor takes), named after the engine's own
// XML element names (recovered from TVisionaireGame::InitXMLNames(),
// Deponia_Linux.asm). The constants keep the original names verbatim, so
// they read as the data files do ("SceneIsMenu", "CharacterScene", ...).
#pragma once

enum eFieldId {
""")
    f.write("\n".join(lines))
    f.write("\n};\n")
print(f"{len(lines)} field ids -> {OUT}")
